### ISSUE TITLE
Allow pagination on GET /transactions/address/

### ISSUE THREAD

**Issue by javichi** [wavesplatform/Waves#1000]
Current limit is 10k transactions. If you have more than 10k transactions you are not able to retrieve them.

I understand the need for this limit but there should be at least a way to paginate through all your transactions. For instance:

GET /transactions/address/{address}/limit/{limit}/page/{page}

**Comment by javichi** [comment]
If the above solution is difficult to implement maybe we could paginate based on blocks. For instance:

GET /transactions/address/{address}/limit/{limit}/fromblock/{fromblock}

**Comment by 0xae** [comment]
Very interesting problem, i wonder which api of the waves blockchain you would need in order to implement this.

**Comment by roccomuso** [comment]
I saw on the swagger doc an `after` param to paginate but it looks broken.
Any news on this?
