### ISSUE TITLE
php api?

### ISSUE THREAD

**Issue by Goddard** [wavesplatform/Waves#1006]
any php api? or javascript examples?

**Comment by vsuharnikov** [comment]
no API for PHP right no, sorry. But we have for javascript: https://github.com/wavesplatform/waves-api

**Comment by Goddard** [comment]
This isn't really javascript.  This is nodeJS.

**Comment by fourclub** [comment]
will be is api for php?

**Comment by vsuharnikov** [comment]
Sorry guys, we haven't such plans :(
