### ISSUE TITLE
API failed to parse json

### ISSUE THREAD

**Issue by sarosbacz** [wavesplatform/Waves#1007]
Chain: testnet.
URL: 'http://127.0.0.1:6870/assets/masstransfer' 
Headers: {'X-Api-Key': 'ridethewaves!', 'Content-type': 'application/json'}
Method: POST.
Passing json, but getting 
{'error': 1, 'cause': None, 'message': 'failed to parse json message', 'validationErrors': {'obj.version': [{'args': [], 'msg': ['error.path.missing']}]}}. 
Same with /assets/transfer.

**Comment by vsuharnikov** [comment]
JSON should be in a format:
https://docs.wavesplatform.com/development-and-api/waves-node-rest-api/asset-transactions/private-functions.html#post-assetsmasstransfer

**Comment by vsuharnikov** [comment]
Also, try to add in JSON:
```
"version": 1
```

**Comment by vsuharnikov** [comment]
Please use https://docs.wavesplatform.com/development-and-api/waves-node-rest-api/transactions.html#post-transactionsbroadcast for this

**Comment by monroid** [comment]
@sarosbacz Did you have a chance to check the transaction broadcast method?

**Comment by monroid** [comment]
In case of failure of the new method, please reopen the issue.
