### ISSUE TITLE
Failed to mine after launching genisis.

### ISSUE THREAD

**Issue by the-valeryard** [wavesplatform/Waves#1018]
I followed the tutorial located here https://github.com/wavesplatform/Waves/wiki/Creating-a-private-Waves-blockchain-network however when I launch the node with my custom config it begins running however it fails to generate new blocks after that it just stops. Hopping for some insight on why this might be happening.

[info] Running (fork) com.wavesplatform.Application waves-custom-network.conf
[info] 2018-04-15 22:08:38,514 INFO  [main] c.w.Application$ - Starting...
[info] 2018-04-15 22:08:39,640 INFO  [main] kamon.Kamon$Instance - Initializing Kamon...
[info] 2018-04-15 22:08:40,108 INFO  [ctor.default-dispatcher-3] a.event.slf4j.Slf4jLogger - Slf4jLogger started
[info] 2018-04-15 22:08:41,014 INFO  [ctor.default-dispatcher-2] a.event.slf4j.Slf4jLogger - Slf4jLogger started
[info] 2018-04-15 22:08:41,046 INFO  [main] c.w.Application$ - Waves v20180416T010809 Blockchain Id: 8
[info] 2018-04-15 22:08:49,358 INFO  [main] c.w.Application - Node REST API was bound on 127.0.0.1:6869
[info] 2018-04-15 22:08:49,374 INFO  [main] c.w.s.BlockchainUpdaterImpl - State rebuild started, total persisted blocks: 0, [ in-memory: (?h=0, ?txs=0) ] + persisted: h=0
[info] 2018-04-15 22:08:49,468 INFO  [main] c.w.state2.StateWriterImpl - BlockDiff commit complete. Persisted height = 0
[info] 2018-04-15 22:08:49,468 INFO  [main] c.w.s.BlockchainUpdaterImpl - State rebuild finished, total persisted blocks: 0, [ in-memory: (?h=0, ?txs=0) ] + persisted: h=0
[info] 2018-04-15 22:08:56,343 INFO  [main] c.w.s.BlockchainUpdaterImpl - Block(TWMwwS6QKnnF5u5tqtUeTMVtsrsjUcaujnmNTVVMmxn4YmgccasWQ5wZ37mh9U7Hv1qCFg4kRJK4iTNRNWe1moz -> 67rpwLC..., txs=2, features=Set()) appended. New height: 1)
[info] 2018-04-15 22:08:56,343 INFO  [main] com.wavesplatform.package$ - Genesis block has been added to the state
[info] 2018-04-15 22:08:56,343 INFO  [main] s.wallet.Wallet$WalletImpl - Added account #1
[info] 2018-04-15 22:08:57,874 INFO  [main] c.w.Application - REST API was bound on 127.0.0.1:6869

**Comment by alexeykiselev** [comment]
Probably it isn't stopped. You just have to wait a long time for the next block.
Please, check timestamp at `debug/minerInfo` API. You may have to adjust initial base target and genesis block timestamps, to correct the second block interval.

**Comment by alexeykiselev** [comment]
Yes, it means that you don't have an account with enough balance (1k/10k Waves) or Miner is disabled in the configuration file.
You may want to distribute some coins to initial miners accounts in genesis block.
