### ISSUE TITLE
data transaction error

### ISSUE THREAD

**Issue by gapaus** [wavesplatform/Waves#1067]
Hello everyone!
I need to create a data transaction and I took an example from the documentation https://docs.wavesplatform.com/technical-details/data-transaction.html and it doesn't work.

POST /addresses/data
{
  "sender": "3My8vJAdUDy5E57LtJiL9hv8YbUqe3axjpp",
  "fee": 100000,
  "data": [{
    "key": "int",
    "type": "integer",
    "value": 24
  }]
}
Response:
{
  "error": 1,
  "message": "failed to parse json message",
  "cause": null,
  "validationErrors": {
    "obj.version": [{
      "msg": ["error.path.missing"],
      "args": []
    }]
  }
}

**Comment by monroid** [comment]
Hi @gapaus, 
could you try this one
{
"version" : 1,
"sender": "3My8vJAdUDy5E57LtJiL9hv8YbUqe3axjpp",
"fee": 100000,
"data": [{
"key": "int",
"type" : "integer",
"value": 24
}]
}

**Comment by petermz** [comment]
This version thingy was missing from the doc -- sorry about that. I'm going to add it there now

**Comment by gapaus** [comment]
Thanks. I have a few more questions. 
1. When will data transactions appear in mainnet? 
2. Will they be displayed in the explorer? 
3. If you use an existing key, only the last value will be visible in the history (GET /addresses/data/{address}/{key}). Is it feature?

**Comment by Alex11211** [comment]
Получение Bitcoin
09:32, с адреса 3PAs2qSeUAfgqSKS8LpZPKGYEjJKcud9Djr
+0.00200529 Bitcoin
+18.42 US Dollar


2018-05-03 14:58 GMT+03:00 Nastya Urlapova <notifications@github.com>:

**Comment by vsuharnikov** [comment]
> When will data transactions appear in mainnet?
When we fix all bugs in v0.13. Then we release it on mainnet and the feature will be available for voting.

> Will they be displayed in the explorer?
In the middle/end of June, I suppose.

> If you use an existing key, only the last value will be visible in the history (GET /addresses/data/{address}/{key}). Is it feature?
Right, we store only the latest value for all keys. Storing of all history is too expensive for disk.

**Comment by monroid** [comment]
@gapaus
 
1. Data Transaction is available on MainNet, you can use full functionality of its in both Waves Client and RestAPI
2. Here is example of Data Transaction in explorer - https://nodes.wavesnodes.com/transactions/info/EByjQAWDRGrmc8uy7xRGy2zsQXZQq59bav7h8oTTJyHC

So if you have additional question about Data Transaction, please feel free to create an issue.
