### ISSUE TITLE
TXs returned by 'GET /transactions/address/' are not sorted by time

### ISSUE THREAD

**Issue by PyWaves** [wavesplatform/Waves#107]
According to API documentation, the GET /transactions/address/{address}/limit/{limit} method should return the specified number of the "latest" transactions by the given account address.
This seems to work in some cases, for example if the accounts has only simple txs (type 2). However, if there are asset txs (type 3 and 4), the returned list is not sorted by time.

**Comment by phearnot** [comment]
#1971 finally fixes pagination. Transactions for address will be returned in the order they appear in the blocks.

**Comment by Karasiq** [comment]
Fixed
