### ISSUE TITLE
How to install 0.12.0 mainnet waves node

### ISSUE THREAD

**Issue by top1st** [wavesplatform/Waves#1073]

**Comment by vsuharnikov** [comment]
Releases: https://github.com/wavesplatform/Waves/releases
Documentation: https://docs.wavesplatform.com/waves-full-node/how-to-install-a-node/how-to-install-a-node.html

The latest release for mainnet is v0.10.3. So v0.12.0 is not supported on mainnet, sorry.
Now we are fixing some bugs in v0.13 and when we will be ready, we release a new version for mainnet as soon as possible.
