### ISSUE TITLE
Most likely a typo

### ISSUE THREAD

**Issue by BlackTurtle123** [wavesplatform/Waves#1112]
https://github.com/wavesplatform/Waves/blob/7b6a61d4ba1b41f5f1fdb0be1370d82500095e0c/src/test/scala/com/wavesplatform/http/AssetsBroadcastRouteSpec.scala#L33

This needs to be failed instead of filed I think most likely?

**Comment by vsuharnikov** [comment]
I'll fix this in one of my PR, thanks
