### ISSUE TITLE
how to get WAVES only balance

### ISSUE THREAD

**Issue by j4ys0n** [wavesplatform/Waves#1205]
It's not totally clear how to get the balance of WAVES only. Is this documented somewhere? I haven't been able to find anything. I've got the block explorer api running locally but I'm not sure which endpoint I should use.

**Comment by username1565** [comment]
Hello.
If you mean the type of WAVES balance in block-explorer, like this:
https://wavesblockexplorer.com/#!/address/3P2HNUd5VUPLMQkJmctTPEeeHumiPN2GkTb
then...

Regular Balance - Regular is your personal WAVES balance, and this is all YOUR WAVES.

Available Balance - balance, available for trading, and pending in opened orders, this is balance, excluded all your leased WAVES.

Effective Balance - Effective is your Regular balance, plus any received leases, minus any WAVES you have leased to another node.

Generating Balance - Generating is the amount actually used for mining on the node, which equals your Effective balance, with received and cancelled leases confirmed after 1,000 blocks.
