### ISSUE TITLE
Asset balances at specific number of confirmatons

### ISSUE THREAD

**Issue by djpnewton** [wavesplatform/Waves#1206]
This is possible for WAVES (eg http://127.0.0.1:6869/addresses/balance/:address/:confirmations)

But I cant seem to find a method of querying the confirmed balance of any other assets

**Comment by monroid** [comment]
Hi @djpnewton,
yep, you are right, there isn't a function to get confirmed balance for custom asset in RestAPI. 
If you need such functionality, please feel free to create topic on our forum: https://forum.wavesplatform.com/latest.
