### ISSUE TITLE
Connection Refused when accessing node from a remote IP

### ISSUE THREAD

**Issue by mcb345** [wavesplatform/Waves#1229]
I have my connection refused when connecting to Waves node from a remote IP, any idea to enable remote ip ? on bitcoin its something like `rpcallowip=0.0.0.0/0`

**Comment by alexeykiselev** [comment]
API is bound to the localhost by default on Mainnet. But it's possible to change it in node's configuration file. 
Use parameters `waves.rest-api.enable` and `waves.rest-api.bind-address` for that. Please, refer to [documentation](https://docs.wavesplatform.com/en/waves-full-node/how-to-configure-a-node.html).
