### ISSUE TITLE
Data transaction error on mainnet

### ISSUE THREAD

**Issue by Minstel** [wavesplatform/Waves#1250]
`State check failed. Reason: ActivationError(DataTransaction transaction has not been activated yet)`

That's when attempted to create data transaction from localy run node in mainnet. Used `waves-all-0.13.3.jar`

**Comment by alexeykiselev** [comment]
It's not activated yet, please, wait a little:
 * Feature 5 (Data Transaction)
   Status           : APPROVED
   Activation       : 1060000 (Jun 28 2018 06:35 UTC, ~ in 93 hrs, 3 mins)
