### ISSUE TITLE
Testnet node does not sign data transaction

### ISSUE THREAD

**Issue by Minstel** [wavesplatform/Waves#1255]
I'm launching a node localy, on Windows 7.

Node, launched with mainnet config, signs data transactions with no problems. But with testnet config it gives an error: `no private key for sender address in wallet`. As I understand, that's because there is no signature, as no `proofs` field is added to transaction.
But I've seen data transactions in testnet blockchain, so there is some way to sign them.

I've tryed `jar` from https://github.com/wavesplatform/Waves/releases/tag/v0.13.3. Also I've tryed localy built version.

Here's my testnet-config:

```

# Waves node settins
waves {

  # P2P Network settings
  network {
    # Network address
    bind-address = "0.0.0.0"

    # Port number
    port = 6863

    # Node name to send during handshake. Comment this string out to set random node name.
    node-name = "Minstel TESTNET node"

    # String with IP address and port to send as external address during handshake. Could be set automatically if uPnP is enabled.
    #declared-address = "1.2.3.4:6863"

    black-list-residence-time = 30 minutes
  }

  # Wallet settings
  wallet {
    # Password to protect wallet file
    password = "12345678"

    # Wallet seed as BASE58 string
    seed = "Seed of testnet wallet here"
  }

  # Blockchain settings
  blockchain.type = TESTNET

  # Matcher settings
  matcher {
    # Enable/disable matcher
    enable = yes

    # Matcher's account address
    # account = ""

    # Matcher REST API bind address
    bind-address = "127.0.0.1"

    # Matcher REST API port
    port = 6886

    price-assets = [
      "WAVES",
      "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe",
      "HyFJ3rrq5m7FxdkWtQXkZrDat1F7LjVVGfpSkUuEXQHj",
      "2xnE3EdpqXtFgCP156qt1AbyjpqdZ5jGjWo3CwTawcux",
      "6pmDivReTLikwYqQtJTv6dTcE59knriaodB3AK8T9cF8"
    ]

    predefined-pairs = [
      {amountAsset = "WAVES", priceAsset = "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe"},
      {amountAsset = "WAVES", priceAsset = "HyFJ3rrq5m7FxdkWtQXkZrDat1F7LjVVGfpSkUuEXQHj"},
      {amountAsset = "WAVES", priceAsset = "2xnE3EdpqXtFgCP156qt1AbyjpqdZ5jGjWo3CwTawcux"},
      {amountAsset = "WAVES", priceAsset = "6pmDivReTLikwYqQtJTv6dTcE59knriaodB3AK8T9cF8"},
      {amountAsset = "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe", priceAsset = "2aSqCbvCTgvCpwkGsk4mea4tCLG4Zgp69aQDhHNvRUZv"},
      {amountAsset = "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe", priceAsset = "8zEZuJcKPQmFuYgVe5ZMpxgiPLu5zBhjA6xgdGomQDaP"},
      {amountAsset = "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe", priceAsset = "D2MNuUyA38pSKoV7F7vpS15Uhw9nw5qfbrGUfCLRNuRo"},
      {amountAsset = "2xnE3EdpqXtFgCP156qt1AbyjpqdZ5jGjWo3CwTawcux", priceAsset = "HyFJ3rrq5m7FxdkWtQXkZrDat1F7LjVVGfpSkUuEXQHj"}
    ]
  }

  # Node's REST API settings
  rest-api {
    # Enable/disable node's REST API
    enable = yes

    # Network address to bind to
    bind-address = "0.0.0.0"

    # Port to listen to REST API requests
    port = 6869

    # Hash of API key string
    api-key-hash = "H6nsiifwYKYEx6YzYD7woP1XCn72RVvx6tC1zjjLXqsu"
  }

  features {
    supported = [5]
  }
}

#include "local.conf"


```

**Comment by alexeykiselev** [comment]
There is two ways to send transaction to the network:

1. Broadcast signed transaction using any node
2. Sign transaction using node's built-in wallet and broadcast it afterward

You've tried to do the latter, but you've provided the sender address for which there is on private key in node's wallet. You have to use the private key from the wallet in order to sing a transaction on the node.

If you haven't configured the wallet seed in configuration file, the seed, the private key and an address will be created for you on the fist start.

**Comment by Minstel** [comment]
@alexeykiselev 

> You've tried to do the latter, but you've provided the sender address for which there is on private key in node's wallet. 

I do not entirely understand this. Then it should not also work for mainnet configuration.
Besides, if I remember correctly, I use the addres, that was generated on first run.
I tryed now to remove existing `wallet.dat` file and all the data in `data` folder. After launching node, it generates a new `wallet.dat` file, so default wallet is created. But there is no information about seed or adress in console output of node (although I remember it was on the very first start). And I need to set the adress and sender public key in transaction data. Where should I take this information from?
