### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by coresh** [wavesplatform/Waves#1283]
Please check the documentation site:

https://docs.wavesplatform.com

404 returns most links:

[https://docs.wavesplatform.com/en/en/technical-details/waves-contracts-language-description.md](url)
[https://docs.wavesplatform.com/en/en/technical-details/technical-details.md](url)
[https://docs.wavesplatform.com/en/en/platform-features/smart-contracts.md](url)
[https://docs.wavesplatform.com/en/en/technical-details/waves-contracts-language-description.md](url)
...

**Comment by monroid** [comment]
@coresh Could you try to open those links from your environment one more time? For now https://docs.wavesplatform.com/en/ works fine, and there aren't errors like you reported. Another point, your links goes to https://github.com/wavesplatform/Waves/issues/url, that url doesn't exists.

**Comment by monroid** [comment]
If you will get 404 error for docs.wavesplatform.com in future, feel free report to us.
