### ISSUE TITLE
Minimal CPU/RAM requirements for mainnet node

### ISSUE THREAD

**Issue by arsenlosenko** [wavesplatform/Waves#1298]
Hello,

We downloaded latest release of mainnet node (in .jar file) and running it on a remote server (4 CPUs, 10 GB of RAM), but we have a significant delay in response from node to our application, which is running on the same server. As far as we can see, the node is the most "heavy" process on the server, application and DB use less resources. 

Can you provide some technical requirements for the node, or some advice on how to properly configure it?

Thanks in advance!

**Comment by alexeykiselev** [comment]
Hello,

The minimum required RAM is 2GB given to JVM. This is a default value on Linux. The node can use as many cores as available on your machine. 
The node's process can consume a lot of resources during initial node synchronisation or blockchain import.
