### ISSUE TITLE
How do I get the test coin?

### ISSUE THREAD

**Issue by flowerMyEyes** [wavesplatform/Waves#1304]
I created the test node, how do I get the test coin?

**Comment by monroid** [comment]
@flowerMyEyes you can create your own asset as described in Waves Client documentation https://docs.wavesplatform.com/en/waves-client/assets-management/issue-an-asset.html, or via RestAPI.

**Comment by petermz** [comment]
You can try the faucet: https://testnet.wavesexplorer.com/faucet
