### ISSUE TITLE
Proposal: 5 new /assets/ APIs

### ISSUE THREAD

**Issue by PyWaves** [wavesplatform/Waves#135]
Working on a number of Waves based projects, I realized that some basic and some more advanced useful functions are missing in the Waves API. In particular, I'd like to suggest the addition of 5 new assets related functions.

These 2 APIs are to get basic information about all issued assets or a specific one:

/assets/list/
Returns the list of all assetID's issued on the Waves blockchain

/assets/info/{assetId}
Returns issuer, name, description, quantity, decimals, reissuable flag, current supply (ie quantity - total burned amount)

The followings are 2 APIs that would be of immense value for trading, price analysis and financial modelling applications. They provide realtime or historical data feed prices for matched orders settled on the Waves blockchain:

/assets/price/{assetId1}/{assetId2}
Returns last price/volume (or the last matched order) for the pair

/assets/price/{assetId1}/{assetId2}/{timestamp_from}/{timestamp_to}/{granularity}
Returns historical tick prices (or OHLC prices) and volumes for the pair, resampled with the specified granularity [1m, 5m, 15m, 30m, ...]

The last one is to submit a signed transaction type 7 (ExchangeTransaction) directly to the Waves network, without posting an order to a Waves matcher. This would open the doors to a world of new opportunities (integration of custom/3rd party matching engines, pseudo-escrow services, OTC trading, ...):

/assets/broadcast/exchange/
Publish exchange of assets between 2 parties signed by a 3rd party

**Comment by Alezhka** [comment]
/assets/info/{assetId}
+ count holders.

/assets/holders/{assetId}[/{skip}/{limit}] or /assets/holders/{assetId}[&skip={skip}&limit={limit}]]
Returns list of asset holders and balance.

**Comment by vsuharnikov** [comment]
> /assets/price/{assetId1}/{assetId2}
> Returns last price/volume (or the last matched order) for the pair

http://matcher.wavesnodes.com/api-docs/index.html#!/matcher/marketStatus_1

> /assets/price/{assetId1}/{assetId2}/{timestamp_from}/{timestamp_to}/{granularity}
> Returns historical tick prices (or OHLC prices) and volumes for the pair, resampled with the specified granularity [1m, 5m, 15m, 30m, ...]

https://api.wavesplatform.com/v0/docs/#/candles/getCandles

> /assets/broadcast/exchange/
> Publish exchange of assets between 2 parties signed by a 3rd party

http://nodes.wavesnodes.com/api-docs/index.html#!/transactions/broadcast_1 already supports this.

**Comment by msmolyakov** [comment]
1. `/assets/list/`
Available via Data Service API: https://api.wavesplatform.com/v0/docs/#/assets/getAssetListByIds

2. `/assets/info/{assetId}`
Available via Node API: https://nodes.wavesnodes.com/api-docs/index.html#/assets/details_1

3. `/assets/price/{assetId1}/{assetId2}`
Available via Matcher API: https://matcher.waves.exchange/api-docs/index.html#!/matcher/marketStatus_1

4. `/assets/price/{assetId1}/{assetId2}/{timestamp_from}/{timestamp_to}/{granularity}`
Available via Data Service API: https://api.wavesplatform.com/v0/docs/#/candles/getCandles

5. `/assets/broadcast/exchange/`
Available via Node API: http://nodes.wavesnodes.com/api-docs/index.html#/transactions/signedBroadcast_1
