### ISSUE TITLE
Running a node - matcher orderbook returns empty results

### ISSUE THREAD

**Issue by koray1396** [wavesplatform/Waves#1354]
Hello,

I'm testing to running a node with matcher. Rest api seems to work fine, but market orderbook does not seem to get updated. Is this a normal behaviour? 

/matcher/orderbook/{amountAsset}/{priceAsset} returns empty results, /matcher returns an empty string. My config is below.

PS: If this is normal, then I would suggest a websocket implementation for market depth as an alternative to rest api, since querying orders for multiple pairs regularly is very slow and quite uneffective due to overhead.

Thanks,

```
# Matcher settings
  matcher {
    # Enable/disable matcher
    enable = yes

    # Matcher's account address
    account = ""

    # Matcher REST API bind address
    bind-address = "127.0.0.1"

    # Matcher REST API port
    port = 6886

    # Minimum allowed order fee
    min-order-fee = 300000

    # Fee of order match transaction
    order-match-tx-fee = 300000

    # Matcher's directories
    matcher-directory = ${waves.directory}"/matcher"
    data-directory = ${waves.matcher.matcher-directory}"/data"
    journal-directory = ${waves.matcher.matcher-directory}"/journal"
    snapshots-directory = ${waves.matcher.matcher-directory}"/snapshots"

    # Snapshots creation interval
    snapshots-interval = 1d

    # Invalid/Expired orders cleanup interval
    order-cleanup-interval = 5m

    # Maximum allowed amount of orders retrieved via REST
    rest-order-limit = 100

    # Base assets used as price assets
    price-assets = [

    ]

```

**Comment by 0xae** [comment]
Hello there, you need to config the  matcher account address:
checkout my config:

` 
    matcher {
          ....
           account = "3NN56Z7FwaPs5m6zxqFfBYZgKEb8hn8xso5"
          ....
     }
`

**Comment by alexeykiselev** [comment]
Actually, Matcher is a semi-centralised part of the Waves network. So, orders reside on an instance of the matcher. But settlement happens on the blockchain.

**Comment by username1565** [comment]
Hm... Is this possible to make the synchronization of the orders
between existing matchers in the Mainnet?
Is there any list of existing matchers?
I see here: http://dev.pywaves.org/nodes/ only a few nodes has enabled matcher.
So, I think, if matcher address or public-key will be published in some list,
new matcher can load orders from that [MATCHER REST API](https://matcher.wavesplatform.com), no?
