### ISSUE TITLE
State check failed. Reason: Attempt to transfer unavailable funds

### ISSUE THREAD

**Issue by Alteryy** [wavesplatform/Waves#1355]
State check failed. Reason: Attempt to transfer unavailable funds: Transaction application leads to negative asset '' balance to (at least) temporary negative state, current balance is 0, spends equals -10000000, result is -10000000"

:balance
curl http://127.0.0.1:6869/addresses/balance/3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc
{
  "address" : "3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc",
  "confirmations" : 0,
  "balance" : 41876000
}
request paras;
$result =  $this->_request( 'post', 'assets/transfer',
			array(
				//'version'   => $this->version,
				'assetId'   => $this->assetId,
				'sender'    =>'3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc',
				'recipient' =>$toAddress,
				'amount'    => $amount,
				//'feeAssetId'=> $this->feeAssetId,
				'fee'       => 100000,
				'attachment'=>'',
				//'timestamp' =>time()
			),
			true
		);

:assets/transfer,responses
Array
(
    [error] => 112
    [message] => State check failed. Reason: Attempt to transfer unavailable funds: Transaction application leads to negative asset '' balance to (at least) temporary negative state, current balance is 0, spends equals -10000000, result is -10000000
    [tx] => Array
        (
            [type] => 4
            [id] => 4E5ptrWQt6rq4VxZxdrai7osBNzaPB1xtDEpftRyG9Ni
            [sender] => 3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc
            [senderPublicKey] => senderPublicKeysenderPublicKey
            [fee] => 100000
            [timestamp] => 1532922250679
            [signature] => 4boLsrEDg6xVGpx8wGjfyGbNXmr485Wpd1rBkunxoFa5tbdzzHqJuJ7opLDNN3CD764ndf4R78sJRURc6cw74eBw
            [version] => 1
            [recipient] => 3PEWpWv5Z75b19M5oYSLTenCxB8tWC9X9hv
            [assetId] => 
            [feeAssetId] => 
            [feeAsset] => 
            [amount] => 10000000
            [attachment] => 
        )
)

There is a coin in my address, but I can't turn it out. Can anyone explain it to me?
Or can someone tell me about the transaction process, which API to call first, then which one to call, etc., including the transaction contract .

**Comment by alexeykiselev** [comment]
What version of Waves node do you use?

**Comment by Alteryy** [comment]
Hi，

 curl http://127.0.0.1:6869/node/version
{
  "version" : "Waves v0.13.4"
}

curl http://127.0.0.1:6869/addresses/balance/details/3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc
{
  "address" : "3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc",
  "regular" : 41876000,
  "generating" : 41876000,
  "available" : 41876000,
  "effective" : 41876000
}

**Comment by alexeykiselev** [comment]
May be you have provided incorrect senderPublicKey? In this case the address will be different and it's balance will be 0.

**Comment by Alteryy** [comment]
senderPublicKey is correct；
curl -H "Content-type: application/json" -H "X-API-KEY: **************!" -d '{ "assetId":"WAVES","sender":"3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc","recipient":"3P67m7d7VV1YvE3p7JRMXF6nzEPHCxq9ZHo","fee":100000,"amount":100000,"attachment":"25bsUKfFsFF4WR7PDzStyxixxUDv"}' -X POST localhost:6869/assets/transfer

{
  "error" : 112,
  "message" : "State check failed. Reason: Attempt to transfer unavailable funds: Transaction application leads to negative asset 'WAVES' balance to (at least) temporary negative state, current balance is 0, spends equals -100000, result is -100000",
  "tx" : {
    "type" : 4,
    "id" : "BrVALDHB17iaVFM9aJtySPG4BAgziB5VdZAq4NF95qZv",
    "sender" : "3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc",
    "senderPublicKey" : "FckK43s6tQ9BBW77hSKuyRnfnrKuf6B7sEuJzcgkSDVf",
    "fee" : 100000,
    "timestamp" : 1534470289604,
    "signature" : "2LvE1J8uMCCshCPdfWQjiWmWbKkFr5rZ4SyQssfwoGwgTL37xpQQ985cJegSuRrVG8apdgM6yd5Y2VWefbQmmGNp",
    "version" : 1,
    "recipient" : "3P67m7d7VV1YvE3p7JRMXF6nzEPHCxq9ZHo",
    "assetId" : "WAVES",
    "feeAssetId" : null,
    "feeAsset" : null,
    "amount" : 100000,
    "attachment" : "25bsUKfFsFF4WR7PDzStyxixxUDv"
  }
}

**Comment by Alteryy** [comment]
Why is the balance 0? The balance can be queried by browser

**Comment by alexeykiselev** [comment]
Because then you request the balance you do it by providing address, and it used to find the balance.
But then you do transfer the public key is used, the node recreates the address from the public key and checks the signature. So, it the public key is incorrect the incorrect address will be created and checked for the balance. By default any address has 0 balance.

**Comment by alexeykiselev** [comment]
Yes, the publicKey is correct, my bad.

**Comment by alexeykiselev** [comment]
This line in the reply is strange:
```
"assetId" : "WAVES",
```
While transferring Waves where should be `null` like with `feeAssedId`. Try to pass nothing while requesting.

**Comment by Alteryy** [comment]
The result is the same.

curl -H "Content-type: application/json" -H "X-API-KEY: *********!" -d '{ "assetId":"","sender":"3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc","recipient":"3P67m7d7VV1YvE3p7JRMXF6nzEPHCxq9ZHo","fee":100000,"amount":100000,"attachment":"25bsUKfFsFF4WR7PDzStyxixxUDv"}' -X POST localhost:6869/assets/transfer
{
  "error" : 112,
  "message" : "State check failed. Reason: Attempt to transfer unavailable funds: Transaction application leads to negative asset '' balance to (at least) temporary negative state, current balance is 0, spends equals -100000, result is -100000",
  "tx" : {
    "type" : 4,
    "id" : "4xCNJfbmBmpdt6RG6M2etQB3GaLumyUauQch9epTdbvT",
    "sender" : "3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc",
    "senderPublicKey" : "FckK43s6tQ9BBW77hSKuyRnfnrKuf6B7sEuJzcgkSDVf",
    "fee" : 100000,
    "timestamp" : 1534499529605,
    "signature" : "eoug3mhK1S95y3dm3qLWmaeb26N4F95YTSmfHVzFb9hyubWeFa1uGctuG4YAc1xcB8BceirMkACJgepWp5ZVUxb",
    "version" : 1,
    "recipient" : "3P67m7d7VV1YvE3p7JRMXF6nzEPHCxq9ZHo",
    "assetId" : "",
    "feeAssetId" : null,
    "feeAsset" : null,
    "amount" : 100000,
    "attachment" : "25bsUKfFsFF4WR7PDzStyxixxUDv"
  }
}

3PETfqHg9HyL92nfiujN5fBW6Ac1TYiVAAc'
This address was generated by my key. Then I transferred a wave from the exchange to this address. I want to transfer the wave of this address to another address in the exchange or wallet.

**Comment by Alteryy** [comment]
It seems to be ok, if the contract is needed for assetId, right?

**Comment by alexeykiselev** [comment]
If you want to transfer an asset, you have to put here the asset's ID. 
As I can see, the transaction finally came through. I close the ticket.
