### ISSUE TITLE
I still don't understand how to get some waves at testnet ?

### ISSUE THREAD

**Issue by flowerMyEyes** [wavesplatform/Waves#1362]
I used windows Java -jar waves.jar waves-testnet.conf  to create nodes，i need some waves for testing, but I can't find a way to get waves.
I mentioned this before, [How do I get the test coin?](https://github.com/wavesplatform/Waves/issues/1304), @monroid  answered me, but I don't understand.
I think I need more help. 
Thanks!

**Comment by Nazeim** [comment]
@flowerMyEyes 
Have you tried this way to get waves for testing?
https://testnet.wavesexplorer.com/faucet

**Comment by flowerMyEyes** [comment]
@Nazeim
I tried it before, but I didn't succeed. I just tried it again. It was successful.
I think it might be that some of my operations were wrong.
Thanks for your help!

**Comment by vsuharnikov** [comment]
@Nazeim Could you add instructions to https://docs.wavesplatform.com how to get waves on testnet?

**Comment by WavBEC** [comment]
i am currently facing the same issues, i am un able to get waves testnet, any help?
