### ISSUE TITLE
Cannot sync block. Invalid child block.

### ISSUE THREAD

**Issue by RayHughes** [wavesplatform/Waves#1370]
My waves node stopped syncing this morning and I am getting the follower error. I have no idea how to resolve. 

`2018-08-04 14:41:16,278 DEBUG [appender-49] c.w.s.a.BlockAppender$ - [79e55e38 185.22.174.107:50712] Could not append Block(63tPypXzRV5Hitb2aQs5W1tKMXb9eCokgskW5tBE7WxrUKuMzemfHRfyPa1xnFPBbzeJdtANW1sDrPsvMh69BsyY -> 4VCSQ6V..., txs=0, features=Set()): BlockAppendError(Block is not a child of the last block,Block(63tPypXzRV5Hitb2aQs5W1tKMXb9eCokgskW5tBE7WxrUKuMzemfHRfyPa1xnFPBbzeJdtANW1sDrPsvMh69BsyY -> 4VCSQ6V..., txs=0, features=Set()))`

**Comment by alexeykiselev** [comment]
Please, check the version of your node. Because your node trying to sync with old nodes. The version of the node on 185.22.174.107 is 0.10.2. 
The simplest solution is update the node to the latest release version and download the blockchain from scratch.
