### ISSUE TITLE
How do I generate a signature?

### ISSUE THREAD

**Issue by lucianoreis** [wavesplatform/Waves#1371]
How do I generate a signature to make a coin transfer through the full node API?

**Comment by alexeykiselev** [comment]
Basically, you have to hash the transaction bytes and sing the digest with your private key afterwards. There are libraries to simplify the task. 
[WavesJ](https://github.com/wavesplatform/WavesJ), [WavesCS](https://github.com/wavesplatform/WavesCS) and, of course, [PyWaves](https://github.com/PyWaves/PyWaves) to name the few.
