### ISSUE TITLE
Not enough tradable balance (negative value)

### ISSUE THREAD

**Issue by devoldemar** [wavesplatform/Waves#1386]
Hello, trade through matcher node. I have about $650 (65000 normalized), and when i try to create order your node reponses with (balance wrong, negative amount):
"Not enough tradable balance: Map(Some(Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck) -> **-1135517**, None..."

**Comment by DrBlast** [comment]
It should be ok now. Please check

**Comment by devoldemar** [comment]
Yes, thanks, now it's working
