### ISSUE TITLE
Transaction not allowed by account-script in testnet faucet

### ISSUE THREAD

**Issue by agonzalezv** [wavesplatform/Waves#1388]
When I try to use the [testnet faucet](https://testnet.wavesexplorer.com/faucet) I get a `Transaction not allowed by account-script` message as a response. I'm using a mac with Brave as my default browser. I have tried also with firefox, chrome and safari with no avail. By doing a quick inspection to the request, the issue seem to be an error when calling `https://testnode1.wavesnodes.com/faucet/payment`. 

Please advise.

**Comment by alexeykiselev** [comment]
During testing on Testnet accounts of few nodes were scripted. That made using of faucet on them impossible. Faucet was moved to other node with unscripted account and work again.
