### ISSUE TITLE
enhance /transactions/address/{address}/limit/{limit} by assetId filter

### ISSUE THREAD

**Issue by AK666** [wavesplatform/Waves#1429]
Max limit is 10k transactions for /transactions/address/{address}/limit/{limit} ,
BUT the result most part is filled by 'spam' assets

Filter by assetId can be helped.
 for instance:
/transactions/address/{address}/limit/{limit}/asset/{assetId}
or
/transactions/address/{address}/asset/{assetId}/limit/{limit}

**Comment by Karasiq** [comment]
Implemented in the gRPC API
