### ISSUE TITLE
Rename asset and/or change its description

### ISSUE THREAD

**Issue by devoldemar** [wavesplatform/Waves#1470]
Hello, it would be excellent if i could rename asset or at least change its description. The concept of business may alter, misprints done in the past, and so on.
Nevertheless, trading ticker can still be the same. Thanks for consideration.

**Comment by monroid** [comment]
Hi @devoldemar,
just to avoid misunderstanding we don't provide the ability to change asset name and/or description after issue, the only one thing can be changed is amount of asset https://docs.wavesplatform.com/en/platform-features/assets-custom-tokens.html
