### ISSUE TITLE
Off-line multi sign

### ISSUE THREAD

**Issue by xianaofei** [wavesplatform/Waves#1503]
How to support offline storage and multi signature.
Please provide reference support.

**Comment by monroid** [comment]
Hi @xianaofei,
what do you explain that do you mean under offline storage definition? 
Multisignature we supports in our smart contracts, here you can find the example of multisig https://docs.wavesplatform.com/en/technical-details/ride-language/language-description.html

**Comment by vsuharnikov** [comment]
@xianaofei You could:
1. Run the node: https://docs.wavesplatform.com/en/waves-full-node/how-to-install-a-node/how-to-install-a-node.html
2. The delete `peers.dat` in `waves` directory and add:
  ```
  waves.network { 
    bind-address = "127.0.0.1"
    known-peers = []
  }
  ```
  at the end of your config.

This should make your node effectively offline :)
