### ISSUE TITLE
Help me check my transfer api

### ISSUE THREAD

**Issue by nmjay** [wavesplatform/Waves#1518]
$data = array(
'assetId' => 'asset id here',
'feeAssetId' => 'asset id here',
'sender' => 'address',
'recipient' => 'addres',
'amount' => 1000000000,
'fee' => 100000,
'attachment' => '',
'timestamp' => time() * 1000
);

$curl = new Curl();
$curl->setHeader('Content-Type', 'application/json');
$curl->setHeader('api_key', 'WavesKey');
$curl->setHeader('X-Api-Key', 'WavesKey');
$curl->post('xxx.xx.xxx.xx:6869/assets/transfer', $data);
Show Error 404 => Error: 400: HTTP/1.1 400 Bad Request

I use the lasted version of node.

**Comment by monroid** [comment]
Hi @nmjay, 
what lib did you use, could you compare your json format with our docs https://docs.wavesplatform.com/en/development-and-api/waves-node-rest-api/transactions.html. May be you've missed some field.

**Comment by vsuharnikov** [comment]
1. Private API for transferring assets:
  * Some documentation: https://docs.wavesplatform.com/en/development-and-api/waves-node-rest-api/asset-transactions/private-functions.html#post-assetstransfer
  * Swagger https://nodes.wavesnodes.com/api-docs/index.html#!/assets/transfer - just replace `https://nodes.wavesnodes.com` with `http://your_domain` or `https://your_domain` depending on your situation
2. About `$data`:
  * `feeAssetId` => …` - `feeAssetId` is optional and works only if `feeAssetId` is [sponsored](https://docs.wavesplatform.com/en/proposals/sponsored-transactions.html) asset;
  * `attachment` - you can leave this field if doesn't send the payload;
  * `'timestamp' => time() * 1000` - right, the Node requires timestamp in milliseconds.
3. `$curl->post('xxx.xx.xxx.xx:6869/assets/transfer', $data)`:
  * Doesn't sure, this will work. If not, try to specify the protocol: `$curl->post('http://`
  * Does this PHP library serializes `$data` to JSON? If not, try `json_encode($data)`
