### ISSUE TITLE
[bug] generating balance incorrect with v2 leases

### ISSUE THREAD

**Issue by w0utje** [wavesplatform/Waves#1560]
it's possible to get a negative generating balance with v2 leases because these leases are ignored by effectivebalance/ [ (1000) confirmations ].

this is introduced by the client for using v2 lease transactions.

Also v1 leases will result in a lower genenating balance, even if you cancel them right after (because of the 1000 blocks timeout). cancelling a v2 lease will update the generating balance immediately, confirming that v2 leases are ignored by effectivebalance with x confirms

**Comment by Karasiq** [comment]
Fixed
