### ISSUE TITLE
Unable to run private network on windows

### ISSUE THREAD

**Issue by CryptoChainDeveloper** [wavesplatform/Waves#1572]
I'm trying to run a private waves network on win10. after following some of waves docs instructions(sbt "test:runMain tools.GenesisBlockGenerator src/test/resources/genesis.example.conf") These errors comes up. what's the matter?

 
![screenshot](https://user-images.githubusercontent.com/43516562/46903956-d3263b00-cee9-11e8-825d-ecc3450b4b6d.png)

**Comment by equisde** [comment]
hello i was trying to make a private chain and i got this output while doing the fourth step
...
[info] Done compiling.
[info] Packaging /root/blockcap/lang/jvm/target/lang-1.0.0.jar ...
[info] Done packaging.
[info] Formatting 328 Scala sources in node:compile ...
[info] Reformatted 1 Scala source in node:compile
[info] Compiling 329 Scala sources to /root/blockcap/target/classes ...
/usr/share/sbt/bin/sbt-launch-lib.bash: line 59: 54601 Killed                  "$@"

and no any other output is generated what should i do ?

**Comment by equisde** [comment]
have you installed jdk for compiling?

**Comment by vsuharnikov** [comment]
@CryptoChainDeveloper Hi! Please check, the user have *write* rights to the directory with Node
