### ISSUE TITLE
API, where i can take current bid's and ask's

### ISSUE THREAD

**Issue by Nekspsy** [wavesplatform/Waves#1580]
Hello, do you have api page like this: https://marketdata.wavesplatform.com/api/ticker/WAVES/USD
but where i can take current bid's and ask's for someone token?

**Comment by vsuharnikov** [comment]
Hi! 

This feature is implemented in a next release's branch. But we think about back-porting it to the current version, this isn't the first request from our users :)

There are fields:
* lastPrice
* lastSide - buy or sell
* bid - best price
* bidAmount
* ask - best price
* askAmount

Is this enough? :)

**Comment by Nekspsy** [comment]
Подскажите, пожалуйста, по какому апи я могу получить цену в usd определенного токена?
И как вообще высчитывается цена определенного токена в USD, которая указана на платформе в разделе "портфель"?

**Comment by vsuharnikov** [comment]
Разработчики клиента ( https://github.com/wavesplatform/WavesGUI ) говорят, что используют среднее арифметическое по 5 последним торгам. Если прямых торгов нет - считают через WAVES и:
> берем среднее по 5 торгам WAVES к 1 ассету, потом к другому и делим или умножаем в зависимости от порядка пары
