### ISSUE TITLE
Could not load library. Reasons: no leveldbjni64-1.8

### ISSUE THREAD

**Issue by sillyghost** [wavesplatform/Waves#1727]
`java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni64-1.8 in java.library.path, no leveldbjni-1.8 in java.library.path, no leveldbjni in java.library.path, /tmp/libleveldbjni-64-1-7621302830990575898.8: /tmp/libleveldbjni-64-1-7621302830990575898.8: failed to map segment from shared object: Operation not permitted]`

During installation on CentOS 7 , found that it was earlier issue which was solved , but occurred again !

**Comment by vsuharnikov** [comment]
Please use packages from https://github.com/wavesplatform/Waves/releases . 
If you do it yourself, please run `sbt clean` before compiling and package's creation.
