### ISSUE TITLE
Error Mining Block on private chain 

### ISSUE THREAD

**Issue by greemo** [wavesplatform/Waves#1751]
Hi All,

I am receiving the following error when I run commit 71a539e3051ffde980d183a423e5a270a36b92ec of the waves node as a private chain.

`Error mining Block: GenericError(Block Block(2RWRA7Z6uXz7io1FNFGzDCeGvLVsvxoBxwuwf5ggU1KsMBfjarF6gJx5VanZ1YUVmmtgA8jtdgnXNWqb4qvW5eDB -> 3Qv6mTq..., txs=0, features=Set()) is invalid: Block time 1544645554716 less than expected)`

The block mining seems to fail depending on how many waves I send.
A transfer of 7466.1 Waves or less is consistently successful, but a transfer of 7466.2 waves or more is consistently unsuccessful. I got pretty bored with my binary search at that point.

When I get the block mining error in the log (Which is a warning level), no more mining is ever performed. I need to restart the server to restart mining.

This looks somewhat related to #1643, but I have the base target at 100, and blocks are successfully mined with low transfer amounts.

My config here: [waves.conf.txt](https://github.com/wavesplatform/Waves/files/2679722/waves.conf.txt)

**Comment by greemo** [comment]
This is a log file from the system when I started the node, sent a transaction for 7466.1 waves which succeeded, then a transaction for 7466.2 which failed.
[waves_short.log](https://github.com/wavesplatform/Waves/files/2681545/waves_short.log)

**Comment by Karasiq** [comment]
Balance change affects the generating balance, therefore PoS mining delay increases.
