### ISSUE TITLE
questions about custom type

### ISSUE THREAD

**Issue by zychappy** [wavesplatform/Waves#1776]
1. does 'type=CUSTOM' means a private chain?
2.  an address generated by crypto.GenerateKeyPair of gowaves 

**NjgM1o7mdYJ5D9KmChLTmM3naF5WKF1qL2V9jruBLjU**
is VERY different such as
**3FR3MyuXumwBj1bLC8xnW38iHtwm9Ugdm8K** 

right or wrong? if wrong ,how to do with golang?
3. does recipient’s address of transactions means init balance of myself?
4.how to get signature?

merry christmas :)

**Comment by danielrangelsa** [comment]
About 'type=CUSTOM' is true.. 
When generating the Genesis block, you define the addresses that will have the waves that will be generated.

**Comment by danielrangelsa** [comment]
What were the steps you followed to generate a genesis?

**Comment by danielrangelsa** [comment]
Follow this tutorial: https://docs.wavesplatform.com/en/technical-details/creating-a-private-waves-blockchain-network.html
