### ISSUE TITLE
How to determine whether a transaction is confirmed by the network？

### ISSUE THREAD

**Issue by FunCodeH** [wavesplatform/Waves#1782]
I send a transaction use this method "node.transfer", but how to know whether this transaction is confirmed by the network？

**Comment by vsuharnikov** [comment]
Hi! 

You can use method, `node. getTransaction` in WavesJ. Or, for better guarantees:
1. Check the transaction's height (actually block's height that contains this transaction) by `node.getTransactionData` ([json](https://docs.wavesplatform.com/en/development-and-api/waves-node-rest-api/transactions.html#section-04c1c63f6a357c3a659366a5cc89737f))
2. Wait until `{transaction's height} > {blockchain's height} + N`, where blockchain's height is obtained by `node.getHeight` and N is some number - the biggest number, the more guarantees, that the transaction stays in the blockchain (e.g. 5).

E.g. in terminal:
```
$ curl 'https://nodes.wavesnodes.com/transactions/info/BSUdvVSVpFf3gV4mkwFmG2c34iCv2tQCcRuT8K2y9vXi'
{
  "type": 4,
  "id": "BSUdvVSVpFf3gV4mkwFmG2c34iCv2tQCcRuT8K2y9vXi",
  "sender": "3PBXABHS1HddeGNqniNW39BuPbAFJXt4TC5",
  "senderPublicKey": "A9HmnaCnCopE3Etmu7ijsaUeLFhhkzw86dkNxv9DDzjW",
  "fee": 100000,
  "timestamp": 1547019219913,
  "proofs": [
    "rdsv95HMmx3XcgfmvPYtTBmqQqPS2Bd3wE15mkARcQp8hNqmsDCVJ98yT9jz6MGgXopt9ToDBtVkhQB2Pa9tAYe"
  ],
  "version": 2,
  "recipient": "3PBbLhML82KwDNtQou74JeYYhrxhSYF4ggH",
  "assetId": "5KBZ6G4kbJZpEY3VFG1iW29z5aD6CTvMHU1ucq3gDtNy",
  "feeAssetId": null,
  "feeAsset": null,
  "amount": 1000000000000,
  "attachment": "",
  "height": 1343293
}

$ curl 'https://nodes.wavesnodes.com/blocks/height'
{
  "height" : 1343307
}
```

`1343307 - 1343293 = 14`
