### ISSUE TITLE
GET /transactions/address/ pagination param "after"

### ISSUE THREAD

**Issue by roccomuso** [wavesplatform/Waves#1794]
There's still no way to fetch tx list with pagination? (Ref. https://github.com/wavesplatform/Waves/issues/1000)
I saw on the swagger doc (https://nodes.wavesplatform.com/api-docs/index.html) an `after` param, is it working? Are tx listed timestamp DESC?

**Comment by phearnot** [comment]
This will be fixed in #1971

**Comment by Karasiq** [comment]
Fixed in https://github.com/wavesplatform/Waves/pull/1971
