### ISSUE TITLE
GET /addresses/balance/<address> shows 0 confirmations

### ISSUE THREAD

**Issue by roccomuso** [wavesplatform/Waves#1795]
why the `/addresses/balance/<address>` endpoint returns always `confirmations: 0` also for addresses with old and confirmed balance? that confirmations field is kinda misleading at this point.

**Comment by theahmadzadeh** [comment]
Got the same issue,
Unfortunately waves community is so weak!!!

**Comment by petermz** [comment]
That's ok. This number just reflects what's in your query, e.g.:
```
$ curl https://testnode1.wavesnodes.com/addresses/balance/3NAxZiHVsJ8bUZvR5K5UEHXFoBe4YSwxMzh
{
  "address" : "3NAxZiHVsJ8bUZvR5K5UEHXFoBe4YSwxMzh",
  "confirmations" : 0,
  "balance" : 699870001
}

$ curl https://testnode1.wavesnodes.com/addresses/balance/3NAxZiHVsJ8bUZvR5K5UEHXFoBe4YSwxMzh/42
{
  "address" : "3NAxZiHVsJ8bUZvR5K5UEHXFoBe4YSwxMzh",
  "confirmations" : 42,
  "balance" : 699870001
}
```
Zero just happens to be the default
