### ISSUE TITLE
No way to find asset balance on the node by API

### ISSUE THREAD

**Issue by vladyslavstartsev** [wavesplatform/Waves#1837]
The API should have method to find asset balance by assetId. 
Why?
Currently I can do in 2 ways (let's assume that I have 1 million of addresses and each of them contain some amount of WAVES and , for example, 3 assets)
- get 1 mln of addresses and call the node 1 mln times to get by balance by asset and then add all the balances. So to know my balance I need to call node for 4 mln times ( 1 mln for WAVES and 3 mln for assets)
- I can get whole distribution of an asset (GET /assets/{assetId}/distribution/{height}/limit/{limit}), and check if the address given in the response is mine. But that's also not the best way to do it.

**Comment by KardanovIR** [comment]
You'd like to get the total amount (result after all issue, reissue and burn transactions) for one particular asset, right?

**Comment by vladyslavstartsev** [comment]
@KardanovIR yes.

**Comment by phearnot** [comment]
Please use `/assets/details/{assetId}` for this. The `quantity` field contains total asset amount (after all issue/reissue/burn transactions).
