### ISSUE TITLE
Update the config wiki to be clearer

### ISSUE THREAD

**Issue by Arkhh** [wavesplatform/Waves#19]
Hi,

The config wiki is not very clear about the "api_key" part. I figured it out but it took me a bit of time. 
Here is my suggested changes :

Replace : 
Decide what api_key you require and call /utils/hash/secure using http method to calculate apiKeyHash.
By : 
Create your API key, think of it as a password that you have to input in order to access each POST request on your node. Call /utils/hash/secure and write the API key you chose in the field then press " Try it out". The response will contain a field called : apiKeyHash, copy this value and paste it in your waves-config.json as the value for the apiKeyHash attribute.

After : 
"Call /scorex/stop using http post method to stop node.

Put your walletSeed and apiKeyHash values into waves-testnet.json. "

Add : 
Prior to using the swagger UI, type your plain text API key that you created a few steps above in the field provided on the top right of the swagger UI as showed in the following screenshot.
![image](https://cloud.githubusercontent.com/assets/6398133/17745167/ce9cf02a-6478-11e6-8179-b5c29a583615.png)

Let me know if you have any objections !

**Comment by gagarin55** [comment]
fixed, https://github.com/wavesplatform/Waves/wiki/How-to-configure-Waves-node
