### ISSUE TITLE
How Confirmations work in private waves?

### ISSUE THREAD

**Issue by theahmadzadeh** [wavesplatform/Waves#1911]
I am running my own private blockchain with waves node source but despite there are two nodes the problem is no address balance gets any confirmation(always zero);

Further more i wanted to know does block mining stops when there are no txs in a period?!
st happens to me.

**Comment by theahmadzadeh** [comment]
Is There possible for nodes to not be synced exactly?!
My first node is on height 21432 While the second one is on 21435!

**Comment by theahmadzadeh** [comment]
It suddenly started over this morning!!
Current height: 7543
How is this possible?? The transactions are gone for good!!

**Comment by Karasiq** [comment]
See https://github.com/wavesplatform/Waves/issues/1795
