### ISSUE TITLE
deploy mainnet from block archive not sync

### ISSUE THREAD

**Issue by sicute** [wavesplatform/Waves#1941]
hi all, 
i try follow https://docs.wavesplatform.com/en/waves-full-node/options-for-getting-actual-blockchain.html 
and the data block success extract in folder data/ 
But why until now block can't sync to main net still at curl -X GET --header 'Accept: application/json' 'http://localhost:6869/blocks/height' -H 'api_key:ridethewaves!'
{
  "height" : 1408805
can't update to mainet , do i need reindex such as bitcoin fork .
Thanks

**Comment by Karasiq** [comment]
Try to use an import file.
