### ISSUE TITLE
Is it possible to make Sponsered Orders in waves?

### ISSUE THREAD

**Issue by theahmadzadeh** [wavesplatform/Waves#1983]
I want to make order on waves dex paying the order fee with my own asset just the same way it is possible in transfer transactions; but I didn't find anything on pywaves or waves docs.

**Comment by theahmadzadeh** [comment]
Guys What the hell?! I've never seen such a weak community! it's pretty strange with a platform ranked 21 in CMC :\

**Comment by Siersciuch** [comment]
yes

**Comment by vsuharnikov** [comment]
Currently not, fee in Orders always specified in Waves.
