### ISSUE TITLE
unsafe init and config

### ISSUE THREAD

**Issue by marilyn4325** [wavesplatform/Waves#20]
If the testnet is the same as the production later, you should change the setup process as described at https://github.com/wavesplatform/Waves/wiki/How-to-configure-Waves-node , because the server is open to public internet access by default and before generating the API hash, so the wallet seed can be queried without an API key and other funny things can be done, like stopping the server. And you should mention, that the wallet dir and data dir in waves-testnet.json is configured in /tmp. On some Linux system the /tmp directory is deleted on reboot (or even a RAM disk), which would result in some interesting support requests, if people loses their wallets or have to re-sync the whole blockchain every time they reboot their system.

**Comment by marilyn4325** [comment]
BTW, not a theoretical problem, just try xxx:6869/wallet/seed for some addresses at http://testnet.wavesexplorer.com/peers , there are public nodes with an empty API key.

**Comment by Arkhh** [comment]
+1, I agree 100% with this flaw, there should be such an api call open to the public at ANY time for the production code. Can someone confirm it has been handled ?

**Comment by marilyn4325** [comment]
Additional note: /addresses can be used without an API key, even when the API key is set. I don't know if this is a security problem, but might be better that no RPC commands are allowed without providing an API key.

Solution for the original problem: use 127.0.0.1 as the default RPC bind address instead of 0.0.0.0, then only local access is possible. And don't start the server with an empty API key. Maybe could be queried and set like the seed at first start, when empty, or a command line tool could be provided for hashing a string.

**Comment by marilyn4325** [comment]
Idea to fix the /tmp problem, which already some people experienced in testnet-maintainers: use empty string as default in the config file. If the string is empty, it will use the user's home directory (System.getProperty("user.home") should do it).

**Comment by marilyn4325** [comment]
both issues, RPC bind address and /tmp directory, are fixed in the latest release
