### ISSUE TITLE
Disable/Enable an Api

### ISSUE THREAD

**Issue by a-bahmani** [wavesplatform/Waves#2087]
Please add an option to disable/enable some Api. So that I allow/disallow an Api and selected Api can be enabled and others be disabled. 
For security reasons, I need to allow selected Api and others must be disabled. Did you have an option to do that?

**Comment by KardanovIR** [comment]
Hello!
Am I right that you need to enable or disable some endpoints of the API? 
If so, you can use nginx as reverse proxy and enable/disable endpoints on the nginx level.
