### ISSUE TITLE
Java installation instruction on Ubuntu doesn't work

### ISSUE THREAD

**Issue by marilyn4325** [wavesplatform/Waves#21]
The instructions for installing Java on a fresh Ubuntu system as described at https://github.com/wavesplatform/Waves doesn't work. First accepted answer here works: http://askubuntu.com/questions/521145/how-to-install-oracle-java-on-ubuntu-14-04

**Comment by Arkhh** [comment]
What error are you getting ? just did it sucesfully today.

**Comment by marilyn4325** [comment]
The problem was that I was running as a normal user and prefixed everything with "sudo". But somehow this didn't work with the "tee" command. I tested it again on a fresh Ubuntu system and when running as root, it works. Nevertheless, might be better to use "apt-add-repository" instead of the "tee" hack.
