### ISSUE TITLE
global namespace and @Verifier(tx)

### ISSUE THREAD

**Issue by j0k** [wavesplatform/Waves#2173]
when variable declared in global scope IDE said no errors when it's used inside @Verifier

here is an [exampe](https://github.com/j0k/waves_understanding/blob/master/smartcontracts/smartBadNamespace.scala) with `accCreator` variable

**Comment by msmolyakov** [comment]
Hi!

@Verifier function has same access to global scope that @Callable and user functions.

The fact that in this case there are no errors is the correct behavior.
