### ISSUE TITLE
v0.6.3: Provided API key is not correct

### ISSUE THREAD

**Issue by vlad-bondarenko** [wavesplatform/Waves#219]
Returned message "Provided API key is not correct" for calls REST API;
GET /debug/settings

**Comment by alexeykiselev** [comment]
Hello!
Have you provided an API key itself during API calls?
Please, refer to this section of configuration manual https://github.com/wavesplatform/Waves/wiki/Waves-Node-configuration-file#rest-api-settings

**Comment by JackPickering** [comment]
Where do you find your API key?

**Comment by Aidin** [comment]
how can we get an API key?

**Comment by alexeykiselev** [comment]
Please read about setting `api-key` at [https://github.com/wavesplatform/Waves/wiki/Waves-Node-Configuration-File#rest-api-settings](https://github.com/wavesplatform/Waves/wiki/Waves-Node-Configuration-File#rest-api-settings)

**Comment by Solido** [comment]
Having generate an API_KEY using rest method and then copy/paste under conf I still get Provided API key is not correct.

Should I provide API_KEY or api_key, using form-data or x-www-form-urlencoded ? 
documentation is contradictory on this and API error can be more detailed to help beginners like me.
Thx !

**Comment by Undenya** [comment]
Same problem

**Comment by iqoptionizator** [comment]
i also dont understand, where i can find an Api Key to use Public Nodes, like a https://nodes.wavesexplorer.com

**Comment by DrBlast** [comment]
@iqoptionizator node api-key is not a public info. You can set up your own api-key for your own node.
