### ISSUE TITLE
sbt installation step incomplete

### ISSUE THREAD

**Issue by marilyn4325** [wavesplatform/Waves#22]
The installation doc at https://github.com/wavesplatform/Waves needs the additional step ```sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 99E82A75642AC823```, and I don't know if your ```tee -a``` magic is a good idea, maybe can be re-written with ```apt-add-repository```.

**Comment by gagarin55** [comment]
May be this one is better http://www.scala-sbt.org/download.html ?

**Comment by marilyn4325** [comment]
Yes, http://www.scala-sbt.org/download.html would be perfect. It has the additional step, and information for manual installation for other systems than Debian and Ubuntu.
