### ISSUE TITLE
no private key for sender address in wallet

### ISSUE THREAD

**Issue by EminBudak** [wavesplatform/Waves#2285]
I run wawes node over 6 months but it starts to give an error when signing transaction "no private key for sender address in wallet" I didn't change anything in the config file. How can I fix this problem I have tokens in my wallet?

**Comment by username1565** [comment]
Hello!

You can rename `wallet.dat` (do not delete this!), and if you specified your base58 encoded seed and password in old node.conf, then this file `wallet.dat`, will be created again, after next running of the node. Maybe this file is corrupted.

Also, if you have base58 encoded seed, in your `node.conf`, you can [decode this seed from that base58 to mnemonic text](https://brainwalletx.github.io/#converter),
and after get your mnemonic seed (words),
you can access to your funds, WAVES, and tokens - using [waves client](https://client.wavesplatform.com/#!/dex-demo), or [waves-lite-client](https://waveswallet.io/).

Best regards.
