### ISSUE TITLE
HTTPS + strong passwords

### ISSUE THREAD

**Issue by clipto** [wavesplatform/Waves#23]
- Will the Swagger websites of the nodes be made more secure by making it https instead of http?
  As password now go in clear text. 
- Will strong passwords be fixed? As we now can set normal characters only, and no special characters. (So no @#€&$~= etc. )

Thanks,

Clipto
wavesnode.net

**Comment by bcdev-** [comment]
I don't think that support for HTTPS in the Node is necessary. If someone really needs to expose his API to the internet with HTTPS, he can just proxy it through Nginx.
