### ISSUE TITLE
how to connect wave node with Testnet for access RPC api of Testnet ??

### ISSUE THREAD

**Issue by rajajwaliya** [wavesplatform/Waves#2303]
i have created node in wave than i m trying to access rpc api via postman. i m also send some wave tokens to my address via testnet faucet. but the problem was every time when i try to get balance via rpc api it gives me 0 balance. but in testnet my testnet address have balance. i have node version of 0.17.2
![postman](https://user-images.githubusercontent.com/44025196/58534398-d962f080-8208-11e9-8c04-47130ce00390.png)

**Comment by KardanovIR** [comment]
@rajajwaliya are you sure that your node is on actual height? 
You can check it using API, for example, URI for public testnet nodes is 
https://testnodes.wavesnodes.com/blocks/height

**Comment by rajajwaliya** [comment]
@KardanovIR node is not on that height. my another question was is there any way to access rest api publicly with out creating full-node. i also need the api-key. @KardanovIR  you have any idea ??

**Comment by KardanovIR** [comment]
There are public testnet nodes here: https://testnodes.wavesnodes.com/api-docs/index.html

Why do you need an API Key?

**Comment by rajajwaliya** [comment]
@KardanovIR i need api-key for creating address and transfer wave assets. can we perform this two without api-key ??

**Comment by widyhafiz03** [comment]
any way to access rest api publicly with out creating full-node. i also need the api-key. added the question label 23 days ago.

**Comment by msmolyakov** [comment]
Api-key is private for the node owner. So several endpoints are available only for the node owner. If you want full access then you should run your own node.

But for creating address or transfers you don't need any api-key.

Also (about problem in the top of the issue) make sure that your local node is connected to the testnet and is already fully synchronized (has the same height as official nodes).

**Comment by rajajwaliya** [comment]
than how can i creating address or transfers waves by using your node without api-key. please help.
    On Wednesday, 24 July, 2019, 06:34:24 pm IST, Maxim Smolyakov <notifications@github.com> wrote:  
 
 
Api-key is private for the node owner. So several endpoints are available only for the node owner. If you want full access then you should run your own node.

But for creating address or transfers you don't need any api-key.

Also (about problem in the top of the issue) make sure that your local node is connected to the testnet and is already fully synchronized (has the same height as official nodes).

**Comment by msmolyakov** [comment]
Please read the official documentation. It explains this and more https://docs.wavesplatform.com/en/
