### ISSUE TITLE
Critical : Node not syncing

### ISSUE THREAD

**Issue by Arkhh** [wavesplatform/Waves#24]
Hi,

My node is not syncing for more than 12 hours, I tried to restart it, delete and regenerate wallet.dat and a seed and nothing works. My node is stuck at the height 100777

On the swagger UI I did the GET /debug/state && GET /debug/info and here are the logs : 

java.lang.IllegalArgumentException: requirement failed: accountChanges(3MpErnxpibaoH7uoMAH7cbSekaRX2iFVfVm).get(100776) is null. lastStates.get(address)=100776
    at scala.Predef$.require(Predef.scala:224)
    at scorex.transaction.state.database.blockchain.StoredState.loop$1(StoredState.scala:126)
    at scorex.transaction.state.database.blockchain.StoredState.scorex$transaction$state$database$blockchain$StoredState$$balanceByAddress(StoredState.scala:131)

The trace is much longer and I can provide it in full if requested.

Thanks

**Comment by asolovyov** [comment]
Hi,

couple of questions:
 - what is version of the node?
 - what is UTC time on the machine running the waves node? You can check results of "date -u" with http://time.is/UTC

Thanks

**Comment by Arkhh** [comment]
Hi, 

Thank you for your answer.

The version is 0.2.2 and the UTC time the machine is running is : Tue Aug 23 14:35:50 UTC 2016, at the time of this comment.

**Comment by Arkhh** [comment]
resolved with issue #30
