### ISSUE TITLE
incorrect release tag conception

### ISSUE THREAD

**Issue by mtuktarov** [wavesplatform/Waves#2414]
I am using the following command to get the latest Waves node latest version:
```
mtuktarov-mbp:~ mtuktarov$ version=$(curl --silent https://api.github.com/repos/wavesplatform/Waves/releases/latest | grep '\"tag_name\":' | sed -E 's/.*\"([^"]+)\".*/\1/') && echo $version

v1.0.0
```
I then want to download artifacts using $version variable:

```
mtuktarov-mbp:~ mtuktarov$ curl -L -o ~/Desktop/waves_${version}_all.deb https://github.com/wavesplatform/Waves/releases/latest/download/waves_${version}_all.deb
```
However, since release tag contains letter **v** it doesn't work.
Yes, I can change **sed** command. However, I strongly believe that specifying **v** in the field that is actually a version field - this is excess

**Comment by phearnot** [comment]
We just strictly follow SemVer's [tagging specification](https://semver.org/spec/v1.0.0.html#tagging-specification-semvertag).
