### ISSUE TITLE
RAM requirements

### ISSUE THREAD

**Issue by marilyn4325** [wavesplatform/Waves#25]
The node crashes with out of memory exceptions, if it runs on a system with limited RAM, like a VPS with 2 GB RAM. But if it is started with the`-Xmx1024m` command line argument to the Java program 
(or `-J-Xmx1024m` if started with the waves wrapper program), it works even on such a small system. Looks like if there is no max memory limit specified, it needs between 4 GB and 8 GB RAM. Don't know if it needs to be examined, but the RAM requirements should be at least mentioned in the docs. A few people in testnet-maintainers reported such crashes.

**Comment by Tolsi** [comment]
JMM has not only the heap, but other memory areas are approximately 256MB by default. So I am a bit do not understand what is the issue, if you can't reproduce it by some clear steps. Now the node we are working on many machines with 2GB of memory and we have never had such this trouble in the last few months.
