### ISSUE TITLE
domain name as declared address in config

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2505]
Hello. I see here: https://github.com/wavesplatform/Waves/blob/master/node/waves-mainnet.conf
the option:

```
# declared-address = "1.2.3.4:6868"
```
So can you make the "Declared address" to be the domain name,
because if I have dynamic IP and DDNS, I can specify domain name only.

Or just option to change IP to the current external IP.

Also, what about onion-domains in TOR network?

**Comment by phearnot** [comment]
Hi, this is the P2P protocol limitation, although it may be changed in one of the future releases.

Please note however that there's most likely no need to change this settings at all, unless you're running your node on an always-on cloud server (which has a static, public IP address). When `declared-address` is not defined, your node will only establish outgoing connections (but will not accept incoming ones), which is perfectly fine. 

If you want your node't P2P connections to run over TOR network, consider using a specialised OS like [Whonix](https://www.whonix.org/wiki/Features) which route all network traffic over TOR.

**Comment by username1565** [comment]
I just see here https://wavesblockexplorer.com/#!/peers
in **Declared address** field, one node, has "N/A", now,
but all another peers has only IP addresses there.
But if I want to specify there
something, like my_node.duckdns.org:6868, or blahblah.onion:6868
then my node cann't accept incoming connections, only outgoing...

**Comment by phearnot** [comment]
You can define any address as your node's declared address, as long as other nodes can establish connections to this address. But I'd like to stress that you don't _have_ to. There's no benefit to having more incoming connections than outgoing ones. 
Also even if `peers.dat` goes stale (e.g. because the node was stopped for some time), once the node connects to the first peer, it will get the most recent peer list from that node, so there will be a plenty of new addresses to connect to.

**Comment by username1565** [comment]
Ok.
So, as I understand, if my node will be disconnected some time,
and if my `peers.dat` will be not actual,
I just need to connect to one from working node to update `peers.dat`.

And I just need to update `known-peers array` for [node.conf](https://github.com/wavesplatform/waves-documentation/blob/master/ko/waves-full-node/how-to-configure-a-node.md)...

I see here: http://dev.pywaves.org/nodes/ some nodes, but this list need to edit manually,
to get `known-peers array` for `node.conf`,
and some nodes there has no opened `P2P port`.
Also I don't see port there.
This can be 6868 or [6863](https://github.com/wavesplatform/waves-documentation/blob/master/ko/waves-full-node/how-to-configure-a-node.md)

I also, see some nodes here: https://wavesblockexplorer.com/#!/peers
and here https://wavesexplorer.com/peers
and inside NODE REST API, like this: https://waves.guarda.co/
there is `peers/all`: https://waves.guarda.co/peers/all

But... I don't see any domain names, or onion-domains there, in **Declared address.** 
So I think need add this in future, and resolve specified domain names, if node has dynamic IP, for example...
