### ISSUE TITLE
No backward compatibility with blockchain-archive

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2507]
Windows.

After [downloading tar-archive with blocks](http://blockchain.wavesnodes.com/), according [this guide](https://docs.wavesplatform.com/en/waves-node/options-for-getting-actual-blockchain.html)
and unpack this blocks to "data"-folder,
latest version of the node, **waves-all-1.0.2.jar** tell me an error.

But old version **waves-all-0.15.4.jar** working normally with this blocks, inside that tar-archive.
Maybe there is no backward compatibility, so need to test and fix this.

**Comment by username1565** [comment]
**Solved!**

I see the node with version v0.15.6 working good with .tar-archive.
But after start node, this node is verifying blocks after connect to the nodes.

The node with version v0.16.2 ask for rebuild storage, when .tar-archive is unpacked in "data"-folder.
So I just imported blocks [from binary file](http://blockchain.wavesnodes.com/mainnet-1655722) for node v1.0.2...
After downloading blockchain as binary file, according [url=https://docs.wavesplatform.com/en/waves-node/options-for-getting-actual-blockchain/import-from-the-blockchain.html]this guide[/url]...
I see blocks verification is processing locally and more faster.

Issue is resulved and closed.

**Comment by username1565** [comment]
I again open this issue to ask the following thing:
Is there any .tar-archive with verified blocks,
which has the backward compatibility with nodes version after v0.16.2?
Verification of blocks so slow (sometimes 100 blocks for 4 minutes!),
and will be better to just unpack tar-archive.
But after version v0.16.2 node ask about rebuild storage...

Can you add some option to make .tar-archive with already **verified blocks**?
Not a **binary file**, because import of blocks from **binary file**
just runing verification of blocks again...

**Comment by phearnot** [comment]
The TAR archive we host should be compatible with the most recent node version. Could you please post a log excerpt containing the exact error you're getting after downloading and extracting the `blockchain.tar`?

**Comment by username1565** [comment]
Something long answer with `scala`-error, and many letters there.
I don't want to repeat this, because now, I do import the blocks from **binary file**.

**Comment by username1565** [comment]
Validation of blocks is so slow...
```
2019-08-16 16:08:22,732 INFO [shutdownHook2] c.wavesplatform.Importer$ - Imported
172576 block(s) from 1281857 to 1454433 in 46 hours, 11 minutes, 33 seconds and 193 milliseconds
```
2 days only 172k blocks... Huh...
