### ISSUE TITLE
Impossible to write verified 150KB DataTransaction in case of scripted account

### ISSUE THREAD

**Issue by amurdev** [wavesplatform/Waves#2515]
**Description**
According to documentation max DataTransaction size is 150KB. But at the same time it is impossible to pass parameter greater than 32KB to the _sigVerify_ RIDE function.
It means that you couldn't verify 150KB DataTransaction in RIDE script and as a result max size is limited by 32KB

**Steps to reproduce the behavior:**
1. Create and deploy script which use sigVerify function
2. Pass DataTransaction with size greater that 32KB

**Expected behavior**
DataTransaction is accepted by Blockchain

**Actual behavior**
`{"name":"sigValid","error":"Invalid message size, must be not greater than 32 KB"}]`

**Additional Context**
See `com.wavesplatform.lang.v1.BaseGlobal#MaxByteStrSizeForVerifyFuncs = 32 * 1024`

**Comment by msmolyakov** [comment]
Yes. Currently, only Data transactions up to 32 KB can be verified in STDLIB V3. This limit will be removed in the next STDLIB version.

**Comment by msmolyakov** [comment]
closed due inactivity. Please feel free to reopen the issue if you still have questions

**Comment by amurdev** [comment]
Please explain what is an approach to close an actual issue 'due inactivity'?
Previously it was confirmed that problem exists. That why there are 2 option to close it - either update documentation or fix STDLIB.
