### ISSUE TITLE
[FEATURE] Chain of leasing, with cancel leasing from the chain, if main node - shutdown and long time offline.

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2531]
**Аbstract**
Is your feature request related to a problem? Please describe.
Yes. If the mining-node is offline, this cann't do mining.

**Motivation and Purposes**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [no any LPOS rewards].

** Specification**
A clear and concise description of what you want to happen. Describe alternatives you've considered

I have the node. And I have receive the LEASED WAVES...
But I cann't to re-lease it to another node, if my node not online...

So, can you realize the auto-leasing for largest mining pool which is from the active peers on the main node, which is online in decentralized network,
and lease this WAVES if the main node is not available online, and will not to be online, and cann't staking?
For example, transaction of leasing go to the network, and if the main node is not available within 12 hours,
then this trancaction can be included into the microblock and inside new generated block in mainnet.
Else - not include this, and repeat signing and send this transaction again, from the main node, with new timestamp.
Is timestamp of transaction is significant to include in microblock?

Also, in the case of the leasing chain, all WAVES can be leased by principle unspent outputs,
and cancel leasing in this case can be realized fragmentary...
If real holder want to cancel leasing, this can be cancelled for all chain, but not all re-leased waves can be cancelled then,
and only his leased waves can be returned - to him, from the chain of re-leasing.

**Backwards Compatibility**
Can your proposition affect any existing features?
Maybe, yes, or maybe no.

**Examples and Implementation**
Examples of implementation in other projects?

As I know, bitcoin transactions can be signed manually, and locally,
and then, this can be broadcasted to the miners at any time, as [the RAW transaction](https://www.blockchain.com/ru/btc/pushtx), by just broacasting this to the mining pools.
So no any difference between timestamp of transaction, and maybe, this transaction can be included from mempool, in block at any time, on the mining pools.
That means, if signed transaction of the re-leasing to another node, will be sent with older timestamp, in this case, re-leasing transaction can be confirmed, and this transaction can be included to the block later, even if the main node will be shutdown and will be long time offline.
But I don't see any unspent outputs in waves blockchain...
So I don't understand how to realize leasing cancelleration from the chain of leasing.

**Comment by pivoo81** [comment]
When you lease your Waves to some node you need to make sure it's reliable.
If it's not - you can choose another node to lease your Waves.

We want leasers to be active users of the Waves ecosystem, so they can empower nodes to generate blocks and govern the Blockchain.
The proposed feature goes against this intention because user can lease Waves and even don't think about the reliability of the node receiving leasing.

**Comment by username1565** [comment]
Hehheh. Isn't that the sence of leasing?
Just put the money in leasing, and forgot for this on a year.
And no need to keep the node online.
It works so right now.
What active users you talking about?
Rewards for leasing are incoming for each leaser.

**Comment by username1565** [comment]
If blockchain is damaged on my node, and I don't want to make re-synchronization, but I have leased waves on my node from someone, will be better to just re-lease this all on the working node, and be able for each lease-giver - to cancel his leasing from the leasing-chain. IMHO.
But this is not easy to programming...
