### ISSUE TITLE
[FEATURE] ADD UTXO for WAVES and tokens.

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2539]
**Аbstract**
Is your feature request related to a problem? Please describe.
Maybe yes.
I just don't see [UTXO](https://en.wikipedia.org/wiki/Unspent_transaction_output) in [Waves blockchchain](https://wavesblockexplorer.com/#!/blocks).
What about attempts and ability of double spending in this case?

**Motivation and Purposes**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I receive fake assets].

** Specification**
A clear and concise description of what you want to happen. Describe alternatives you've considered
Bitcoin has UTXO principle, and no one cann't send the signed transaction to spend coins from output, where this already spent.
This transaction just cann't be confirmed and included by miners in the block on the mining pools.

**Backwards Compatibility**
Can your proposition affect any existing features?
Maybe yes, but maybe no.

**Examples and Implementation**
Examples of implementation in other projects?
[Bitcoin blockchain](https://www.blockchain.com/explorer).
You can see JSON transactions inside the blocks - [using this API](https://www.blockchain.com/ru/api/blockchain_api)
As you can see, there is using [UTXO](https://en.wikipedia.org/wiki/Unspent_transaction_output).

**Comment by pivoo81** [comment]
Hi, we have different than UTXO model - accounts.
To spend coins from the account signature must be provided. 
Noone can spend coins he haven't on his account. Such transaction would be rejected by miners
