### ISSUE TITLE
[FEATURE] Warning notice for enabling REST API

### ISSUE THREAD

**Issue by WavescapTorben** [wavesplatform/Waves#2552]
From time to time there are nodes with enabled REST API and standard password probably because they are not aware of making their private wallet key public if they didn't change the API key by changing the api-key-hash.
I would like to propose a hint in the config right there where you can enable the API. 
Or maybe even better disable endpoints that shouldn't be public if the api-key-hash has not been touched.

**Comment by pivoo81** [comment]
Hi. Yes, we will provide such functionality. 
We plan to disable previously used default API-key "ridethewaves!" - it will not work, and require some other not empty API-key.

**Comment by phearnot** [comment]
This has been released with version [1.1.2](https://github.com/wavesplatform/Waves/releases/tag/v1.1.2). Default API key hash has been removed from configuration file. Unless the user explicitly specifies their own API key hash, the node will reject all requests to private methods.
