### ISSUE TITLE
[FEATURE] Off-chain transactions, like yobit-codes

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2587]
**Аbstract**
>Is your feature request related to a problem? Please describe.

This is not a problem, just request to add new function.

**Motivation and Purposes**
>A clear and concise description of what the problem is. Ex. I'm always frustrated when

[I cann't convert my assets into some [tradable info-file](https://satoshidisk.com/) or into [codes, like a YOBIT-codes](https://yobit.net/ru/yobicodes/) to make PR for this assets, like info-goods.]

**Specification**
>A clear and concise description of what you want to happen.
>Describe alternatives you've considered

Can you implement something, like [YOBIT-codes](https://yobit.net/ru/yobicodes/), to make off-chain transfer of assets.
For example: 1 token is burning (or locked), and return the code. This code is encrypted.
If this code will be decrypted, and if some another user enter this code in some field,
he can got that token at any-time, anywhere, even if he will be offline,
or if he is - in another segment of the decentralized network.
Also, this can be an encrypted signed offline-RAW-transaction,
which can be bloadcasted much later, to get this assets,
but, in this case, in blockchain must be a real transaction "wallet -> no one",
to exclude the double-spending.

**Backwards Compatibility**
>Can your proposition affect any existing features?

Maybe no, and maybe, you can implement this easy.

**Examples and Implementation**
> Examples of implementation in other projects?

1. [YOBIT-codes](https://yobit.net/ru/yobicodes/)
2. [send signed bitcoin raw-transaction as hex, at any-time](https://www.blockchain.com/ru/btc/pushtx)
3. [File-trading](https://satoshidisk.com/)

**Comment by pivoo81** [comment]
Please describe what you want to be implemented in the Blockchain Protocol. Is it needed? Why couldn't it be implemented in some other way?
Now the quality of the proposal is like a raw idea, it's very hard to verify it.

Please take care of developers time, provide more worked proposals.
You can verify your ideas in developers chats in telegram for example here
https://t.me/waves_ride_dapps_dev

**Comment by username1565** [comment]
Yes, it is raw idea.
If you're interested it, you can programing this yourself - in the best way.
I don’t know how, it could be programmed and implemented better - in the blockchain protocol.
But on https://YOBIT.net it is already implemented, and you can test how it works, there.
The idea is to make from that codes - a digital product,
which anyone could carry with himself, off-chain, like a file for example.
And just trade with this, and exchange this!

**Comment by pivoo81** [comment]
If you want your proposal to be reviewed please describe it like proposal. Carefully

**Comment by username1565** [comment]
This is proposal can be described shortly, just as **ANALOG of YOBIT-CODES** or **scretch cards**, for WAVES and all assets in WAVES platform.
Other words the **carried digital assets**.
