### ISSUE TITLE
[FEATURE] Publish the transaction list for deposit-withdrawals

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2588]
**Аbstract**
>Is your feature request related to a problem? Please describe.

Yes, sometimes this is a problem,
because there is no any dependency
between transactions of tokens
and transactions in blockchains.

**Motivation and Purposes**
>A clear and concise description of what the problem is. Ex. I'm always frustrated when

[I can not prove that the transaction on the blockchain is the result of the fact that I brought out the associated tokens].

**Specification**
>A clear and concise description of what you want to happen. Describe alternatives you've considered

Can you publish transactions list for each processed deposit/withdrawal, where will be able to see the all dependencies between transactions for bitcoin address and transactions for waves address?

**Backwards Compatibility**
>Can your proposition affect any existing features?

Maybe no. Just transactions list on the service https://coinomat.com

**Examples and Implementation**
>Examples of implementation in other projects?

Maybe, somewhere is already exists the lists, like this.

**Comment by pivoo81** [comment]
Description is not clear now.
This question is connected to Coinomat, as I understood. 
It's not connected to Waves blockchain protocol, therefore it's not for this repository.

There is new implementation of gateways in development. They plan to provide such information.
