### ISSUE TITLE
Non-valid peers

### ISSUE THREAD

**Issue by jansenmarc** [wavesplatform/Waves#26]
It seems like there are a couple of non-valid peers propagated through the network, e.g., IPs like 127.0.0.2 and others. Usually it helped to delete peers.dat and restart the node, but this issue should be solved anyhow...

**Comment by asolovyov** [comment]
An obsolete peer data cleanup will be a part of the next release.

**Comment by asolovyov** [comment]
An obsolete peer data cleanup has been added to [Release 0.2.4](../releases/tag/v0.2.4). 
For now, peers which have not been touched (connected) during a day (24 hours) are removed from peers.dat list.
