### ISSUE TITLE
[JUST QUESTION] How to accept WAVES on the site?

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2634]
Is there any guides about set up accepting the WAVES on the site, and pay this, like PayPal?
For example, I want to host my own exchanger, like many another here: https://bestchange.ru/
I see WAVES there, and there is aveailable many ways to exchange WAVES to crypto and fiat currencies.

I know, the WAVES address and seed, can be generated client-side, using some scripts,
like this: https://cryptostorage.com/generate.html?tickers=waves
And WAVES-address can be unique for each new user.

But... How to connect WAVES into exchange-site, and another site (online-store, for example), to make automatically deposit-withdrawals of the WAVES?
How to get last block in blockchain?
How to check balance by address?
How to get transaction ID for last WAVES transaction?
How to check is transaction confirmed or not?
How to see the number of block, where transaction was been included?
How many maturation for each transaction? 1000 blocks?
How to request payment, like in your waves-client?
How to check is payment already processed or not?
How to calculate the profit for leasers?
How to set up some script for autopay for leasing?

Is there any guide to do this all?

I see here: https://h2ox.io/
there is possible to confirm waves-address, using the payment of the some token, with some value in attachment.
Also, I see they have enabled the auto-payments for leasing after each generated block.

Is there any scripts to do this all?

**Comment by vlzhr** [comment]
Hey, @username1565! It'd be more convinient to discuss these things in the Waves official Dev chat: https://t.me/waves_ride_dapps_dev. Please resend your questions to it and feel free to ask there for any other assistance.

**Comment by username1565** [comment]
Oww, I did not registered in telegram, and will not to be, because there need to specify my own phone number.

**Comment by username1565** [comment]
Is it possible to connect specified WAVES-token on the site?

**Comment by msmolyakov** [comment]
Deposit-withdrawals are just transactions in blockchain. To sign and send these, you can use [Waves Keeper API](https://github.com/wavesplatform/waveskeeper) or any client Waves library for your preferred programming language. For example, [waves-transactions](https://github.com/wavesplatform/waves-transactions) for JavaScript.

How to get any information - see [Swagger documentation for Node API](https://nodes.wavesnodes.com). Any [client libraries](https://github.com/msmolyakov/awesome-waves#client-libraries) can retrieve data from this API.

Btw, you can run your [private local node](https://hub.docker.com/r/wavesplatform/waves-private-node) for experiments and testing.

There is some scripts by community for autopayments to leasers. For example, [https://github.com/w0utje/WavesLPoSDistributer](WavesLPoSDistributer).

**Comment by username1565** [comment]
Hi @msmolyakov! Thanks for your info!

But this issue was been opened to get the guide of optimal include deposit-withdrawals some token on the side.
I just want to know how to organize this by optimal way, using this all.
For example, I want to add on the site the ability of deposit the specified tokens to account,
and withdraw this tokens to the address of user.

You say about I can sign transactions, using script, and broadcast this, using [NODE REST API](https://nodes.wavesplatform.com/)
```
POST /transactions/broadcast 
```

Also, I can see info about this transaction, after receive the txID:
```
GET /transactions/info/{id} 
```
Ok...
But I don't see confirmations for specified sent txid.

I can see `"height": block_number`, in the response, where `block_number` is a block number, where this transaction was been included.

Also, I can get current block height:
```
GET /blocks/height 
```
and if I'll know previous `block_number`, I can calculate number of confirmations for sent transacton.

Okay...
I still don't understand on which step I can get `txID` of transaction After `sign` it, right?
This txid can be generated client-side?
This all - just about sending the transactions...

But what about accepting the transactions?
I see here is possible to get the list of transactions:
```
GET /transactions/address/{address}/limit/{limit} 
```
What if there will be so many transactions?
Need to check this all every time, and load every time many old transactions?

Here, I can see full balances, by specified address:
```
GET /assets/balance/{address}
```
But this contains many data, and slow loading...

Here, I can see balance for specified address and specified asset:
```
GET /assets/balance/{address}/{assetId}
```
If this value will be changed, then I can request list of transactions by address.
Hm, and this is working very much faster...

________
So at first, I may to generate random address for each user,
then propose to send there some tokens,
then check the balance on this address, by of this tokens:
```
GET /assets/balance/{address}/{assetId}
```
And if balance over 0, then get tansactions:
```
GET /transactions/address/{address}/limit/{limit}
```
After this, I can extract the amounts, and deposit this amounts of tokens on the account for this user.
But... To transfer tokens from there, I need to do airdrop of the waves to pay comissions for transfer. And if address will be generated on the server-side, then seeds will be on the server,
and all this randomly generated addresses will be my addresses, on my server.
All right?

**Comment by msmolyakov** [comment]
Yes, you can create, sign and send transaction from client side.

To check that transaction is in blockchain, you can call `transactions/info/{txId}` endpoint instead of `transactions/address`.

Store seed on server is bad idea. Propose users to use Waves Keeper or store user's seed in local storage of his browser, but notice him to backup seed.

**Comment by msmolyakov** [comment]
Yes, you can get tx id without blockchain.

No, we haven't any plan about analog of this service. Feel free to create your own :)
