### ISSUE TITLE
Can't get seed from address on the node.

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2654]
**Describe the bug**
>A clear and concise description of what the bug is.

`GET /addresses/seed/{address}` - not working correctly. This is not returning the seed, this is returning some base58 encoded string.

**To Reproduce**
>Steps to reproduce the behavior:

1. Go to 'the local [Node REST API](https://nodes.wavesplatform.com/api-docs/index.html) with your API key.'
2. Click on `Addresses`->`GET /addresses`, and get addresses on the node. Copy this address.
3. Scroll down to '`GET /addresses/seed/{address}`, and try to get seed.'
4. See error (Not an error, but this is unknown base58 encoded string.)
5. Try to get this address from that base58 string.
6. Compare that address with your entered address.
7. See error - not match.

**Expected behavior**
>A clear and concise description of what you expected to happen.

Mnemonic passphrase, base58 encoded seed (this mnemonic passphrase),
or privateKey from the address on the node.
Because that string cann't give the access to this address in [waves-client](https://client.wavesplatform.com/#!/dex-demo).
Will be better to return `mnemonic words of seed`.
Or describe the way to get this address and keypair - in the title tooltip.

**Screenshots**
>If applicable, add screenshots to help explain your problem.

No need.

**Desktop (please complete the following information):**
 - OS: [e.g. Debian/Ubuntu/iOS] - Winows, `.jar`-file.
 - Browser/JVM [e.g. chrome, safari] - all.
 - Version [e.g. 22] - node v1.1.2, the Node REST API.

**Additional context**
>Add any other context about the problem here.

Cann't access to generated address, after:
`POST /addresses - Create`.
What if I did generate new address on the node, and by mistake did transfer there some waves, just for test, and now I cann't to transfer this back from that address???

What means this base58 string?
This is not private key. This is not seed. This is not public-key.
How to get address from this string?
I did try to encode this string to bytearray, and using as hash, or as bytes to get hash, and then try to generate keypair, but I cann't get the node-address.
And of course, I did try to using this string, as base58Encoded seed in config, with generated address, and I see "error with throw exception", about `invalid Instance0`.

Maybe, something is wrong with this base58encoded string, and need to fix this.

I see, [here from private key get some value of seed](https://github.com/wavesplatform/Waves/blob/816e0c2f378a7b102852860c9737fde61dab6252/node/src/main/scala/com/wavesplatform/api/http/AddressApiRoute.scala#L268), before return this.
But how to get private key from this "seed", again?

Is this possible to return base58 encoded private key, or keypair: base58(pubkey + privkey)?
Or will be better to return mnemonic passphrase, just to copy and paste this to [waves-client](https://client.wavesplatform.com/#!/dex-demo) and log in...
Also... Is this possible to get `publicKey` from `PrivateKey`, by multiple this on elliptic curve?

**Comment by username1565** [comment]
Also, is there any explanation, about `wallet.dat` format?
I see there is base64 encoded data.
After decoding this to hex, I see some value in the end of this data,
and this value seems like hash (32 bytes).
After new address created, I see come additional data (+48 bytes), and new regenerated string in the end (+32 bytes, seems like hash).
So, as I understand, all data about new generated address, contains in that new added 48 bytes.
I just decoded generated WAVES-address from base58 to hex, I don't see bytes from address, in this 48 bytes, there. 
What is this bytes? This not seems like privkey or privkey+pub. Maybe this is a seed-bytes or hash of seedbytes?
Hm... Don't understand...

**Comment by phearnot** [comment]
Just as stated in the endpoint description, `/addresses/seed/{address}` returns account seed value which is used to derive the key pair which corresponds to the given `{address}`, not the "main" seed. See [cryptographic details](https://docs.wavesplatform.com/en/blockchain/waves-protocol/cryptographic-practical-details.html) for more info.

After creating a new address with `POST /addresses`, you'll see your newly generated address in the response (and also in `GET /addresses` response). You can use `/addresses/seed/{address}` to retrieve account seed, and then derive private and public key for new address.

Considering `wallet.dat` — its format is an implementation detail and not a part of public API (and therefore can and probably will change without notice), but it is indeed an AES-encrypted JSON which stores the main seed, account seeds and a counter.

**Comment by username1565** [comment]
Thanks. I just did decode this seed string to bytes, calculated sha256-hash from this string, and then sucessfully got keypair. So, you're right, this is not a bug.
But you can add some description there, or title tooltip, if you want.

Best regards.
