### ISSUE TITLE
[FEATURE] Add ability to request payments for leasing.

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2655]
**Аbstract**
>Is your feature request related to a problem? Please describe.

Yes. Scripts for autopayments can pay for leasing to the users, who are inactive, in this case all system is loss the WAVES.

**Motivation and Purposes**
>A clear and concise description of what the problem is. Ex. I'm always frustrated when [waves are sent for inactive user, who lost privkey or dead].

So I want to propose add the ability to request payments for leasing.

**Specification**
>A clear and concise description of what you want to happen. Describe alternatives you've considered

When user cansel the leasing, he got only his leased waves, and lost comissions.
But in this case, user is active. Another leasing will be confirmed after 1000 blocks.
Now, there is possible to check is user active or not, by his address,
but this need to load many data for each user.
I want to propose the following thing. Just add button "request leasing interest".
If user is active and if he press this button, he send some data to the nodes, with his signature, and after verify this data, this go to mempool, and node can pay automatically.

**Backwards Compatibility**
>Can your proposition affect any existing features?

Maybe no, and this feature can be realized without including some transactions in blockchain. Just signalling between the nodes.
But, if the node still do mining, but has closed port, and not accepting the signals, it can accept the block with transaction type "data", which can contains the list of users,
who are already requested the payment for leasing from this node.
As additional option, need to implement autopaying on the node,
without include another scripts, and without visit some services, like this:
https://w8io.ru/3P3RD3yJW2gQ9dSVwVVDVCQiFWqaLtZcyzH/pay/1741000/1742000

**Examples and Implementation**
>Examples of implementation in other projects?

Compounding percentage or fixed percentage with regullary paying the profit.

**Comment by pivoo81** [comment]
Proposed functionality is not subject of the Node. User can signal that he is active (if it's truelly needed) by sending some tx. Paying script can watch for outgoing transactions by address.

If the node owner wants some special protocol confirming user alive he can implement it without blockchain and use even button for this, but in this case blockchain not needed.
