### ISSUE TITLE
SSL, HTTPS. TLS 1.2 not deprecated, and many browsers not supporting TLS 1.3

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2657]
**Describe the bug**
>A clear and concise description of what the bug is.

https://github.com/ and https://nodes.wavesnodes.com/
is using the both TLS versions, 1.2 and 1.3 (if this is available).
Disabling the TLS 1.2 make the resource shutdown for many browsers,
because there is no backward compatibility:
```
https://nodes.wavesplatform.com/transactions/unconfirmed
Failed to load resource: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**To Reproduce**
>Steps to reproduce the behavior:

1. Go to 'https://nodes.wavesplatform.com/'
2. Click on 'HTTPS'
3. Scroll down to 'TLS version'
4. See error (TLS version, this is 1.3).
Repeat this for github, this is supporting both TLS, 1.2, 1.3, and 1.2 not excluded, because this was been not deprecated.
TLS 1.0 and TLS 1.1 was been deprecated, and not using now, not TLS 1.2.

**Expected behavior**
>A clear and concise description of what you expected to happen.

Working HTTPS with TLS 1.2 in old browsers,
and TLS 1.3 in new browsers.

**Screenshots**
>If applicable, add screenshots to help explain your problem.

No need.

**Desktop (please complete the following information):**
 - OS: [e.g. Debian/Ubuntu/iOS] - all
 - Browser/JVM [e.g. chrome, safari] - all
 - Version [e.g. 22] - all

**Additional context**
>Add any other context about the problem here.

You can make both TLS (1.3 and 1.2), like here: https://nodes.wavesnodes.com/ or https://github.com/

And maybe, will be better to include HTTPS-module with all TLS versions, inside the node application.

Also, while you did not setup TLS 1.2 on default *.wavesplatform.com,
you can change this to *.wavesnodes.com as default.
This is the same servers, and there is working TLS 1.2 and TLS 1.3 (as additional option),
but this not default servers, and https://matcher.wavesplatform.com/ using TLS 1.3,
and return error for browsers, where is using TLS 1.3 not supporting, and using TLS 1.2.
So noone cann't connect there, and trading, by using TLS 1.2.

**Comment by mtuktarov** [comment]
Hi @username1565 
Please advise what you mean in step 2 **Click on 'HTTPS'**? Where is such a button?
In brief, we failed to replicate. Please provide us with the exact steps and screenshots if possible ;)

**Comment by username1565** [comment]
Hi, @mtuktarov.
See this screens:

![wavesplatform com_TLS1 3](https://user-images.githubusercontent.com/39200328/66994249-9fba5580-f0d5-11e9-8c1c-7281e76d37bc.png)
![wavesnodes com_TLS1 2](https://user-images.githubusercontent.com/39200328/66994250-9fba5580-f0d5-11e9-908f-2cf540a9a8b6.png)

As you can see, wevesnodes.com us supporting both TLS 1.2 and TLS 1.3, but wavesplatform using only TLS 1.3, and not opening in browsers, where TLS 1.3 not supported.

**Comment by phearnot** [comment]
Both nodes.wavesplatform.com and nodes.wavesnodes.com support TLS 1.2, you can check this with openssl:
```
~ ▶ openssl s_client -connect nodes.wavesnodes.com:443 -tls1_2 </dev/null 2>&1 | grep Protocol -B1
SSL-Session:
    Protocol  : TLSv1.2
~ ▶ openssl s_client -connect nodes.wavesplatform.com:443 -tls1_2 </dev/null 2>&1 | grep Protocol -B1
SSL-Session:
    Protocol  : TLSv1.2
```
I assume the browser on the upper screenshot picks up the most recent version it supports, this is why it's using TLSv1.3. Could you please share the exact versions of browsers you're using which have issues with nodes.wavesnodes.com?

**Comment by username1565** [comment]
>Could you please share the exact versions of browsers you're using which have issues with nodes.wavesnodes.com?

For example, when I try to open https://nodes.wavesplatform.com/
the Google Chrome 34.0.1847.131 m, say me the following throw error in console.log()
```
GET https://nodes.wavesplatform.com/ net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH https://nodes.wavesplatform.com/:1
```
But https://nodes.wavesnodes.com/ opening good there, and I see HTTPS is working, with TLS 1.2. That means, something on your server side - is not saving the backward compatibility,
and waves-lite client cann't working in this case, with default node and matcher, which are hosted on *.wavesplatform.com.
Maybe many your clients and customers cann't get access to their accounts from old browsers, as it was before, out of habit.

**Comment by phearnot** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Google_Chrome_version_history), Chrome 34.0.1847 was released in April 2014 (over five years ago!) and is no longer supported. I highly discourage using discontinued versions of any software, especially web browsers.

By the way, Waves Lite Client has been deprecated and is no longer supported. However, as long as source code is available, you can build your own client and run it against an environment set up for your specific requirements (e.g. select ciphers and TLS versions).

I am closing this issue for now, because no users running "recent" versions of popular web browsers seem to be affected at this time.

**Comment by username1565** [comment]
Yes, but I want to warn you that first of all, you should think about
how to ensure maximum backward compatibility,
instead of forcing your old investors
to buy new devices and licenses
for modern, updated and newer software.

Have a nice day.
