### ISSUE TITLE
Can't get seed value using address !!!

### ISSUE THREAD

**Issue by narmathamuthu** [wavesplatform/Waves#2728]
Hi team , 

I got this error ( no private key for sender address in wallet ) when i get the seed value using address in our node.

PFA.

![image](https://user-images.githubusercontent.com/55826071/68772451-db522c00-064f-11ea-8f5a-d77e8d024cf2.png)

Please provide the solution ASAP.

**Comment by ismagin** [comment]
You are sending address that the node doesn't have seed for.
