### ISSUE TITLE
leveldb says "Corrupted compressed block contents"

### ISSUE THREAD

**Issue by Caveman2019** [wavesplatform/Waves#2750]
Hi, I am trying to run a waves full node and ran into trouble.

because downloading blocks from peers takes too long, so I was following [this](https://docs.wavesplatform.com/en/waves-node/options-for-getting-actual-blockchain/state-downloading-and-applying.html) to restore the blockchain.

I have a windows server and I unpacked the downloaded tar file into the waves node root folder and I see everything is in the ./data folder but when I started the node by this:  {java -jar waves-all-1.1.5.jar application.conf} I got an error

![image](https://user-images.githubusercontent.com/9812320/69186155-d61c3380-0acc-11ea-9fad-1104e1784268.png)

[The docs](https://docs.wavesplatform.com/en/waves-node/options-for-getting-actual-blockchain/state-downloading-and-applying.html) says "running sudo systemctl start waves" in Linux not sure if I should use a different command to start the node on Windows server.

Could you help?  Thanks!!

**Comment by Caveman2019** [comment]
Seems it is because the downloaded state is Linux only. The solution would be to add windows based state for downloading if possible or some kind of converter.

**Comment by Caveman2019** [comment]
OK, I am importing from the main net file and it seems working. case closed.

**Comment by Caveman2019** [comment]
importing seems working but still very slow. would be great if there is packed state for windows

**Comment by phearnot** [comment]
Which hardware are you using to import blockchain? While the process is indeed taking longer than we'd hope, weeks seems like an overstatement to me, it's more like days (3 to be precise).

Also we're now investigating the possibility to upgrade LevelDB library to a newer version, which will hopefully enable us to share state files between different platforms.

**Comment by msmolyakov** [comment]
Hi, @Caveman2019!
Is your problem case actual on the latest 1.2.13 version?

**Comment by Caveman2019** [comment]
> Hi, @Caveman2019!
> Is your problem case actual on the latest 1.2.13 version?

Hello. We added duplicated nodes on Linux as a solution for this. For rebuilding states it still takes very long on Windows as there is not any data for download.

**Comment by DrBlast** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
