### ISSUE TITLE
самая отстойная платформа вместе со стеларам 

### ISSUE THREAD

**Issue by yury653** [wavesplatform/Waves#2778]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Debian/Ubuntu/iOS]
 - Browser/JVM [e.g. chrome, safari]

**Additional context**

**Comment by yury653** [comment]
я не про вас я перепутал,извините

**Comment by Ronald26** [comment]
удалите мойе негативное отзыв

**Comment by Ronald26** [comment]
удалите мой негатив я не вам адресавал
