### ISSUE TITLE
самая отстойная платформа вместе со стеларам #2778

### ISSUE THREAD

**Issue by yury653** [wavesplatform/Waves#2779]
**Аbstract**
Is your feature request related to a problem? Please describe.

**Motivation and Purposes**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

**Specification**
A clear and concise description of what you want to happen. Describe alternatives you've considered

**Backwards Compatibility**
Can your proposition affect any existing features?

**Examples and Implementation**
Examples of implementation in other projects?

**Comment by yury653** [comment]
я не про вас я перепутал,извините

**Comment by yury653** [comment]
удалите мое негативное

**Comment by Ronald26** [comment]
удалите мой негативный отзыв

**Comment by Ronald26** [comment]
удалите мой негатив ,я не вам адресавал
