### ISSUE TITLE
Best practices of `case _ =>`

### ISSUE THREAD

**Issue by ismagin** [wavesplatform/Waves#2794]
*How it Works*
Matching works as a reflection-like call to `_isInstanceOf` function.
The code:
```
match tx {
  case t: BurnTransaction => foo
  case t: ReissueTransaction=> bar
  case _ => baz
}
```
gets compiled to 
```
if(_isInstanceOf(tx, "BurnTransaction")) 
  then foo
  else if(_isInstanceOf(tx, "ReissueTransaction"))
     then bar
     else baz
```

**The proplem**
Let's say someone deploys a script:
```
{#- STDLIB_VERSION 3 -#}
let multisig = sigverify(..) && sigverify() && sigverify() # 3 of 3
match tx {
  case t: ReissueTransaction => multisig 
  case _ => sigverify(..)
}
```

1. The intension of the script author Rob is something like: "ReissueTx is very important, so it will be protected by `multisig `, while the other txs are okay on a regular basis, so we just use `sigerify()`.
2. Now, a new type of transaction is about to be rolled out: `UpdateAssetInfoTransaction`. 
3. This script has been deployed before this tx was even planned, so when an `UpdateAssetInfoTransaction` hits it, it will get to `case _ =>`, so Rob might get furious: _I didn't know that tx will be introduced, and it's super important and should be denied at all, needless to say, sigverify is not enough!_

***Denying new txs in scripts is a poor option***
This might be the first idea, but it breaks something more fundamental:
1. Alice doesn't have a scipt
2. Bob sets a script with an intension just to change private key:
```
{#- STDLIB_VERSION 3 -#}
sigVerify(tx.bodyBytes,tx.proofs[0],base58'3Pm..')
```
3. `UpdateAssetInfo` is activated on mainnet
4. Alice can send `UpdateAssetInfo` transaction
5. **Bob can't send `UpdateAssetInfo` transaction**

So, By changing keys from his account Bob lost an ability to send new types of transactions, unless he redeploys the same script, but with `{#- STDLIB_VERSION 4 -#}`. This doesn't seem right.

***Allowed-else-denied vs Denied-else-Allowed***
When Rob implemented his script, he missed the distinction between the aformentioned approaches. 

Given 

1. matching is a set of if-else calls to `_isInstanceOf` function
2. `Transaction = ReissueTransaction|BurnTransaction|MassTransferTransaction|ExchangeTransaction|TransferTransaction|SetAssetScriptTransaction|InvokeScriptTransaction|IssueTransaction|LeaseTransaction|LeaseCancelTransaction|CreateAliasTransaction|SetScriptTransaction|SponsorFeeTransaction|DataTransaction`
3. `tx` can also be `Order`

The better way is to explicilty set rules for ALL current tx and set `case _` rule for all new transactions. 

```
{-# STDLIB_VERSION 3 #-}

match tx {
    case t: TransferTransaction => ... # condition for TransferTransaction
    case t: Transaction => ... # condition for all other transaction types known at STDLIB_VERSION 3
    case o: Order =>  ... # condition for order
    case _ => ... # condition for all other future types of input(new transaction types)
}
```

**Comment by DrBlast** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
