### ISSUE TITLE
Endpoints not responding

### ISSUE THREAD

**Issue by jansenmarc** [wavesplatform/Waves#28]
It seems that on machines with less than 2GB of RAM some endpoints do not respond at all or take very long time to respond, e.g., /debug/info is not working. At the same time other endpoints (e.g., /blocks/height) are working properly.

**Comment by Arkhh** [comment]
did you try to restart your node ? I was experiencing the same issue. Are you using a swap ? Do you have a xmx param ?

**Comment by jansenmarc** [comment]
Yes, i restart my nodes quite often, cause they keep crashing. I also set the xmx parameter, tried with 768m and 1024m, both pretty much the same with this regard. I don't have swap...

**Comment by gagarin55** [comment]
/debug/info is switched off due to security reason. We are not sure is it really useful to have api endpoint which returns config file content.

**Comment by jansenmarc** [comment]
Agreed, i used it before to get the current height of the node, but this information is better received by the /blocks/height endpoint.

**Comment by Arkhh** [comment]
Are you still having issues with that ? Or is your node responsive now ?

**Comment by jansenmarc** [comment]
No, /debug/info is still not responding...
