### ISSUE TITLE
[FEATURE] Do the lite mining node.

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2837]
**Аbstract**
>Is your feature request related to a problem? Please describe.

Yes. Blockchain size is too large for my hard disk drive.

**Motivation and Purposes**
>A clear and concise description of what the problem is. Ex. I'm always frustrated when

[I cann't save all large blockchain, and I cann't do mining WAVES without save this].

**Specification**
>A clear and concise description of what you want to happen.
>Describe alternatives you've considered

I want to offer you to release the lite mining-node
to do mining waves and generate microblocks without store full blockchain.
Like bitcoin-ASIC's do mining without saving blockchain.
Now, blockchain size have over 50GB + testnet-stagenet blockchains.

**Backwards Compatibility**
>Can your proposition affect any existing features?

Yes, this can have backward compatibility.

**Examples and Implementation**
>Examples of implementation in other projects?

Bitcoin and altcoins mining pools, and lite wallets for Proof-Of-Stake coins.
Yes, I can leasing, but I want to do mining myself.

**Comment by pivoo81** [comment]
Lite wallet don't mine.
To validate transactions you need to know if they spend money they have - you need blockchain state for this. 
Script validations and invokeScripts also can require some data from blockchain.
We are working on state optimisations, in order to blockchain state become less.

**Comment by username1565** [comment]
Hi, @pivoo81! As I understanding, blocks can be loaded from another nodes, as JSON, by using their opened NODE REST API. For example: 184000-th block, as JSON here: https://nodes.wavesnodes.com/blocks/at/1840000
Also, the balances can be loaded without parsing all blocks.
So no need to store this all blocks to generate microblocks and push this to the mainnet for another nodes. Bitcoin ASICs working by this way, they not save all blockchain.
