### ISSUE TITLE
[Known Issue] Error while broadcasting transaction

### ISSUE THREAD

**Issue by pivoo81** [wavesplatform/Waves#2843]
In ver. 1.1.5 we introduced a hard limit on UTX processing time. We needed this limit because some transactions can take substantial amount of time to validate. This limit is not a part of consensus, it’s merely a safeguard to prevent such transactions from getting into the blockchain. This is a temporary measure, and we will be addressing the root cause of this issue (sub-optimal validation implementation) in the future release.
The way it’s implemented is a kind of a hack, and in some cases can lead to unwanted consequences: if transaction takes longer than 5 seconds to validate, the validating thread is killed, and validation future never gets completed. This causes API thread waiting for this future to get stuck. 
Since API thread pool size is limited, when all the threads get stuck waiting for the future which will never complete, the node effectively stops processing any API requests. 
To work around the case when future never completes, we introduced a 10-second timeout in ver. 1.1.6. When this timeout elapses, API thread gives up waiting for the future to complete, completes the request with a 500 response and moves on to the next request, this can be seen as {‘error’: 0, ‘message’: ‘Error is unknown’} response (note: such message could be seen in other cases). 
As a user, if you get such errors when attempting to broadcast your transactions via API, this means that the node is likely under heavy load and is unable to process your transactions in a timely manner. In such cases just try broadcasting the transaction once again.
One more side effect of this hack may be the presence of `NoClassDefFoundError`s in the node’s log. In some rare cases these exceptions may cause the node to stop. You’ll need to manually restart the node afterwards.
We plan to fix this in ver. 1.2. after new features activation.

**Comment by phearnot** [comment]
Fixed in #2885 and will be released with 1.1.8.
