### ISSUE TITLE
[Just question] Smart contracts to lease tokens?

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2861]
Is this possible to make some smart-contract, to secure leasing and unleasing transactions for the tokens, and pay the rewards for leasing as waves-rewards?
Leasing must to be secure, and the tokens must cann't be stolen or transferred from contract-address. This means, all signatures of contract address must to be invalid.
While tokens leased, any leaser can unlease this after some time,
but when this leased, this not traded, and this leasing is just as warranty of no any intervention on the market.
So, this leasing period can be fixed and contract address can pay for this leasing.

Is this possible, to make this all?

**Comment by pivoo81** [comment]
Hello. This repo is for node's features and issues. 
You can address such questions to dev groups in Telegram https://t.me/waves_ride_dapps_dev or in Discord
