### ISSUE TITLE
[WEBSITE] Revise website

### ISSUE THREAD

**Issue by ghost** [wavesplatform/Waves#2936]
**problem**

This site

https://nearprotocol.com/developers/

Is not perfect (several things can be enhanced), but it outperforms the waves site by far

**Motivation and Purposes**
 I'm always frustrated when I don't find the information fast, in different contexts, like...

- get some currency
- create an asset (super quick intro)
- create a simple dapp
- run a node
- core-level contribution

**Specification**

https://wavesplatform.com/

A few redesign steps should be enough, identified by an newcomer with an eye for details.

Create a mock site to demonstrate an efficient structure and draft content.

goal: A visitor stays with waves.

**Examples and Implementation**

Bad

* https://neo.org/dev
* https://wavesplatform.com/

Good

https://nearprotocol.com/developers/

best

?

**Comment by KardanovIR** [comment]
Thank you for your feedback and references, we're working on our website now, so we'll update relatively soon. I'll close this issue because this repository is about Waves Node, not the website.
