### ISSUE TITLE
Revise README

### ISSUE THREAD

**Issue by ghost** [wavesplatform/Waves#2937]
The README should be compact, straight to the point, in order to allow code-level workers to process it quickly.

* Build Status
* Description (very compact, consistent with repo-description)
* Install from Binaries (can point to online-manuals)
* Build from Source (basic build, e.g. for ubuntu, then point to manual for more info)
  * Running Tests
  * Install
  * Mention Mac and Win
* Contribution (tiny text, then point to manual / file)
* Developer Resources
* Acknowledgements (optionally)
* LICENSE

**Comment by KardanovIR** [comment]
Thank you for your feedback! We're in process of revising all our github repositories, so we'll update READMEs soon.

**Comment by phearnot** [comment]
Fixed in #3056
