### ISSUE TITLE
Transaction broadcasted using RPC doesn't appear in blockchain

### ISSUE THREAD

**Issue by szhelonkin** [wavesplatform/Waves#2938]
Transaction successfully signed by /transactions/sign
then successfully broadcasted by transactions/broadcast
but does not appear in blockchain. 
No information in the log about the transaction processing.
Problem appears in 1.1.8 version.
Before it works fine a lot of time.

**Comment by msmolyakov** [comment]
Hi @szhelonkin !
Are you using GRPC extension or REST API? Official https://nodes.wavesnodes.com/ or your own node?
If your own node, could you give trace logs? And also Id of the lost transaction?

**Comment by szhelonkin** [comment]
Hi @msmolyakov !

**Comment by msmolyakov** [comment]
Sorry for the long answer. Is the problem still there?

If so, please compare the last block on your node and on the official node: `/blocks/headers/last`. Are they on blocks with the same fields `"height"` and `"generation-signature"`?

If at least one of them is different, then the state of your node has been broken, and you need to re-import the blockchain again. Please read this documentation page: [Options for Getting Actual Blockchain](https://docs.wavesplatform.com/en/waves-node/options-for-getting-actual-blockchain/#_3-downloading-the-latest-node-database).

**Comment by szhelonkin** [comment]
No issue was resolved yesterday.
It was caused by internal DNS malfunction.
Thank you for reply.
