### ISSUE TITLE
[PROJECT] Provide a CONTIBUTING.md or DEVELOPMENT.md or similar

### ISSUE THREAD

**Issue by ghost** [wavesplatform/Waves#2942]
**Аbstract**

Every open source project should provide information about "how to contribute". Though on github this is more or less a standard-procedure, it is not always clear how a team is organized, and if external contributions are welcome and to what extend.

**Motivation and Purposes**

I'm always frustrated when...

* I can't get a status overview of a project, simply by looking on project resources
* I realize that there are internal issue-trackers, where the team keeps additional info

**Specification**

Provide a compact CONTRIBUTING.md (or aternatively DEVELOPMENT.md)

Either describe how folks scan contribute, or decribe  your development process (which can, if it fits you, discourage external contributors, e.g. if you have a "well coordinated internal team").

**Examples and Implementation**

## CONTIBUTING.md

Contributions are usually welcome, please take in account that:

* Many tasks require deep thought of the core-team, it is sometimes better to not distract
* File an issue first, to avoid too much work on a PR which will not get merged.
* Documentation has owners, which have an own writing style. Avoid too intense changes (e.g. sometimes better to file an issue, asking for an addition).
* The team uses additionally an internal issue-tracker (xyz)
* The main dev process is "Agile xyz", there is no writeup of the meetings currently.

**Comment by KardanovIR** [comment]
Thank you for your feedback! We'll add CONTRIBUTING.md in all our repos soon.

**Comment by lazaridiscom** [comment]
@KardanovIR , you should leave the "we will soon" to the politicians.

As I assess it, this project is not really interested in contributors. Quite closed processes, even closes source (see https://github.com/wavesplatform/Waves/issues/2942).
