### ISSUE TITLE
Bootstrap file

### ISSUE THREAD

**Issue by vladyslavstartsev** [wavesplatform/Waves#2949]
**Аbstract**
Waves  node syncs for a lot of time (it takes like forever)

**Motivation and Purposes**
I'm trying to install waves node on my server, but for whole week I'm waiting it to sync

**Specification**
If there is a way for it to sync for couple of hours that would be perfect. Other alternative instead of this will be, something like `fast` param in `conf` file. Anyway what I want in the end is high speed sync of the node.

**Backwards Compatibility**
Probably no

**Examples and Implementation**
Examples of implementation in other projects?
Yes, there are
I'm not making deep research, but that's what I've found
DASH - https://github.com/UdjinM6/dash-bootstrap
XMR - https://www.getmonero.org/downloads/ (search for "Blockchain Bootstrap" on the page)
NEO - https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files

**Comment by msmolyakov** [comment]
Hi, @vladyslavstartsev!
Yes, you can choose one of these options:

- import blockchain from binary file (3-4 days)
- download the ready node state (up to 10-15 minutes, depends on network speed)

Please read this documentation article: [Options for Getting Actual Blockchain](https://docs.wavesplatform.com/en/waves-node/options-for-getting-actual-blockchain/).

BTW, now we are working on optimizing the synchronization time and striving to make the process more convenient for users.

**Comment by msmolyakov** [comment]
Hi!

@vladyslavstartsev is your problem still there? Did you manage to import blockchain?

**Comment by vladyslavstartsev** [comment]
everything is fine
