### ISSUE TITLE
Could not append blocks

### ISSUE THREAD

**Issue by Caveman2019** [wavesplatform/Waves#2951]
My node seems not able to append more blocks. I tried to roll back a few hundrends of blocks but still not working. Can anybody help? Error:

![Capture](https://user-images.githubusercontent.com/9812320/75296451-11bc4d00-57e2-11ea-93fe-ee58a19c4d24.PNG)

Thank you!

**Comment by phearnot** [comment]
This is the duplicate of #2709.
