### ISSUE TITLE
[WEBSITE] Missing Waves Wallet Download

### ISSUE THREAD

**Issue by lazaridiscom** [wavesplatform/Waves#2971]
## Problem

visiting https://wavesplatform.com/

* I'm not able to find a download for a wallet.
* I'm not able to find information how to issue a token on waves

## Expected

download/information links, right on the landing page, so a visitor does not need to search around.

**Comment by msmolyakov** [comment]
You can download the wallet at Waves.Exchange website: https://waves.exchange/

How to issue a token:
1. through the Waves.Exchange wallet: https://docs.waves.exchange/en/waves-exchange/waves-exchange-online-desktop/online-desktop-asset/online-desktop-token-creation
2. for manual sending of [IssueTransaction](https://docs.wavesplatform.com/en/blockchain/transaction-type/issue-transaction) you can use client libraries in many programming languages: https://github.com/msmolyakov/awesome-waves#client-libraries

**Comment by lazaridiscom** [comment]
> You can download the wallet at Waves.Exchange website: https://waves.exchange/

A zip with an axe, then...

"Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk."

How can I point a user to such an installation?

**Comment by lazaridiscom** [comment]
> How to issue a token:
> 
>     1. through the Waves.Exchange wallet:

This is good, simple as expected.

**Comment by pivoo81** [comment]
Hello.
This is Waves repository. Your question is about Waves.Exchange
Please report their support.
