### ISSUE TITLE
API Address creation "Error is unknown"

### ISSUE THREAD

**Issue by richiedunk** [wavesplatform/Waves#2974]
Incorrect response when creating new addresses on a hub via the API {"version":"Waves v1.1.9"}

- Sending POST request to node.address/addresses
- Expected response is `{"address": "XXxxxxXXXXXxXX"}`
- Actual response is 
```
{
    "error": 0,
    "message": "Error is unknown"
}
```
- New address is shown at GET node.address/addresses, so it's being created, just getting an incorrect respose.

Any ideas?!

**Comment by msmolyakov** [comment]
Hi, @richiedunk!
Is your problem still actual? Was the node at the current height of the blockchain when you received this error?

**Comment by richiedunk** [comment]
Yes, still having the error. Node seems to be up to date.

```
{
    "blockchainHeight": 1970664,
    "stateHeight": 1970664,
    "updatedTimestamp": 1584112894157,
    "updatedDate": "2020-03-13T15:21:34.157Z"
}
```

**Comment by msmolyakov** [comment]
I spent some time to reproduce this error, but node is still correctly creating new addresses with correct response.
What messages appear in the TRACE node logs when you create an address?

How to enable TRACE logging level: https://docs.wavesplatform.com/en/waves-node/logging-configuration#configuring-own-logback-xml

**Comment by msmolyakov** [comment]
Have you tried restarting the node?
If you installed it from a deb package, then: `systemctl restart waves`

**Comment by richiedunk** [comment]
Thanks for your help. 

Tried `systemctl restart waves` and ran out of memory! Maybe something is corrupt in the Java file, or there's a memory leak of some sort. Should I try ungrading/reinstalling?

**Comment by msmolyakov** [comment]
1. Stop node: `systemctl stop waves`
2. Check Java Xmx value for the node: `cat /etc/waves/application.ini | grep Xmx`
3. Check free RAM: `free -hm`

Make sure that free RAM is greater than the Xmx value.

And check that you have enough free disk space: `df -h /`

**Comment by msmolyakov** [comment]
Did this solve the problem?

**Comment by msmolyakov** [comment]
Close due to inactivity. Feel free to reopen the issue if the problem is still not solved
