### ISSUE TITLE
[CRITICAL] Windows Defender warning about WavexExchange EXE 

### ISSUE THREAD

**Issue by lazaridiscom** [wavesplatform/Waves#2975]
(re https://github.com/wavesplatform/Waves/issues/2971#issuecomment-595673822, affects Waves Product-Management)

**Describe the bug**

"Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk."

**To Reproduce**

* Visit  https://waves.exchange/
* Menu => Download => Windows ( https://waves.exchange/files/Waves.Exchange.zip )
* Extract
* Start the exe

**Expected behavior**

I must be able to send users to the waves-platform site, so they can:

* Download an exe or msi
* Install without any warnings

**Additional context**

This about very basic product quality.

You need to fix this immediately.

**Comment by pivoo81** [comment]
Hello.
This is Waves repository. Your question is about Waves.Exchange
Please report their support.
