### ISSUE TITLE
Waves Exchange Source Codes

### ISSUE THREAD

**Issue by lazaridiscom** [wavesplatform/Waves#2976]
I'd like to have the overall tool-chain available as open-source.

Where can I find the source-code of the Waves-Exchange?

EDIT: is it this here?

https://github.com/wavesplatform/dex

**Comment by lazaridiscom** [comment]
https://github.com/wavesplatform/dex/issues

**Comment by pivoo81** [comment]
Hello.
This is Waves repository. Your question is about Waves.Exchange
Please ask their support.

**Comment by lazaridiscom** [comment]
@pivoo81 , do you actually bother to read? I'm asking for a relevant repository, within the main repository. I don't want to use non-public support.

**Comment by pivoo81** [comment]
@lazaridiscom 
https://github.com/wavesplatform/dex - this is repository for [Matcher](https://docs.wavesplatform.com/en/blockchain/glossary#matcher). The software which matches orders.
Waves.exchange uses this software.
Where to find the source code of Waves.exchange you can find out from their support.

> overall tool-chain 
I don't know what you mean by this.

**Comment by lazaridiscom** [comment]
> Where to find the source code of Waves.exchange you can find out from their support.

Seriously, you start to sound like a bot.
