### ISSUE TITLE
[PRODUCT] Sell a Token without Exposing Consumers to "WavesExchange"

### ISSUE THREAD

**Issue by lazaridiscom** [wavesplatform/Waves#2977]
I just evaluated the waves-exchange a bit, and I do not want to expose my users to this functionality.

The question is:

Can users purchase tokes in a more simple manner, e.g. an official waves-wallet, with a simple means to add funds via FIAT, and then buy waves-implemented tokens?

**Comment by pivoo81** [comment]
Hello.
This is Waves repository. Your question is about Waves.Exchange
Please report their support.

**Comment by pivoo81** [comment]
Waves Platform has no official Wallet currently.

**Comment by pivoo81** [comment]
There are several wallets developed by the community:

WavesFx
https://medium.com/waves-lab/wavesfx-a-preview-6864737b0605
https://github.com/wavesfx/wavesfx

Signature Chain
https://www.signature-chain.com/web-wallet.html

**Comment by lazaridiscom** [comment]
prototypes, or payed services (totally overprices, closed source).

You should not even mention them, makes a totally unserious impression.
