### ISSUE TITLE
https://waveswallet.io/

### ISSUE THREAD

**Issue by lazaridiscom** [wavesplatform/Waves#2979]
https://waveswallet.io/

points to

https://client.wavesplatform.com/

which points to

https://waves.exchange/

## expected

point immediately to https://waves.exchange/

**Comment by pivoo81** [comment]
Waves Platform no longer support the Client (client.wavesplatform.com)
But you can find similar functionality on Waves.Exchange, but it's separate organization, so we can't give direct link to it.

**Comment by lazaridiscom** [comment]
@pivoo81 , this starts to become annoying.

> but it's separate organization, so we can't give direct link to it.

You link DIRECTLY to it, from your client.wavesplatform.com. So, just link one instance earlier to it, to avoid sending users around on the internet.

> but it's separate organization, so we can't give direct link to it.

What does this even mean? Isn't this a product of waves?

A bit more transparency!
