### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridiscom** [wavesplatform/Waves#2980]

**Comment by pivoo81** [comment]
This repository is for Waves Protocol.
It is not about any wallet. We have no official wallet.
There is a **separate organisation Waves.Exchange** and you can ask all questions concerning Waves.Exchange in their support, or find it on their site.

**Comment by pivoo81** [comment]
We need to clarify that questions about wallets on our site and documentation.

**Comment by pivoo81** [comment]
There are several wallets developed by the community:
1. WavesFx
https://medium.com/waves-lab/wavesfx-a-preview-6864737b0605
https://github.com/wavesfx/wavesfx

2. Signature Chain
https://www.signature-chain.com/web-wallet.html

**Comment by lazaridiscom** [comment]
@pivoo81 , you are placing "waves" as an ecosystem in danger, if you continue to simply ignore what I'm writing you, and repeat like a bot the same again and again.

WavesPlatform does not function without Waves.Exchange.

Waves.Exchange is just a part of an overall problem of mine, which affects "waves". I refuse to use support-systems, I need an developer-oriented Issue-tracker.

You, as a platform central repo, MUST provide an alternative issue-tracker, so people which create assets on your platform can file issues. I refuse to use telegram, discord or other chat systems for support. This is for kids and amateurs.

> We need to clarify that questions about wallets on our site and documentation.

You need to wake up, and understand that your platform has several weaknesses, which makes you loose adopters unnecessarily.

Waves is very nice and super-easy. Make documentation and infrastructure the same easy, and waves will have more success.

## Suggestion

You could e.g. for now quick-and-dirty create a repo "dev", "For general waves developer issues, e.g. asset creation etc.", and handle dev-related issues there (even if they involve waves.exchange or whatever else popular waves tool).
