### ISSUE TITLE
no private key for sender address in wallet

### ISSUE THREAD

**Issue by graphenepay** [wavesplatform/Waves#301]
After recovering a wallet from it's BASE58 seed:

List addresses: Shows 1 single unknown address that has no balances
Verify address: Lists my address from my main wallet holding all assets

Asset transfer: **no private key for sender address in wallet**

Any solutions for this?

**Comment by wongagung** [comment]
how about the solutions ??
i have same trouble here

**Comment by metaceo01** [comment]
We haven't figured this one out jet neither.

**Comment by crashbdx** [comment]
same here... "no private key for sender address in wallet" i guess no help :/
