### ISSUE TITLE
What happened with official WUSD? https://coincodex.com/crypto/wusd/?period=ALL

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#3010]
Что у вас с долларом? 4 года 1 к 1 торговался https://coincodex.com/crypto/wusd/?period=ALL ,
а теперь внезапно - упал??? Это SCAM такой, или что?
11 тысяч ваших инвесторов - ждут от вас объяснений: https://dev.pywaves.org/assets/Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck

**Comment by pivoo81** [comment]
Hello. 
This repository is about Waves Node development. It's not connected to any Waves-based asset.
You can ask about asset its issuer - support@coinomat.com

**Comment by username1565** [comment]
This scammers just decided to close the trading of the official waves USD??? Pfff... WTF?

https://coinomat.com/
```
Notification of further services
Dear customers,

Hereby we'd like to inform you that estimated time for resuming our services is Autumn 2020. Current world state makes it nearly impossible to arrange anything due to coronavirus outbreak. In the meantime, we will put all our efforts to establish a new agreement with appropriate banks. Furthermore, to prevent speculations and additional withdrawal issues we've asked Waves.exchange to suspend trading options for cUSD and cEURO assets. The details of the resumption of services will be announced later. Thank you for your patience and understanding.
```
