### ISSUE TITLE
Make it so people CAN ACTUALLY FIND a @#$! Waves wallet. It's near IMPOSSIBLE. k tnx. Geeze.

### ISSUE THREAD

**Issue by gruvin** [wavesplatform/Waves#3029]
I give up. There's nothing in the documentation. There's nothing remotely current and obvious on the GitHub and there's nothing on your website.

Looking for a Desktop wallet AND some instructions on where to get it, how to install it and how to make it run. Closest thing I can find (macOS btw) is some "jar" file, that won't open.

WTF. Mind blown.

**Comment by pivoo81** [comment]
Hi.
There is no official wallet.

You can use 
1. Waves.Exchange app. It contains wallet. They have web, desktop and mobile versions.
https://waves.exchange/

2. Waves FX - https://github.com/wavesfx/wavesfx

**Comment by gruvin** [comment]
Well that's a seriously poor state of affairs. Oh well. Goodbye Waves. They
can keep my $40BTC. Not worth the trouble.

**Comment by pivoo81** [comment]
Here is the link with 
https://waves.tech/utilize#asset-management-dApps
