### ISSUE TITLE
[Feature] "Free sockets"! "Free sockets"!

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#3048]
**Аbstract**
>Is your feature request related to a problem? Please describe.

Yes. I cann't enable "Free Sockets", and I cann't see any description [in this guide](https://github.com/wavesplatform/waves-documentation/blob/master/ko/waves-full-node/how-to-configure-a-node.md).

**Motivation and Purposes**
>A clear and concise description of what the problem is. Ex. I'm always frustrated when [I cann't enable "Free sockets"].

**Specification**
>A clear and concise description of what you want to happen. Describe alternatives you've considered

I want to enable "Free Sockets". I see some nodes have the enabled "Free sockets" here: https://dev.pywaves.org/nodes/ and I want to enable this too, but... I cann't!

**Backwards Compatibility**
>Can your proposition affect any existing features?

No, just enable this "Free sockets", and no any affects.

**Examples and Implementation**
>Examples of implementation in other projects?

Some nodes have enabled "Free sockets" here: https://dev.pywaves.org/nodes/
So, somewhere, there is an implementation of this.

**Comment by pivoo81** [comment]
Cite @alexeykiselev from [this issue](https://github.com/wavesplatform/gowaves/issues/285):

> Free sockets at https://dev.pywaves.org/nodes/ means that a node has an available network "slots" for connections from other nodes. PyWaves service tries to establish connection to nodes network port and marks it with "yes" if succeeded. Node tries to use all available connection "slots" constantly trying to establish new connections, that's why there is so few of "yes" in the list.

**Comment by username1565** [comment]
What means "slots"? How to enable this?

**Comment by alexeykiselev** [comment]
There are two parameters in `waves/network` configuration section: [`max-inbound-connections`](https://github.com/wavesplatform/Waves/blob/1254df3cba7def132f734a8b30d76a81489f2a63/node/src/main/resources/application.conf#L70) and [`max-outbound-connections`](https://github.com/wavesplatform/Waves/blob/1254df3cba7def132f734a8b30d76a81489f2a63/node/src/main/resources/application.conf#L73) that define the number of connections that node establishes.

**Comment by username1565** [comment]
Hi, @alexeykiselev!
I have the default values 30 for this parameters, but https://dev.pywaves.org/nodes/ show "Free Sockets": "-" for my node.

So, how to enable "Free Sockets"??

**Comment by alexeykiselev** [comment]
Set both values to number more than number of nodes on the network. This will give your node the free sockets status on PyWaves.

**Comment by username1565** [comment]
Ok, thanks. I got it. This seems, like a "Super-Node"!
