### ISSUE TITLE
Compile the node.

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#3082]
Hello.
How to compile this `scala`-code of the waves node into `.jar`-file on `Windows`.
What need to download to build this from the source code? Some binaries and modules?..
I want to be sure the source code is corresponding the binary files, and there is no any viruses.
Do you have any instructions to compile this all?

And... Is this possible to compile this code for all versions, and into x86-node, as binary file for win32,
for example, to run the node even on the Windows XP.

**Comment by username1565** [comment]
Как сконпелировать, блядь, это скамное говно?

**Comment by pivoo81** [comment]
@username1565 please be calm and constructive, or you will be blocked.

Concerning your original question - the answer will be given soon today.

**Comment by msmolyakov** [comment]
Instructions with all the necessary commands are in the [readme](/wavesplatform/Waves#-development)
