### ISSUE TITLE
Node Synchronization stuck on this block 1964603.

### ISSUE THREAD

**Issue by osiz-blockchainapp** [wavesplatform/Waves#3127]
Hi,
I configure waves full node in AWS. The node synchronization was stopped on this block 1964603 then again restarted the waves node service then the node was not started to synchronized but it throws below error.
Error:
`WARN c.w.s.a.ExtensionAppender$ - Can't process fork starting with 4B5eZheiVAxMfpkwPgLKYzTe5j9LHyAet4jLWFwgkVjAGGsTgqBz6Nf2z1VJqusQqonKQPmeX86VyJTcMuGqXkQq, error appending block Block(FMi3E8S8tfzgsp2zUUA15pBbFCAKxXfT2WA7sjw1a6TM21wz8hgWDyE6MkLntFCv4pkdBy7CGnzS67WwW5CsjFn -> 4B5eZhe..., txs=75, features=Set(), rewardVote=600000000): GenericError(Block Block(FMi3E8S8tfzgsp2zUUA15pBbFCAKxXfT2WA7sjw1a6TM21wz8hgWDyE6MkLntFCv4pkdBy7CGnzS67WwW5CsjFn -> 4B5eZhe..., txs=75, features=Set(), rewardVote=600000000) is invalid: Block time 1583754581413 less than expected)`

Then I was upgraded waves node to this version (waves_1.1.10_all.deb) then again restarted waves node service but again getting the same error.
I take back up of node configuration file then removed all the old data of waves node after that i started node synchronization from scratch but still am receiving same error can you please help me to solve this issue. here attached screen short.
![Screenshot 2020 05 19 at 5 50 53 PM png PNG Image 1440%A0×%A0550 pixels ](https://user-images.githubusercontent.com/48212011/82525101-3eb49d80-9b4e-11ea-957d-8d3aaa79a99b.png)

**Comment by phearnot** [comment]
Data corruption in LevelDB has been fixed in [1.1.11](https://github.com/wavesplatform/Waves/releases/tag/v1.1.11). Please update your node and check state as described in the release notes.
