### ISSUE TITLE
maxConnections is not being respected on some nodes

### ISSUE THREAD

**Issue by bcdev-** [wavesplatform/Waves#32]
I have 4 nodes running Release0 v0.2.3-SNAPSHOT that have specified "maxConnections": 20, but have > 45 nodes connected to them. [checked using /peers/connected API]

Most of these connections are inbound, only few are outbound. Is this intentional?

**Comment by asolovyov** [comment]
It is better to restrict inbound and outbound connections in sum - it is p2p after all...
Very likely will be a part of the next release.

Thanks

**Comment by asolovyov** [comment]
Fixed in [Release 0.2.4]https://github.com/wavesplatform/Waves/releases/tag/v0.2.4)
