### ISSUE TITLE
Help with my node update please

### ISSUE THREAD

**Issue by Praexor** [wavesplatform/Waves#3241]
I was updating my node to version 1.2.10 and it gives me this error, it does not start :( 
 ****ERROR c.w.h.StorageFactory$ - Storage version 4 is not compatible with expected version 5!****
PLEASE HELP

My server : 4 GB Memory / 80 GB Disk / TOR1 - Debian 10.2 x64

I used 
1.- sudo systemctl stop waves
2.- wget https://github.com/wavesplatform/Waves/releases/download/v1.2.10/waves_1.2.10_all.deb
3.- sudo dpkg -i waves_1.2.10_all.deb

Result 

● waves.service - Waves node
   Loaded: loaded (/lib/systemd/system/waves.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-08-17 19:08:57 UTC; 8min ago
  Process: 8576 ExecStart=/usr/share/waves/bin/waves -Dlogback.file.directory=/var/log/waves -Dlogback.pattern=%-5level %logger{26} - %m
 Main PID: 8576 (code=exited, status=38)

Aug 17 19:08:49 waves-node-sucre waves[8576]: INFO  c.w.Application$ - Starting...
Aug 17 19:08:49 waves-node-sucre waves[8576]: INFO  c.wavesplatform.utils.NTP - Initializing time
Aug 17 19:08:50 waves-node-sucre waves[8576]: INFO  a.event.slf4j.Slf4jLogger - Slf4jLogger started
Aug 17 19:08:50 waves-node-sucre waves[8576]: INFO  c.w.Application$ - Waves v1.2.10 Blockchain Id: W
Aug 17 19:08:50 waves-node-sucre waves[8576]: INFO  c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory wi
Aug 17 19:08:56 waves-node-sucre waves[8576]: INFO  c.w.n.PeerDatabaseImpl - Loaded 171 known peer(s) from peers.dat
Aug 17 19:08:57 waves-node-sucre waves[8576]: ERROR c.w.h.StorageFactory$ - Storage version 4 is not compatible with expected version 5!
Aug 17 19:08:57 waves-node-sucre waves[8576]: ERROR c.w.h.StorageFactory$ - FOR THIS REASON THE NODE STOPPED AUTOMATICALLY
Aug 17 19:08:57 waves-node-sucre systemd[1]: waves.service: Main process exited, code=exited, status=38/n/a
Aug 17 19:08:57 waves-node-sucre systemd[1]: waves.service: Failed with result 'exit-code'.

Regards

**Comment by msmolyakov** [comment]
As said in the [Release Notes](https://github.com/wavesplatform/Waves/releases/tag/v1.2.10) in the section `"Update Notes`, you need to rebuild state of your node.

Please, follow the instructions.

**Comment by Praexor** [comment]
> 
> 
> As said in the [Release Notes](https://github.com/wavesplatform/Waves/releases/tag/v1.2.10) in the section `"Update Notes"`, you need to rebuild state of your node.
> 
> Please, follow the instructions.

Ok great, thank you guys, I'll try it, regards

**Comment by msmolyakov** [comment]
@Praexor have you successfully updated the node?

**Comment by Praexor** [comment]
> @Praexor have you successfully updated the node?

No yet, I am looking for help

**Comment by msmolyakov** [comment]
please describe your steps and what error you get

**Comment by msmolyakov** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
