### ISSUE TITLE
Is there any way to see last transactions, including exchanged, by asset ID?

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#3248]
Is there any way to see last trades by asset ID?

**Comment by msmolyakov** [comment]
You can use Data Service API: https://api.wavesplatform.com/v0/docs/#/transactions/searchTxsExchange

Repository of this project: https://github.com/wavesplatform/data-service

**Comment by username1565** [comment]
I mean when `PriceAsset` or `AmountAsset` is `unknown`. Because `Waves DEX` - this is a `DEX`,
and if noone not trading by the SPECIFIED `trading pairs`,
somewhere through another `matcher`,
there is possible to trade `specified asset`, for another `unknown asset`,
and all `exchange-transactions`, are including in blockchain.

So, I think, there is possible to make some services, where by `Asset ID`,
anyone can see full list or last-transactions, including the `exchange transactions`, and those `unknown Asset`-id,
if trading was been processed, somewhere else.
I just leave this here, as future-request.

**Comment by username1565** [comment]
I mean when `PriceAsset` or `AmountAsset` is `unknown`. Because `Waves DEX` - this is a `DEX`,
and if noone not trading by the SPECIFIED `trading pairs`,
somewhere through another `matcher`,
there is possible to trade `specified asset`, for another `unknown asset`,
and all `exchange-transactions`, are including in blockchain.

So, I think, there is possible to make some services, where by `Asset ID`,
anyone can see full list or last-transactions, including the `exchange transactions`, and those `unknown Asset`-id,
if trading was been processed, somewhere else.
I just leave this here, as future-request.

**Comment by username1565** [comment]
I mean when `PriceAsset` or `AmountAsset` is `unknown`. Because `Waves DEX` - this is a `DEX`,
and if noone not trading by the SPECIFIED `trading pairs`,
somewhere through another `matcher`,
there is possible to trade `specified asset`, for another `unknown asset`,
and all `exchange-transactions`, are including in blockchain.

So, I think, there is possible to make some services, where by `Asset ID`,
anyone can see full list or last-transactions, including the `exchange transactions`, and those `unknown Asset`-id,
if trading was been processed, somewhere else.
I just leave this here, as future-request.

**Comment by username1565** [comment]
I mean when `PriceAsset` or `AmountAsset` is `unknown`. Because `Waves DEX` - this is a `DEX`,
and if noone not trading by the SPECIFIED `trading pairs`,
somewhere through another `matcher`,
there is possible to trade `specified asset`, for another `unknown asset`,
and all `exchange-transactions`, are including in blockchain.

So, I think, there is possible to make some services, where by `Asset ID`,
anyone can see full list or last-transactions, including the `exchange transactions`, and those `unknown Asset`-id,
if trading was been processed, somewhere else.
I just leave this here, as future-request.

**Comment by username1565** [comment]
I mean when `PriceAsset` or `AmountAsset` is `unknown`. Because `Waves DEX` - this is a `DEX`,
and if noone not trading by the SPECIFIED `trading pairs`,
somewhere through another `matcher`,
there is possible to trade `specified asset`, for another `unknown asset`,
and all `exchange-transactions`, are including in blockchain.

So, I think, there is possible to make some services, where by `Asset ID`,
anyone can see full list or last-transactions, including the `exchange transactions`, and those `unknown Asset`-id,
if trading was been processed, somewhere else.
I just leave this here, as future-request.

**Comment by username1565** [comment]
I mean when `PriceAsset` or `AmountAsset` is `unknown`. Because `Waves DEX` - this is a `DEX`,
and if noone not trading by the SPECIFIED `trading pairs`,
somewhere through another `matcher`,
there is possible to trade `specified asset`, for another `unknown asset`,
and all `exchange-transactions`, are including in blockchain.

So, I think, there is possible to make some services, where by `Asset ID`,
anyone can see full list or last-transactions, including the `exchange transactions`, and those `unknown Asset`-id,
if trading was been processed, somewhere else.
I just leave this here, as future-request.

**Comment by username1565** [comment]
I mean when `PriceAsset` or `AmountAsset` is `unknown`. Because `Waves DEX` - this is a `DEX`,
and if noone not trading by the SPECIFIED `trading pairs`,
somewhere through another `matcher`,
there is possible to trade `specified asset`, for another `unknown asset`,
and all `exchange-transactions`, are including in `blockchain`.

So, I think, there is possible to make some services, where by `Asset ID`,
anyone can see full list or last-transactions, including the `exchange transactions`, and those unknown `Asset-id`,
if trading was been processed, somewhere else.
I just leave this here, as `future-request`.
