### ISSUE TITLE
Publick key

### ISSUE THREAD

**Issue by ShawnShoper** [wavesplatform/Waves#3264]
Hi, we upgrade the waves to lastest.
when we call `calcfee` api, the throw error,`content={"error":199,"message":"requirement failed: invalid public key length: 0"}`,
But i do not found  how to get `public key`

**Comment by msmolyakov** [comment]
Hi. Please check that json of your request body contains field `"senderPublicKey"` with correct value

**Comment by ShawnShoper** [comment]
Json body, 
```
{
type:4
sender:xxxx,
recipient:xxx,
amount:10000
fee:1000
senderPublicKey:""
}
```
I fill empty value for publick key, the old wallet version,can pass it .  But we upgrade to lastest version,it's wrong.   and i see the docs. No API was found to get the public key for the account

**Comment by ShawnShoper** [comment]
@msmolyakov Can u help me

**Comment by msmolyakov** [comment]
It's impossible to calculate its public key from the address. `"senderPublicKey"` field is required, but `"sender"` isn't.

**Comment by ShawnShoper** [comment]
umm,I can't get `senderPublicKey` from the address creation to the transfer. How should I do, how can i get the `publickey`

**Comment by past2017** [comment]
> It's impossible to calculate its public key from the address. `"senderPublicKey"` field is required, but `"sender"` isn't.

so is there an API or another way to get senderPublicKey for one address? @msmolyakov

**Comment by msmolyakov** [comment]
If account owner has its seed phrase or private key, he can calculate public key from them. There're [client libraries](https://github.com/msmolyakov/awesome-waves/blob/master/README.md#client-libraries) for many programming languages that can do it for you.

Please read this article for more details: https://medium.com/wavesprotocol/protect-your-funds-public-private-keys-and-seed-phrases-c52fe4c46fbf

**Comment by ShawnShoper** [comment]
Thanks.
