### ISSUE TITLE
config error with after upgrading to v1.2.13

### ISSUE THREAD

**Issue by jadechip** [wavesplatform/Waves#3280]
**Describe the bug**
After having upgraded the node to verseion 1.2.13 on Debian, I get the following error:
```
Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: waves.blockchain.type has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
	at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:459)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:183)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at com.wavesplatform.settings.package$.loadConfig(package.scala:71)
	at com.wavesplatform.Application$.loadApplicationConfig(Application.scala:495)
	at com.wavesplatform.Application$.startNode(Application.scala:572)
	at com.wavesplatform.Application$.main(Application.scala:566)
	at com.wavesplatform.Application.main(Application.scala)
```
I have verified that I am passing all required variables to the config file.

Please advise.

**To Reproduce**
1. Upgrade node to version v1.2.13
2. Start the node, here is how I am doing it:
```
CMD java -XX:+ExitOnOutOfMemoryError \
    -Dconfig.override_with_env_vars=true \
    -jar waves.jar config.conf
```

**Expected behavior**
Node should start successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: openjdk:11-jre-slim (running inside EKS cluster)
 - Version v1.2.13

**Additional context**

**Comment by msmolyakov** [comment]
Please make sure:
- in the run command the path to `config.conf` file is correct
- `config.conf` exists in the specified path
- `config.conf` has property `waves.blockchain.type` and it has one of the values: `MAINNET`, `TESTNET`, `STAGENET` or `CUSTOM`

**Comment by vbonini** [comment]
Hello. I'm working with @jadechip to troubleshoot this node issue, and we confirmed each of those points with our deployment. 

- `config.conf` is in the top-level folder with the the jar file. We've also specified `./config.conf` in our command.
- `cat` the config shows the appropriate data with our wallet changes. This unmodified config worked with previous `waves` versions.
- `config.conf` is owned by the user running the command. We also changed to `chmod 777` which was unsuccessful. 
- Our config indeed has the `waves.blockchain.type` value of `MAINNET`.

```
waves {
...
  # Blockchain settings
  blockchain {
    # Blockchain type. Could be TESTNET | MAINNET | CUSTOM. Default value is TESTNET.
    type = 'MAINNET'
...
  }
...
}
include "deprecated-settings.conf"
```

If we deploy v1.2.12 with the same config, it works without issue.

**Comment by msmolyakov** [comment]
> `type = 'MAINNET'`

Node config uses [HOCON](https://github.com/lightbend/config#using-hocon-the-json-superset) format.

In HOCON, string values could be defined in double quotes `"`, or unquoted or as substitution `${someVar}`.\
But single quotes `'` become part of the value.

Try to change the `'MAINNET'` value to `"MAINNET"` or `MAINNET`. And also replace other values with single quotes, if any.

**Comment by vbonini** [comment]
Thank you. I actually complicated this ticket by not mentioning that we originally used env var `type = ${BLOCKCHAIN_TYPE}` in our config, but that no longer works with the new update. Then I tried `'MAINNET'`. And then you pointed me in the right direction. 

I got it working with `"MAINNET"` as you directed. After some testing, here are my results.

```
type = ...
${BLOCKCHAIN_TYPE} - doesn't work
'${BLOCKCHAIN_TYPE}' - doesn't work
"${BLOCKCHAIN_TYPE}" - doesn't work

MAINNET - works
"MAINNET" - works
'MAINNET' - doesn't work
```

Ideally we would use the env var to set the type, but this will work for now. This might be a bug and would require further testing from you guys. 

For now, we will move on.

**Comment by msmolyakov** [comment]
Btw, if you use a node in docker and want to set blockchain type as env variable, then perhaps this image will be quite convenient: https://hub.docker.com/r/wavesplatform/wavesnode

It accepts blockchain type as `WAVES_NETWORK=mainnet` env variable.
