### ISSUE TITLE
ERROR: 18:28:45,568 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform com.protonail.leveldb.jna.LevelDBException: IO error: /root/.local/share/waves-testnet/data: Invalid argument

### ISSUE THREAD

**Issue by swatim2020** [wavesplatform/Waves#3341]
I want to fork the waves blockchain in which I wanted to change the coin. I first change the name of coin in waves node

link : https://github.com/wavesplatform/Waves/blob/version-1.2.x/node/src/main/scala/com/wavesplatform/transaction/assets/exchange/AssetPair.scala

according to the link I deployed on windows and I got this error.

ERROR: 18:28:45,568 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform com.protonail.leveldb.jna.LevelDBException: IO error: /root/.local/share/waves-testnet/data: Invalid argument

(note : full error is given below)

software details:

  1. openjdk11
  2. ubuntu 18.04LTS
I am deploying in windows through ubuntu 18.04LTS by following steps for installing in windows and installing deb file.

link for installing: https://docs.waves.tech/en/waves-node/how-to-install-a-node/on-windows

command: java -jar node/target/waves-all-1.2.15-DIRTY.jar node/target/classes/application.conf

I got error while initializing it with wavesplatform.

root@WJLP-1220:/mnt/c/Users/swatim/Desktop/wavesProject/Waves/node/target# java -jar waves-all-1.2.15-DIRTY.jar classes/application.conf 2021-01-04 18:28:44,524 INFO [main] c.w.Application$ - Starting... 2021-01-04 18:28:45,082 INFO [ctor.default-dispatcher-4] a.event.slf4j.Slf4jLogger - Slf4jLogger started 2021-01-04 18:28:45,193 INFO [main] c.w.Application$ - Waves v1.2.15-DIRTY Blockchain Id: T 2021-01-04 18:28:45,271 INFO [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@72ba28ee 2021-01-04 18:28:45,568 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform com.protonail.leveldb.jna.LevelDBException: IO error: /root/.local/share/waves-testnet/data: Invalid argument at com.protonail.leveldb.jna.LevelDBNative.checkError(LevelDBNative.java:295) at com.protonail.leveldb.jna.LevelDB.(LevelDB.java:16) at com.wavesplatform.database.jna.LevelDBJNADBFactory.openJnaDatabase(LevelDBJNADBFactory.scala:11) at com.wavesplatform.database.jna.LevelDBJNADBFactory.open(LevelDBJNADBFactory.scala:15) at com.wavesplatform.database.package$.openDB(package.scala:51) at com.wavesplatform.Application.(Application.scala:69) at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:558) at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:555) at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25) at com.wavesplatform.Application$.startNode(Application.scala:555) at com.wavesplatform.Application$.main(Application.scala:524) at com.wavesplatform.Application.main(Application.scala)

**Comment by DrBlast** [comment]
Changing coin name in AssetPair file is not enough. You can see coin name only in exchange tx, in other txs you should use null as assetID.
You cal contact with [BlackTurtle](https://www.blackturtle.eu/) , he forked waves blockchain
