### ISSUE TITLE
Exception when compiling 171 sources to classes

### ISSUE THREAD

**Issue by viraladmin** [wavesplatform/Waves#3342]
Error Occurs on Ubuntu 18.08 when attempting to manually compile. Specifically when issuing the command:

`sbt checkPR`

Errors were way to long for a post so I created a pastebin.

Errors pastebin: [https://pastebin.com/fTNJjAQW](https://pastebin.com/fTNJjAQW)

**Comment by viraladmin** [comment]
So I tested this with java 1.8, 1.9 and 1.11 All three had errors with `sbt checkPR`. I also tried with version 1.2.x and 1.3x both had issues. 

With 1.8 I end up getting an 

java.lang.OutOfMemoryError: Java heap space 

It still seemed to compile okay when I did a `sbt packageAll`

**Comment by DrBlast** [comment]
sbt checkPR - compile and run unit tests. It's not enought mem to run unit tests on our server
You can compile sources without tests using  sbt packageAll
