### ISSUE TITLE
Change first character

### ISSUE THREAD

**Issue by viraladmin** [wavesplatform/Waves#3343]
How do I change the first character of the wallet address? This seems to be the only thing I havn't been able to find anywhere in the code.

**Comment by DrBlast** [comment]
First two bytes of address is address version and chain id. For you custom blockchain you should set your own chainid:
https://docs.waves.tech/en/waves-node/private-waves-network#setup-jar-node-with-custom-blockchain
network-type in genesis.conf is you chain id
