### ISSUE TITLE
Fatal error when deploying waves on Bitvise client SSH. 

### ISSUE THREAD

**Issue by swatim15** [wavesplatform/Waves#3344]
Hello, I tried to deploy Waves blockchain locally with the help of waves documentation.
link for installing: [https://docs.waves.tech/en/waves-node/how-to-build-and-test-a-node](https://docs.waves.tech/en/waves-node/how-to-build-and-test-a-node)

After installing deb file and run which jar file, i got the error : "Fatal error in channel, terminating application
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer"

And chain is terminated after getting start. Its working fine locally but have some issues while deploying on Bitvise SSH client.

![image](https://user-images.githubusercontent.com/73603669/104086259-2f40ac80-5224-11eb-9d0f-267ee3ccf336.png)
![image](https://user-images.githubusercontent.com/73603669/104086266-41bae600-5224-11eb-84d5-22749d5ec72f.png)

can anyone please help?

**Comment by viraladmin** [comment]
I would recommend checking your java version. It needs to be 1.8. 

`java -version`

If its the wrong version see if you have `update-java-alternatives` installed and if not install it and use it to switch java versions.

**Comment by swatim2020** [comment]
> I would recommend checking your java version. It needs to be 1.8.
> 
> `java -version`
> 
> If its the wrong version see if you have `update-java-alternatives` installed and if not install it and use it to switch java versions.

Its same 1.8.0 java version and it is working fine on locally but giving issues when i try to deploy it on cloud Ubuntu server(Bitvise SSH Client).

**Comment by DrBlast** [comment]
How do you build jar? Error in stake trace occurs if you use 1.11 compiler
If you installed deb you should start node as service, not as jar

**Comment by DrBlast** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
