### ISSUE TITLE
Understanding Base Target?

### ISSUE THREAD

**Issue by viraladmin** [wavesplatform/Waves#3356]
When I setup my own custom network, the baseTarget seems to always get exponentially larger - in fact so much so that it ends up breaking things like the block explorer if it gets to large (issue of a number being to large as its not set as a string type). 

Yet when I look at the baseTarget on nodes.wavesplatform.com that number is always less than 100. How does waves keep the baseTarget low without affecting the earnings of nodes? 

Could someone please help me understand this. There is not much in the docs about the baseTarget other than it relating to difficulty.

**Comment by DrBlast** [comment]
In version [1.2.x](https://github.com/wavesplatform/Waves/tree/version-1.2.x) (not released yet) we implemented  new mechanism of genesis block generation. Now you do not need to calc base target yourself. Base target will be calculated automatically. Base target depends on genesis block timestamp and initial balance.

**Comment by viraladmin** [comment]
I'm on the 2.17 release at the moment Would be helpful to understand how basetarget currently works - or more to the point how waves keeps the target base so low. Otherwise I will have to roll a new chain when 2.x (which is weird to say seeing as 2.x implies any version 2 and I am on 2.17) releases and then roll a new chain and merge old to new.

**Comment by DrBlast** [comment]
https://docs.wavesenterprise.com/en/latest/how-the-platform-works/consensus/PoS.html

**Comment by DrBlast** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
