### ISSUE TITLE
How to use 100 million Wave Tokens which are already distributed while creating genesis block in custom network?

### ISSUE THREAD

**Issue by swatim2020** [wavesplatform/Waves#3365]
I am working on Waves Blockchain. I have created my testnet network locally and distributed the 100 million tokens in 5 different accounts locally. But the problem is that I am not able to use them because it starts from genesis block and I am not able to transfer them into a new account.

In original waves, it uses dex application to exchange into waves or from waves to the different token. and one more thing in testnet it buys tokens from the faucet.

Note: For genesis block and address where token distribution is done is automatic. In code, only public addresses are given and genesis block signature.

Procedure how network starts:

1.   create database
2.   generate the genesis block with distribution
3.   create a new wallet
4.   set the network and peers

code:- 

```
it should "read testnet settings" in {
    val config   = loadConfig(ConfigFactory.parseString("""waves {
        |  directory = "/waves"
        |  data-directory = "/waves/data"
        |  blockchain {
        |    type = TESTNET
        |  }
        |}""".stripMargin))
    val settings = BlockchainSettings.fromRootConfig(config)
    settings.addressSchemeCharacter should be('T')
    settings.functionalitySettings.generationBalanceDepthFrom50To1000AfterHeight should be(0)
    settings.functionalitySettings.blockVersion3AfterHeight should be(161700)
    settings.functionalitySettings.maxTransactionTimeBackOffset should be(120.minutes)
    settings.functionalitySettings.maxTransactionTimeForwardOffset should be(90.minutes)
    settings.rewardsSettings.initial should be(600000000)
    settings.rewardsSettings.minIncrement should be(50000000)
    settings.rewardsSettings.term should be(100000)
    settings.rewardsSettings.votingInterval should be(10000)
    settings.genesisSettings.blockTimestamp should be(1460678400000L)
    settings.genesisSettings.timestamp should be(1478000000000L)
    settings.genesisSettings.signature should be(    ByteStr.decodeBase58("5uqnLK3Z9eiot6FyYBfwUnbyid3abicQbAZjz38GQ1Q8XigQMxTK4C1zNkqS1SVw7FqSidbZKxWAKLVoEsp4nNqa").toOption
    )
    settings.genesisSettings.initialBalance should be(10000000000000000L)
    settings.genesisSettings.transactions should be(
      Seq(
        GenesisTransactionSettings("3My3KZgFQ3CrVHgz6vGRt8687sH4oAA1qp8", 400000000000000L),
        GenesisTransactionSettings("3NBVqYXrapgJP9atQccdBPAgJPwHDKkh6A8", 200000000000000L),
        GenesisTransactionSettings("3N5GRqzDBhjVXnCn44baHcz2GoZy5qLxtTh", 200000000000000L),
        GenesisTransactionSettings("3NCBMxgdghg4tUhEEffSXy11L6hUi6fcBpd", 200000000000000L),
        GenesisTransactionSettings("3N18z4B8kyyQ96PhN5eyhCAbg4j49CgwZJx", 9000000000000000L)
      )
    )   }
```

**Comment by viraladmin** [comment]
Well seeing as you are talking about genesis block, this is not really the waves testnet. Its a local testnet of your own genesis. When you create a genesis block, you don't define the addresses, you set the seeds and the wallets are automatically generated for you based on those seeds. In your genesis creation config you would do something like

```
genesis-generator {
  network-type: "T"  #your custom network identifier byte
  initial-balance: 10000000000000  #initial balance to be created by genesis
  base-target: 136951653 #the initial complexity parameter
  average-block-delay: 60s #average block delay
  distributions {
    wallet1 {
      seed-text: "seed used to generate address 1"
      nonce: 0
      amount: 1000000000 #amount to send to address
    }
    wallet2 {
      seed-text: "seed used to generate address 2"
      nonce: 0
      amount: 1000000000 #amount to send to address
    }
  }
}
```

All the wallets combined should equal the value you define in initial-balance. 

HOWEVER I am not sure this is actually what you are referring to and think there may be some terminology mix up taking place. When you create a genesis block, you are creating a new chain, not working off the waves testnet nor mainnet. As such it works on a new currency, not tokens. 

If you are working from testnet, that would mean you did NOT roll your own genesis block. Instead you setup a node and connected it to the waves test network. This is done merely through the node configuration file. 

I recommend reviewing https://docs.waves.tech/en/waves-node/private-waves-network
and https://docs.waves.tech/en/waves-node/node-configuration

**Comment by DrBlast** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
