### ISSUE TITLE
Ubuntu waves_1.2.17_all.deb install gives an error

### ISSUE THREAD

**Issue by EminBudak** [wavesplatform/Waves#3370]
btr@bt1-xl:~/waves$ **sudo dpkg -i waves_1.2.17_all.deb**
(Reading database ... 94457 files and directories currently installed.)
Preparing to unpack waves_1.2.17_all.deb ...
dpkg: error processing archive waves_1.2.17_all.deb (--install):
 **conffile name 'usr/share/waves/conf/application.ini' is not an absolute pathname**
Errors were encountered while processing:
 waves_1.2.17_all.deb

Ubuntu 20

**Comment by DrBlast** [comment]
I've tried to install deb on in docker with  ubuntu  20.04 
`root@333219a8b410:/# dpkg -i waves_1.2.17_all.deb
(Reading database ... 5964 files and directories currently installed.)
Preparing to unpack waves_1.2.17_all.deb ...
Unpacking waves (1.2.17) over (1.2.17) ...
Setting up waves (1.2.17) ...
/var/lib/dpkg/info/waves.postinst: 61: /sbin/init: not found
/var/lib/dpkg/info/waves.postinst: 61: /sbin/init: not found
...`
Deb installed fine without errors. We need more information about your server configuration to investigate your issue.

**Comment by DrBlast** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
