### ISSUE TITLE
Testnet fails to deserialize block 1413341

### ISSUE THREAD

**Issue by djpnewton** [wavesplatform/Waves#3376]
>java.lang.RuntimeException: Too large proof (65), must be max 64 bytes
>...
>c.w.a.h.CompositeHttpService - HTTP 500 Internal Server Error from GET http://localhost:6869/blocks/at/141334

See also: https://testnet.wavesexplorer.com/blocks/1413341

**Comment by DrBlast** [comment]
fixed in release 1.2.18.
You should rebuild state to set your node to right chain
