### ISSUE TITLE
Endpoints answering with swagger ui source code

### ISSUE THREAD

**Issue by jansenmarc** [wavesplatform/Waves#34]
the following endpoints answer with the swagger ui itself (it’s source code) if you enter negative numbers as inputs:

http://<node>/addresses/seq/123123123/-123123125  
http://<node>/blocks/at/-123123123123123123
http://<node>/blocks/seq/-1212/10
http://<node>/debug/state/-123
http://<node>/debug/blocks/-121231231
http://<node>/transactions/address/3Mvtz6QNaxBgS2o8nBkJLhaeDKE38U8V68Y/limit/12123123123

**Comment by gagarin55** [comment]
All urls are invalid. Its ok.

**Comment by gagarin55** [comment]
fixed in https://github.com/wavesplatform/Scorex/commit/1962d854df2f714afaf2103854f8c378e316e99f
Now request to invalid url response with 404
