### ISSUE TITLE
Can not find waves-all*.jar in 1.2.20 waves docker image

### ISSUE THREAD

**Issue by lcgogo** [wavesplatform/Waves#3415]
**Describe the bug**
Can not find waves-all*.jar in 1.2.20 waves docker image

In https://github.com/wavesplatform/Waves/blob/master/docker/Dockerfile
line 65
COPY --from=builder /waves/node/target/waves-all-*.jar /usr/share/waves/lib/

**To Reproduce**
1. docker pull wavesplatform/wavesnode:1.2.20
2. docker run -it --entrypoint "/bin/sh" wavesplatform/wavesnode:1.2.20
# cd /usr/share/waves/lib/
# ls
ch.obermuhlner.big-math-2.1.0.jar
ch.qos.logback.logback-classic-1.2.3.jar
ch.qos.logback.logback-core-1.2.3.jar
com.chuusai.shapeless_2.13-2.3.3.jar
com.fasterxml.jackson.core.jackson-annotations-2.11.0.jar
com.fasterxml.jackson.core.jackson-core-2.11.0.jar
com.fasterxml.jackson.core.jackson-databind-2.11.0.jar
com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.10.4.jar
com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.10.4.jar
com.github.oshi.oshi-core-4.2.1.jar
com.github.scopt.scopt_2.13-4.0.0-RC2.jar
com.github.spullara.mustache.java.compiler-0.9.5.jar
com.google.android.annotations-4.1.1.4.jar
com.google.api.grpc.proto-google-common-protos-1.12.0.jar
com.google.code.findbugs.jsr305-3.0.2.jar
com.google.code.gson.gson-2.8.6.jar
com.google.errorprone.error_prone_annotations-2.2.0.jar
com.google.guava.failureaccess-1.0.1.jar
com.google.guava.guava-27.0.1-jre.jar
com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
com.google.j2objc.j2objc-annotations-1.1.jar
com.google.protobuf.protobuf-java-3.10.0.jar
com.iheart.ficus_2.13-1.4.7.jar
com.lihaoyi.fastparse_2.13-2.2.4.jar
com.lihaoyi.geny_2.13-0.5.1.jar
com.lihaoyi.sourcecode_2.13-0.2.1.jar
com.softwaremill.sttp.core_2.13-1.6.4.jar
com.squareup.moshi.moshi-1.5.0.jar
com.squareup.okhttp3.logging-interceptor-3.11.0.jar
com.squareup.okhttp3.okhttp-3.11.0.jar
com.squareup.okio.okio-1.14.0.jar
com.squareup.retrofit2.converter-moshi-2.4.0.jar
com.squareup.retrofit2.retrofit-2.4.0.jar
com.thesamet.scalapb.lenses_2.13-0.9.0.jar
com.thesamet.scalapb.scalapb-json4s_2.13-0.9.3.jar
com.thesamet.scalapb.scalapb-runtime-grpc_2.13-0.9.0.jar
com.thesamet.scalapb.scalapb-runtime_2.13-0.9.0.jar
com.thoughtworks.paranamer.paranamer-2.8.jar
com.typesafe.akka.akka-actor_2.13-2.6.4.jar
com.typesafe.akka.akka-http-core_2.13-10.1.12.jar
com.typesafe.akka.akka-http_2.13-10.1.12.jar
com.typesafe.akka.akka-parsing_2.13-10.1.12.jar
com.typesafe.akka.akka-protobuf-v3_2.13-2.6.4.jar
com.typesafe.akka.akka-slf4j_2.13-2.6.4.jar
com.typesafe.akka.akka-stream_2.13-2.6.4.jar
com.typesafe.config-1.3.3.jar
com.typesafe.play.play-functional_2.13-2.9.0.jar
com.typesafe.play.play-json_2.13-2.9.0.jar
com.typesafe.scala-logging.scala-logging_2.13-3.9.2.jar
com.typesafe.ssl-config-core_2.13-0.4.1.jar
com.wavesplatform.curve25519-java-0.6.4.jar
com.wavesplatform.grpc-server-1.2.20.jar
com.wavesplatform.lang-1.2.20.jar
com.wavesplatform.leveldb-jna.leveldb-jna-core-1.22.3.jar
com.wavesplatform.leveldb-jna.leveldb-jna-native-1.22.3.jar
com.wavesplatform.waves-1.2.20.jar
com.wavesplatform.zwaves-0.1.0-SNAPSHOT.jar
com.wavesplatform.zwaves-bn256-0.1.5-SNAPSHOT.jar
commons-net.commons-net-3.6.jar
io.circe.circe-core_2.13-0.13.0.jar
io.circe.circe-generic_2.13-0.13.0.jar
io.circe.circe-jawn_2.13-0.13.0.jar
io.circe.circe-numbers_2.13-0.13.0.jar
io.circe.circe-parser_2.13-0.13.0.jar
io.grpc.grpc-api-1.35.0.jar
io.grpc.grpc-context-1.35.0.jar
io.grpc.grpc-core-1.35.0.jar
io.grpc.grpc-netty-1.35.0.jar
io.grpc.grpc-protobuf-1.21.0.jar
io.grpc.grpc-protobuf-lite-1.21.0.jar
io.grpc.grpc-stub-1.21.0.jar
io.kamon.kamon-core_2.13-2.1.0.jar
io.kamon.kamon-influxdb_2.13-2.1.0.jar
io.kamon.kamon-system-metrics_2.13-2.1.0.jar
io.monix.implicitbox_2.13-0.2.0.jar
io.monix.monix-catnap_2.13-3.3.0.jar
io.monix.monix-eval_2.13-3.3.0.jar
io.monix.monix-execution_2.13-3.3.0.jar
io.monix.monix-internal-jctools_2.13-3.3.0.jar
io.monix.monix-reactive_2.13-3.3.0.jar
io.netty.netty-buffer-4.1.59.Final.jar
io.netty.netty-codec-4.1.59.Final.jar
io.netty.netty-codec-http-4.1.52.Final.jar
io.netty.netty-codec-http2-4.1.52.Final.jar
io.netty.netty-codec-socks-4.1.52.Final.jar
io.netty.netty-common-4.1.59.Final.jar
io.netty.netty-handler-4.1.59.Final.jar
io.netty.netty-handler-proxy-4.1.52.Final.jar
io.netty.netty-resolver-4.1.59.Final.jar
io.netty.netty-transport-4.1.59.Final.jar
io.perfmark.perfmark-api-0.23.0.jar
net.java.dev.jna.jna-5.5.0.jar
net.java.dev.jna.jna-platform-5.5.0.jar
net.logstash.logback.logstash-logback-encoder-4.11.jar
org.apache.commons.commons-lang3-3.9.jar
org.apache.commons.commons-math3-3.6.1.jar
org.bitlet.weupnp-0.1.4.jar
org.bouncycastle.bcpkix-jdk15on-1.59.jar
org.bouncycastle.bcprov-jdk15on-1.59.jar
org.checkerframework.checker-qual-2.5.2.jar
org.codehaus.janino.commons-compiler-3.0.12.jar
org.codehaus.janino.janino-3.0.12.jar
org.codehaus.mojo.animal-sniffer-annotations-1.17.jar
org.ethereum.leveldbjni-all-1.18.3.jar
org.influxdb.influxdb-java-2.14.jar
org.json4s.json4s-ast_2.13-3.6.7.jar
org.json4s.json4s-core_2.13-3.6.7.jar
org.json4s.json4s-jackson_2.13-3.6.7.jar
org.json4s.json4s-scalap_2.13-3.6.7.jar
org.msgpack.msgpack-core-0.8.16.jar
org.parboiled.parboiled_2.13-2.1.8.jar
org.reactivestreams.reactive-streams-1.0.2.jar
org.rudogma.supertagged_2.13-1.5.jar
org.scala-lang.modules.scala-java8-compat_2.13-0.9.0.jar
org.scala-lang.modules.scala-parser-combinators_2.13-1.1.2.jar
org.scala-lang.scala-library-2.13.3.jar
org.scala-lang.scala-reflect-2.13.3.jar
org.scorexfoundation.scorex-util_2.13-0.1.7.jar
org.scorexfoundation.scrypto_2.13-2.1.8.jar
org.slf4j.slf4j-api-1.7.25.jar
org.typelevel.cats-core_2.13-2.1.0.jar
org.typelevel.cats-effect_2.13-2.1.3.jar
org.typelevel.cats-kernel_2.13-2.1.0.jar
org.typelevel.cats-macros_2.13-2.1.0.jar
org.typelevel.cats-mtl-core_2.13-0.7.1.jar
org.typelevel.jawn-parser_2.13-1.0.0.jar
org.typelevel.machinist_2.13-0.6.8.jar
org.web3j.abi-4.5.18.jar
org.web3j.crypto-4.5.18.jar
org.web3j.rlp-4.5.18.jar
org.web3j.utils-4.5.18.jar
plugins

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Debian/Ubuntu/iOS]
 - Browser/JVM [e.g. chrome, safari]

**Additional context**

**Comment by lcgogo** [comment]
In the 1.2.17 docker image

docker run -it --entrypoint "/bin/sh" wavesplatform/wavesnode:1.2.17
$ ls -l /usr/share/waves/lib/
total 96740
drwxr-xr-x 2 waves waves     4096 Dec 25 14:31 plugins
-rwxr-xr-x 1 waves waves 99051861 Dec 25 14:30 waves-all-1.2.17.jar

**Comment by DrBlast** [comment]
In latest release we've made changes in building image for docker process. Please follow new instructions:
https://docs.waves.tech/en/waves-node/waves-node-in-docker#prerequisites

**Comment by DrBlast** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
