### ISSUE TITLE
Can't sync with custom network

### ISSUE THREAD

**Issue by affiliatepayday** [wavesplatform/Waves#3456]
2021-04-26 21:35:22,399 DEBUG [nio-worker-group-3-2] c.t.n.PeerDatabaseImpl - Suspending [073a2f57 real.ip:6860]
2021-04-26 21:35:23,353 DEBUG [nio-worker-group-3-4] c.t.n.PeerDatabaseImpl - Suspending [cc47e72e 127.0.0.1:6860]

I have a custom chain and the first node runs fine, but I can't seem to get a second node to connect to it. No matter what I try I get the above output and no block updates at all.

I have not been able to get a second node to connect no matter what I try.

**Comment by DrBlast** [comment]
Do nodes see each other? Or you have network problems? Where did you set ip 127.0.0.1? 
You should set another node ip in know-peers (network section) and bind address is "0.0.0.0" for any address

**Comment by affiliatepayday** [comment]
The first node:

  ```
network {
    bind-address = "0.0.0.0"
    port = 6860
    known-peers = []
    node-name = "Private node"
    declared-address = "127.0.0.1:6860"
  }
```

The second node:

 ```
 network {
    bind-address = "0.0.0.0"
    port = 6861
    known-peers = ["127.0.0.1:6860","actual.public.ip:6860"]
    node-name = "Private node 2"
    declared-address = "127.0.0.1:6861"
  }
```

My firewall has 6860 open

I am able to telnet into 127.0.0.1 6860
I am able to telnet into actual.public.ip 6860 (from local machine only)
I am able to telnet into 127.0.0.1 6861

I am also able to access the api on the first node, have a wallet connect to it, issue commands, etc. I have a block explorer working, just can't get the second node to work with the first at all.

Whats more weird is even when I try manually copying the data folder from node 1 directly to node 2, node 2 still doesn't see node 1 and says there are not enough coins held to mine (which there should be as I sent the coins from node address 1 to node address 2). Its almost as if they are trying to operate from 2 different chains even though the genesis shows the same block information. 

I have also tried this on a second server using just the public IP and get the same exact result.

I am very perplexed. 

I've also noticed when I try to connect via external IPs it connects and **immediately** drops connection:

```
telnet actual.public.ip 6860
Trying actual.public.ip...
Connected to actual.public.ip.
Escape character is '^]'.
Connection closed by foreign host.
```

I suspect the problem relates to this, but my firewall is not set to drop. 

```
netstat -tlnp | grep 6860
tcp        0      0 0.0.0.0:6860            0.0.0.0:*               LISTEN      4161/java
```

```
iptables -S | grep 6860
-A INPUT -p tcp -m tcp --dport 6860 -j ACCEPT
```

All my IPs are ipv4 so I don't understand why these drops are happening.

Also as stated this also doesn't work localhost - but telnet does work without dropping. However the logs do not show any handshake even being attempted.

**Comment by affiliatepayday** [comment]
Just to rule things out, I also stopped the node, set sshd to run on port 6860, and loggedin via ssh perfectly without a drop - then I switched everything back so ssh port is back to original, restarted node, and again can't access the 6860 port - immediately dropped. 

This leads me to assume it is something with the server/client connection - not an host dropping port/NAT issue.

These are both dedicated servers running Ubuntu 18.04.5 LTS bionic but the fact the first node runs fine leads me to believe this is not server specific.

**Comment by DrBlast** [comment]
declared address should not be 127.0.0.1, it's a localhost. Do you have both nodes on one host?
Nodes should be available by telnet from one host to another. 
In known peers you should use port that you specified in config for another node - 6861, like this:
node1 - known-peers = ["public.ip.node-2:6861"]
node2 - known-peers = ["public.ip.node-1:6860"]

Generating balance updates every 1000 blocks after balance increase and immediately if balance becomes lower. If you want both nodes to be miners after blockchain start, you should generate right genesis block:
https://docs.waves.tech/en/waves-node/private-waves-network#setup-jar-node-with-custom-blockchain (from 3rd step)
