### ISSUE TITLE
Native library (win32-x86-64/leveldb.dll) not found in resource path

### ISSUE THREAD

**Issue by affiliatepayday** [wavesplatform/Waves#3466]
This is hopefully my last question. 

I am doing a custom build (not a custom chain) and windows users get an error about leveldb.dll not being found in the build when trying to run a miner.

How do I compile/cross compile with the custom leveldb.dll? 

Also will this same issue arise on macOS? 

Currently works flawlessly on linux. I did custom build leveldb locally so it may be something I should have done when doing that build, not really sure. Not a lot of info given about leveldb.

**Comment by phearnot** [comment]
Are you building a fat jar (`assembly`) or a ZIP archive (`node/Universal/packageBin`)? Are there any modifications in your build? The library we depend on already includes pre-built leveldb.dll for 64-bit Windows, so there shouldn't be any reason to manually recompile it when building the node.

**Comment by affiliatepayday** [comment]
I got this sorted already, sorry I forgot to close this question.
