### ISSUE TITLE
Ports Forwarding Configuration

### ISSUE THREAD

**Issue by sebastianfelipe** [wavesplatform/Waves#347]
Hi,

I'm running a peer server just to try and understand how waves works, but I have some questions.  I saw that a peer could use 3 ports -> [network: 6863, rest: 6869, matcher: 6886]. Everything is running behind the ip 127.0.0.1 and I'm not sure about what external ports I need to open for this peer works correctly. I thought in redirect the port 80 to the 6869, but what about the other ports? In the node configuration file is not explained what ports need to be opened as external ports. Maybe if someone is using a virtual machine with an public IP possible there will be no problem, but someone that is using a local machine, redirecting external ports to internal ports manually in the router is a different situation.

I'd really appreciate your help,
Sebastián.

**Comment by alexeykiselev** [comment]
Hi!
You have to open outbound connection on port 6863 at least. This will allow your node to connect to the network. If you want other nodes to connect to your node you have to open inbound connection on the same port. Other ports are optional to open.
