### ISSUE TITLE
MobileGo tokens not received

### ISSUE THREAD

**Issue by mjbayly** [wavesplatform/Waves#354]
Hi there

I transferred MobileGo tokens from my Waves wallet nearly a 4 days ago and the token haven't shown in my wallet yet. Anybody able to help me understand why? The transaction looks successful and the recipient address is correct. http://wavesexplorer.com/tx/HoigTFBmoLLCLk53xpUCGxRK6W561NEqisq961HNRdL6

**Comment by xenohunter** [comment]
Hello! Thank you for the feedback. Maybe you're looking for the asset on the wallets tab? If so, try to check the portfolio tab. All your issued and received assets are shown there. It's the second icon in the Lite Client app header.

**Comment by anton48** [comment]
Hi! 

This transaction contains some scam token (http://wavesexplorer.com/tx/9yTNgraB8y9uR7J2WR4cjBJDC8rCNYRrUMDhfRLvYJkD), not the real Mobile Go (http://wavesexplorer.com/tx/2Y8eFFXDTkxgCvXbMT5K4J38cpDYYbQdciJEZb48vTDj). On the other hand, if your address is 3PE5ZLLSdrryLZ6TSCJZhimY9HxmQT8m4Ty, then it has correct tokens too, 148609.67643154 of them.

**Comment by mjbayly** [comment]
Hi @xenohunter - sorry i'm confused. I transferred the MobileGo tokens from my Waves Wallet to the Tidex exchange, and the coins aren't in my Waves wallet or on Tidex. I've checked all over the Waves wallet and Tidex (Not new too trading, so am pretty sure I haven't missed anything). Any other ideas?

Hi @anton48 - are you saying the MobileGo tokens I received were actually not the real MobileGo tokens? Any idea where they may have gone? Really confused sorry. Thanks

**Comment by anton48** [comment]
@mjbayly: yes, in the transaction from your first message (http://wavesexplorer.com/tx/HoigTFBmoLLCLk53xpUCGxRK6W561NEqisq961HNRdL6) we can see not the real MGO tokens, since they have 9yTNgraB8y9uR7J2WR4cjBJDC8rCNYRrUMDhfRLvYJkD asset id. 

Real MGO have 2Y8eFFXDTkxgCvXbMT5K4J38cpDYYbQdciJEZb48vTDj asset id. 

and, if your address is 3PE5ZLLSdrryLZ6TSCJZhimY9HxmQT8m4Ty, then you have correct MGO tokens too, currently 152441.67643154 of them.

this is an example of transaction with 3700 correct MGO tokens which were sent to 3PE5ZLLSdrryLZ6TSCJZhimY9HxmQT8m4Ty address: http://wavesexplorer.com/tx/H7fkUbUghgkMd7hLh1THHtF1g4HSVapQCWes4B3PFPV8

**Comment by mjbayly** [comment]
@anton48 cheers for clarifying, I'm on board with what you're saying. Any idea what the MobileGo tokens I received were then? Or if they have value? I'm guessing because I send the fake MGO tokens to the a real MGO token address, the tokens will have disappeared from my control now?

Based on the address above, yes that is my wallet address in Tidex but my account is empty. I just noticed the deposit addresses for multiple coins in my wallet are the same, this is counter to what i've experienced with Bittrex and Poloniex. The deposit address for MobileGo on Tidex is also the same as it was last week. Shouldn't the deposit address for each coin be different, and shouldn't the address update as new blocknumbers open? Having not used Tidex prior to this, is it legit? Unsure if it's worth pursuing this issue, esp. if the coins are fake and have no value... 

![image](https://user-images.githubusercontent.com/29106686/27256090-f5d82110-53ff-11e7-8e1d-d8d466540ff3.png)

**Comment by anton48** [comment]
@mjbayly: not sure about tokens at Tidex, although they are certainly legit. maybe you didn't use MEMO while sending? in this case you need to contact Tidex support.
