### ISSUE TITLE
GRPC GetUnfonfirmed always returns empty stream.

### ISSUE THREAD

**Issue by a-kosak-mbx** [wavesplatform/Waves#3568]
I am trying to use grpc and all works fine until i call GetUnconfirmed.
Small part of code is

`__SERVER_ADDRESS = 'nodes.wavesnodes.com:6870'`
`channel = grpc.insecure_channel(__SERVER_ADDRESS)`
`client = TransactionsApiStub(channel)`
`request = TransactionsRequest()`
`response = client.GetUnconfirmed(request)`
`transaction = response.next()`

And it always causes StopIteration even there unconfirmed transactions in the pool.

I looked into grpc server source code and it looks like no parameters must be configured for call.

Ubuntu 20, Python 3.8.

**Comment by phearnot** [comment]
If neither [`sender`](https://github.com/wavesplatform/protobuf-schemas/blob/master/proto/waves/node/grpc/transactions_api.proto#L51) nor [`transaction_ids`](https://github.com/wavesplatform/protobuf-schemas/blob/master/proto/waves/node/grpc/transactions_api.proto#L53) is specified, the server will return an empty stream.

Will you kindly describe your use case?

**Comment by a-kosak-mbx** [comment]
Looks like you are right. I passed both sender and transaction_ids empty and expected that it will work in the same way as its analogue in REST API and would return all unconfirmed transactions that had existed in such case. But you say that it is not a bug. So issue can be closed I think.
The only one question. Maybe you can suggest how in such case I can get all unconfirmed transactions using grpc?

**Comment by phearnot** [comment]
We're not planning to expose the whole UTX pool content via gRPC.
However, if you intend to monitor UTX, you might consider writing an extension for the node which will have access to all [UTX events](https://github.com/wavesplatform/Waves/blob/758aee7dd2348b755f8c5b84a3cbfe21d86f4f5a/node/src/main/scala/com/wavesplatform/extensions/Context.scala#L34).
