### ISSUE TITLE
Failed ethereum transactions have no additional info

### ISSUE THREAD

**Issue by deemru** [wavesplatform/Waves#3584]
**Describe the bug**
There is an empty payload on a failed ethereum (19) transaction.

**To Reproduce**
https://nodes-stagenet.wavesnodes.com/transactions/info/GvMHeCnYKduQg26Ly8oZkYYXP7ghjdKZHRNzkXVEZcTo

**Expected behavior**
At least we need to know everything we know from failed invocation (16) transactions:
- dApp
- call function
- function args
- payments
- stateChanges with error description

**Screenshots**
![image](https://user-images.githubusercontent.com/10706633/141368855-ab88110e-37f1-438b-8b35-54ed4c64515b.png)

**Comment by DrBlast** [comment]
Accepted. Will be fixed in nearest release.

**Comment by phearnot** [comment]
Fixed in #3587
