### ISSUE TITLE
Default value of "walletDir" and "dataDir" in the json file

### ISSUE THREAD

**Issue by omwave777** [wavesplatform/Waves#36]
The default values of the properties "walletDir": "/tmp/scorex/waves/wallet" and "dataDir": "/tmp/scorex/waves/data/"in the .json file should be changed to "/var/lib/waves/wallet" and to "dataDir": "/var/lib/waves/data/" respectively. The tmp directory is getting deleted by default in ubuntu during reboot, so the node will have to do a full sync which currently takes a few hours to complete. Thanks.

**Comment by gagarin55** [comment]
fixed in https://github.com/wavesplatform/Waves/commit/7dd0cb2d30827d466dfb3994b4a6b14acd32439b
