### ISSUE TITLE
transaction type 17 not supported

### ISSUE THREAD

**Issue by viraladmin** [wavesplatform/Waves#3632]
I am using node version 1.3.x. 

According to the docs `The Update Asset Info transaction type is enabled by of feature #15 “Ride V4, VRF, Protobuf, Failed transactions”.` -- https://docs.waves.tech/en/blockchain/transaction-type/update-asset-info-transaction

Yet when submitting a type 17 for signing, the rest API for my node returns: 

```
{
  "error": 312,
  "message": "transaction type not supported"
}
```

Looking at `node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala` it appears there is no definition for `UpdateAssetInfoTransaction` in the `parseRequestAndSign`.

**Comment by phearnot** [comment]
Thanks for the report, we'll include the fix in one of the future releases.
