### ISSUE TITLE
NodeException{code=112, message=State check failed. Reason: Transactions from non-scripted accounts must have exactly 1 proof}

### ISSUE THREAD

**Issue by suryansh-lovcash** [wavesplatform/Waves#3682]
**Describe the bug**
HI 
I am getting 
NodeException{code=112, message=State check failed. Reason: Transactions from non-scripted accounts must have exactly 1 proof}
when using 
TransferTransaction transaction = new TransferTransaction(sender, recipient, amount, attachment, chainId, fee, timestamp, version, proofs);
proofs variable is null here.

I am unable to get any documentation on how to define proof for a transaction, 
I am using java dependency
		 <dependency>
		    <groupId>com.wavesplatform</groupId>
		    <artifactId>wavesj</artifactId>
		     <version>1.2.4</version>
		</dependency>

**Comment by suryansh-lovcash** [comment]
Please can i get any solution.

**Comment by yvaskov** [comment]
Hi, this is not a bug.

I'd recommend using `TransferTransaction.builder()` instead of `new TransferTransaction()`. This way you can easily add proof with `.getSignedWith()` like this:

```
TransferTransaction tx = TransferTransaction
    .builder(recipientAddress, Amount.of(100000000L))    //Transferring 1 Waves for example
    .getSignedWith(yourPrivateKey);
```

**Comment by yvaskov** [comment]
@suryansh-lovcash have I helped resolve the issue?

**Comment by suryansh-lovcash** [comment]
Hi Yan
Thanks for your reply.
Yes, your suggestion helped us a lot and we  were able to do our
transactions.

Regards
Suryansh Tiwari
