### ISSUE TITLE
Orderbook bug. Maybe matcher issue.

### ISSUE THREAD

**Issue by nbkshocks** [wavesplatform/Waves#369]
![image](https://user-images.githubusercontent.com/29697494/27542367-e2b20a78-5a3b-11e7-8905-7092819c11f5.png)

![image](https://user-images.githubusercontent.com/29697494/27542370-e758f690-5a3b-11e7-9804-32b9c47b2903.png)

I bought some mercury, 40k amount but not seeing it in my order page.. This is happening with waveswallet.io/liteapp/mainnet. Firewall/anti-virus were off. Please help.

**Comment by alexeykiselev** [comment]
It was a matcher restart issue, was fixed in newer versions.
