### ISSUE TITLE
There's no option do disable cors on new node version

### ISSUE THREAD

**Issue by anonpragmatic** [wavesplatform/Waves#3724]
**Describe the bug**
New version of the node (1.4.6) has a bug with cors option. Even if it's set to no, it still sends this header:

access-control-allow-origin: http://localhost:8080

**Comment by anonpragmatic** [comment]
In new configuration, cors-headers {} should disable cors headers completely, that's the behavior I would expect. But it doesn't, it just sends defaults.

**Comment by phearnot** [comment]
#3721 addresses this issue. It also changes the behavior of the node in such way that CORS headers are only sent when `Origin` header is present in the original request. If no `Origin` header is present in the original request, then no CORS headers will be sent at all.

Could you please describe a use case when you need to explicitly disable CORS headers completely?

**Comment by anonpragmatic** [comment]
I think this covers my use case too, thank you. Also, I remembered that I can strip any header using nginx so this is what I've done for now, if anybody is experiencing the same issue:

`proxy_hide_header access-control-allow-origin;`
`add_header 'Access-Control-Allow-Origin' $ref always;`

I'll close the issue now.
