### ISSUE TITLE
Could not load library. Reasons: no leveldbjni64-0.6.4

### ISSUE THREAD

**Issue by parliament718** [wavesplatform/Waves#399]
I'm trying to start a waves full node for the first time. I believe my config is correct. I used the starter config from the github, added my Encoded Seed from the Liteclient into "seed =", and my password. Set type=MAINNET, set public-key= to value from the liteclient, set account= to the account address in the liteclient.

Running java -jar waves-0.6.6.jar waves-mainnet.conf results in some leveldb related errors. Seems to stem from Temp folder, I tried deleting that to no avail. 

![capture](https://user-images.githubusercontent.com/3580270/28244787-a96a0b76-69c2-11e7-9172-13bfa6cd5d32.PNG)

**Comment by ken-talkingsource** [comment]
Got same error when I set  **matcher.enable = yes** in 0.7.6
OS : Windows7
Java version: 1.8

> 2017-08-22 22:46:28 ERROR [t-dispatcher-12] akka.actor.ActorSystemImpl - Uncaugh
> t error from thread [wavesplatform-akka.persistence.dispatchers.default-plugin-d
> ispatcher-13]: Could not load library. Reasons: [no leveldbjni64-0.7.6 in java.l
> ibrary.path, no leveldbjni-0.7.6 in java.library.path, no leveldbjni in java.lib
> rary.path, C:\Users\minimini\AppData\Local\Temp\leveldbjni-64-0-4975276957591979
> 080.7: Can't find dependent libraries], shutting down JVM since 'akka.jvm-exit-o
> n-fatal-error' is enabled for ActorSystem[wavesplatform]
> java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni6
> 4-0.7.6 in java.library.path, no leveldbjni-0.7.6 in java.library.path, no level
> dbjni in java.library.path, C:\Users\minimini\AppData\Local\Temp\leveldbjni-64-0
> -4975276957591979080.7: Can't find dependent libraries]
>         at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
>         at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
>         at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)
> 
>         at akka.persistence.journal.leveldb.LeveldbStore.leveldbFactory(LeveldbS
> tore.scala:52)
>         at akka.persistence.journal.leveldb.LeveldbStore.leveldbFactory$(Leveldb
> Store.scala:51)
>         at akka.persistence.journal.leveldb.LeveldbJournal.leveldbFactory(Leveld
> bJournal.scala:23)
>         at akka.persistence.journal.leveldb.LeveldbStore.preStart(LeveldbStore.s
> cala:178)
>         at akka.persistence.journal.leveldb.LeveldbStore.preStart$(LeveldbStore.
> scala:177)
>         at akka.persistence.journal.leveldb.LeveldbJournal.preStart(LeveldbJourn
> al.scala:23)
>         at akka.actor.Actor.aroundPreStart(Actor.scala:510)
>         at akka.actor.Actor.aroundPreStart$(Actor.scala:510)
>         at akka.persistence.journal.leveldb.LeveldbJournal.aroundPreStart(Leveld
> bJournal.scala:23)
>         at akka.actor.ActorCell.create(ActorCell.scala:590)
>         at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
>         at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
>         at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:223)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> 2017-08-22 22:46:34 INFO  [shutdownHook1] c.w.Application - Stopping network ser
> vices
> [ERROR] [08/22/2017 22:46:34.800] [wavesplatform-akka.persistence.dispatchers.de
> fault-plugin-dispatcher-16] [akka://wavesplatform/system/akka.persistence.journa
> l.leveldb] null
> java.lang.NullPointerException

Could someone help ?

**Comment by alexeykiselev** [comment]
Akka and its persistent layer use LevelDB as storage engine. Since version 0.9.1 we added the fixed version of LevelDB JNI library to `waves-all-...` JAR file.
