### ISSUE TITLE
Node doesn't detect a change in "walletSeed" automatically.

### ISSUE THREAD

**Issue by bcdev-** [wavesplatform/Waves#40]
After changing "walletSeed" node still tries to forge using the previous seed.
It starts forging using a new seed only after removing wallet.s.dat.

Expected behavior is obviously to respect "walletSeed" parameter when the node starts.

**Comment by Tolsi** [comment]
One wallet file can store information for multiple seeds addresses. you just do not see it :) probably we will change this in the future
