### ISSUE TITLE
Waves v0.7.2-SNAPSHOT Expected authority at index 5: my://

### ISSUE THREAD

**Issue by iSnow** [wavesplatform/Waves#400]
From 2017-07-15, running on Ubuntu:

If I leave declared-address="" in my usr/share/waves/conf/waves.conf, the exception further down is thrown. If I use my public address:port 6863, the exception is not thrown.

Is this a bug in the snapshot version or should I just enter something like 0.0.0.0? As a DSL user, my public IP of course changes daily.

Stacktrace:

Jul 16 22:31:11 Goldmine systemd[1]: Started Waves node.
Jul 16 22:31:12 Goldmine waves[24356]: INFO  c.w.Application$ - Starting...
Jul 16 22:31:12 Goldmine waves[24356]: Exception in thread "main" java.net.URISyntaxException: Expected authority at index 5: my://
Jul 16 22:31:12 Goldmine waves[24356]:         at java.net.URI$Parser.fail(URI.java:2848)
Jul 16 22:31:12 Goldmine waves[24356]:         at java.net.URI$Parser.failExpecting(URI.java:2854)
Jul 16 22:31:12 Goldmine waves[24356]:         at java.net.URI$Parser.parseHierarchical(URI.java:3102)
Jul 16 22:31:12 Goldmine waves[24356]:         at java.net.URI$Parser.parse(URI.java:3053)
Jul 16 22:31:12 Goldmine waves[24356]:         at java.net.URI.<init>(URI.java:588)
Jul 16 22:31:12 Goldmine waves[24356]:         at com.wavesplatform.settings.NetworkSettings$.$anonfun$fromConfig$3(NetworkSettings.scala:44)
Jul 16 22:31:12 Goldmine waves[24356]:         at scala.Option.map(Option.scala:146)
Jul 16 22:31:12 Goldmine waves[24356]:         at com.wavesplatform.settings.NetworkSettings$.fromConfig(NetworkSettings.scala:43)
Jul 16 22:31:12 Goldmine waves[24356]:         at com.wavesplatform.settings.NetworkSettings$.com$wavesplatform$settings$NetworkSettings$$$anonfun$networkSettingsValueReader$1(NetworkSettings.scala:36)
Jul 16 22:31:12 Goldmine waves[24356]:         at com.wavesplatform.settings.NetworkSettings$$anonfun$1.read(NetworkSettings.scala:36)
Jul 16 22:31:12 Goldmine waves[24356]:         at com.wavesplatform.settings.NetworkSettings$$anonfun$1.read(NetworkSettings.scala:36)
Jul 16 22:31:12 Goldmine waves[24356]:         at net.ceedubs.ficus.FicusConfig.as(FicusConfig.scala:10)
Jul 16 22:31:12 Goldmine waves[24356]:         at net.ceedubs.ficus.FicusConfig.as$(FicusConfig.scala:10)
Jul 16 22:31:12 Goldmine waves[24356]:         at net.ceedubs.ficus.SimpleFicusConfig.as(FicusConfig.scala:19)
Jul 16 22:31:12 Goldmine waves[24356]:         at com.wavesplatform.settings.WavesSettings$.fromConfig(WavesSettings.scala:38)
Jul 16 22:31:12 Goldmine waves[24356]:         at com.wavesplatform.Application$.main(Application.scala:235)
Jul 16 22:31:12 Goldmine waves[24356]:         at com.wavesplatform.Application.main(Application.scala)
Jul 16 22:31:12 Goldmine systemd[1]: waves.service: Main process exited, code=exited, status=1/FAILURE
Jul 16 22:31:12 Goldmine systemd[1]: waves.service: Unit entered failed state.
Jul 16 22:31:12 Goldmine systemd[1]: waves.service: Failed with result 'exit-code'.

**Comment by alexeykiselev** [comment]
Hello, it's not a bug. We mentioned this new configuration file behavior in notes to new version 0.7.2 https://github.com/wavesplatform/Waves/wiki/What's-new-in-version-0.7.2.
You should delete this line or comment it out.
