### ISSUE TITLE
DEX: negative BTC balance

### ISSUE THREAD

**Issue by bitdjinn** [wavesplatform/Waves#408]
Making a trade in (Waves/BTC) and then directly another trade  (Waves/BTC)  results in a negative BTC balance. (I have open buy orders where the sum is bigger than the negative BTC amount)
![waves exchange bug](https://user-images.githubusercontent.com/22123146/28375533-0a927248-6ca8-11e7-8b72-47ac78b99c61.png)

I can only imagine what will happen to my open orders when they are filled

This occurs on the mainnet (node v0.6.6 + chrome lite wallet 0.4.30a)

**Comment by alexeykiselev** [comment]
It is so called "tradable balance" it could be negative.
