### ISSUE TITLE
How can I run my own Matcher?

### ISSUE THREAD

**Issue by User195** [wavesplatform/Waves#416]
I read your blog https://blog.wavesplatform.com/what-is-waves-dex-7c311d1360a1 
But I dont understood how can I run my own Matcher. What toolkit I have to install? Or how to set it up? Can anybody explain?

**Comment by alexeykiselev** [comment]
Waves node contains DEX Matcher. You have to enable it. Please, read https://github.com/wavesplatform/Waves/wiki/Waves-Node-Configuration-File#matcher-settings about matcher configuration.
