### ISSUE TITLE
Unexpected behavior in "Trades by address" service

### ISSUE THREAD

**Issue by AndreaPravato** [wavesplatform/Waves#421]
After reading this one: http://marketdata.wavesplatform.com/, 
I have tested this service: "Trades (by address) Get trades for a specified asset pair and address". The example in that page works fine for me too, but if I try to change address and assets, I get apparently wrong results. Example: 

http://marketdata.wavesplatform.com/api/trades/WGO/WAVES/3PLDVNLQnbs3CREh1CPhA4r1C98s8T2UAE8/4
gives 
[ {
  "timestamp" : 1498465586405,
  "id" : "EwodBAuGCn4FhQyFBonB9PXD3MyFAdZPLCMyTiwzWyng",
  "confirmed" : true,
  "type" : "buy",
  "price" : "0.03400000",
  "amount" : "3277.32817405",
  "buyer" : "3P3J3h7d3AUof2wjtWzHjLj6Hr2Sq6GqzWC",
  "seller" : "3PPRHx1PSXLJm6XZS7P7VjyrnXFJQ9xBaPE",
  "matcher" : "7kPFrHDiGw1rCm7LPszuECwWYL3dMf6iMifLRDJQZMzy"
}, {
  "timestamp" : 1498463730395,
  "id" : "Ay8k9KDDn4R2pSzpi6aTXhq6kLrHpS92ENyUcRkbhWxy",
  "confirmed" : true,
  "type" : "buy",
  "price" : "0.02900000",
  "amount" : "500.00000000",
  "buyer" : "3PGKvcbxNf8aJdEPAqniY63Gb996ZpRMHd5",
  "seller" : "3P3J3h7d3AUof2wjtWzHjLj6Hr2Sq6GqzWC",
  "matcher" : "7kPFrHDiGw1rCm7LPszuECwWYL3dMf6iMifLRDJQZMzy"
} ]

and the provided address is neither in buyer nor seller

**Comment by AndreaPravato** [comment]
Am i supposed to use the service in another way or is it a confirmed bug?

**Comment by PyWaves** [comment]
Thanks for reporting the issue! Yes, it's a confirmed bug and the fix is going to be deployed today.
@pblck

**Comment by AndreaPravato** [comment]
@PyWaves, given that this is under re-work, please consider this new feature request also #422
