### ISSUE TITLE
Feature request: api to get orders (trades) of a given address

### ISSUE THREAD

**Issue by AndreaPravato** [wavesplatform/Waves#422]
I would like to collect all existing orders related to a wallet address, disregarding the asset pair.
In http://marketdata.wavesplatform.com, "datafeed api" tab, there is an API to get trades by address, but I have to specify a specific asset pair

**Comment by AndreaPravato** [comment]
In the result, for each trade there should be also info to know which asset pair that specific trade is related to

**Comment by PyWaves** [comment]
This is already on my to-do list, but it will take some more time.

**Comment by ilyacherevkov** [comment]
was it implemented?
