### ISSUE TITLE
Improvement proposal: Smooth fee rewards.

### ISSUE THREAD

**Issue by bcdev-** [wavesplatform/Waves#44]
Right now current a miner can have free transactions by putting transactions into blocks mined by him.
That is suboptimal because of free blockchain bloat. Let's make a miner pay! >:-B
Let's split the reward from the block. There are few alternatives:
1) Sending a fee to the past. When a miner mines a block, he takes 50% of the reward, and he gives 50% of the reward to a miner who mined a block 60 blocks ago.
2) Smoothing: Like [1], but the reward is split 50%-1%-1%-1%...

I think that [2] is slightly superior because it smooths fees more. Thus, it makes rewards from getting large-fee-transactions [ex. asset creation - 1000NXT] much more fairly distributed.

Regardless of implementation, there are things to keep in mind:
- Fees have to be sent back in time, not forward.
- Miner needs to have some big % of the reward for himself to encourage him to include transactions in a block.

**Comment by alexeykiselev** [comment]
The "40%-60%" fee police was implemented with NG.
