### ISSUE TITLE
List btc and etc transactions through api?

### ISSUE THREAD

**Issue by Corstiaan84** [wavesplatform/Waves#454]
Can I somehow list btc and eth transactions and balances through the api?

Thanks

**Comment by petermz** [comment]
No, BTC and ETH have their own blockchains, Waves node does not communicate with them

**Comment by Corstiaan84** [comment]
I know that :-). But the waves wallet displays eth/btc (onramp) transactions and those are the ones I am referring to. When talking to the waves api, can I get to that information?

**Comment by petermz** [comment]
Hi --
I'm sorry for the delay. Sure, for these assets, like any other ones, you can get balances by doing GET /assets/balance/{address} . The returned value is a map where keys are asset IDs so you just need to know the IDs of your assets to check balances
