### ISSUE TITLE
/asset/balance endpoint answering with Swagger UI when a . is provided as parameter

### ISSUE THREAD

**Issue by jansenmarc** [wavesplatform/Waves#48]
If for at least one of the two parameters address or assetId a simple . is provided, the endpoint answers with the Swagger UI itself (as HTML source).

**Comment by gagarin55** [comment]
I need to note that Swagger UI is not actually User UI. It doesn't contain many validation feature. 
So, "dot' is invalid URL Parameter, HTTP GET with url /asset/balance/./. is invalid.
Please, do not consider Swagger UI as GUI for full node, its more documentation tool
