### ISSUE TITLE
Wiki cryptographic details is wrong

### ISSUE THREAD

**Issue by dmichulke** [wavesplatform/Waves#487]
Among others, the correct hashing order to arrive at a key pair from an account address is not:

    blake2b256(keccak256(bytes))

but

    keccak256(blake2b256(bytes))

In addition, the *hash* (sha256) of the account seed is used to feed Curve25519.

Taken from

https://github.com/PyWaves/pywavestools/blob/master/address_generator.py

**Comment by alexeykiselev** [comment]
It's a curve25519 implementation detail. Some libraries do this hashing inside of the key generation function the other do it outside. We can add a note about this.

**Comment by petermz** [comment]
Seems fixed in the wiki
