### ISSUE TITLE
Documentation for the /asset/issue endpoint

### ISSUE THREAD

**Issue by jansenmarc** [wavesplatform/Waves#49]
According to SimpleTransactionModule.issueAsset, it seems like assedItOpt, name and descritption need to be Base58 encoded strings. This should be obvious from the documentation of the endpoint.

Furthermore, the documentation of the endpoint describes the decimals field as a string, which should actually be an int.

**Comment by Tolsi** [comment]
[Here](https://github.com/wavesplatform/Waves/wiki/Waves%20Node%20REST%20API#post-assetsissue) it is
