### ISSUE TITLE
Monitor bandwidth of Waves process

### ISSUE THREAD

**Issue by devos50** [wavesplatform/Waves#540]
For an experiment, I would like to monitor the bandwidth of Waves for a short period (a few minutes). Since my knowledge of Scala is limited and I'm not familiar with the code, I wonder if there's someone who could help me with some pointers to relevant code for this.

I did some searching already and I found the `NetworkServer` class but it's rather complicated for me since I don't know in detail what's going on. I also found out about the `TrafficCounter` class which can be implemented on a `Channel` (https://netty.io/4.0/api/io/netty/handler/traffic/TrafficCounter.html), however, I'm not sure how to integrate this class.

Any help would be much appreciated! I'm just interested in counting the bytes of the core network communication, not the HTTP API traffic 👍

**Comment by alexeykiselev** [comment]
There is a `traffic-logger` section in configuration file:

```
   traffic-logger {
      # Codes of transmitted messages to ignore. See MessageSpec.messageCode
      ignore-tx-messages = [23, 25] # BlockMessageSpec, TransactionMessageSpec

      # Codes of received messages to ignore. See MessageSpec.messageCode
      ignore-rx-messages = [25] # TransactionMessageSpec
    }
```
