### ISSUE TITLE
Segfault java процессса при поднятии двух нод на одной машине

### ISSUE THREAD

**Issue by damir-manapov** [wavesplatform/Waves#560]
SIGSEGV выкидывается одной из нод, если на одной машине поднять 2 ноды waves с невыключенным стартом kamon

Шаги для воспроизведения

* Клонируем мастер
	```git clone https://github.com/wavesplatform/Waves.git```
	```cd Waves```
* На данный момент последний коммит "7272ef9529b5a7a3c4c360d75fdb475be6469c28", для воспроизводимости переключимся явно на него
	```git checkout 7272ef9529b5a7a3c4c360d75fdb475be6469c28```
* Копируем конфиг файл первой ноды
	```cp waves-devnet.conf ./waves-devnet-1.conf```
* Редактируем его
	```sed -i "s/waves {/waves {\n\n  directory = \${user.home}\"\/waves_test-1\/1\"\n/g" waves-devnet-1.conf```
	```sed -i "s/known-peers = \[\"34.251.200.245:6864\", \"35.157.212.173:6864\", \"13.229.61.140:6864\"\]/known-peers = [\"127.0.0.1:7864\"]/g" waves-devnet-1.conf```
	```sed -i "s/My DEVNET node/My DEVNET node 1/g" waves-devnet-1.conf```
* Чиним изменение формата waves.blockchain.custom.functionality.pre-activated-features		 
	```sed -i "s/pre-activated-features = \[2\]/pre-activated-features = \{2=0\}/g" waves-devnet-1.conf```
* Делаем конфиг второй ноды на основе конфига первой
	```cp waves-devnet-1.conf ./waves-devnet-2.conf```
* Редактируем его
	```sed -i "s/waves_test-1\/1/waves_test-1\/2/g" waves-devnet-2.conf```
	```sed -i "s/127.0.0.1:7864/127.0.0.1:6864/g" waves-devnet-2.conf```
	```sed -i "s/My DEVNET node 1/My DEVNET node 2/g" waves-devnet-2.conf```
	```sed -i "s/port = 6864/port = 7864/g" waves-devnet-2.conf```
	```sed -i "s/declared-address = \"127.0.0.1:6864\"/declared-address = \"127.0.0.1:7864\"/g" waves-devnet-2.conf```
	```sed -i "s/port = 6886/port = 7886/g" waves-devnet-2.conf```
	```sed -i "s/port = 6869/port = 7869/g" waves-devnet-2.conf```
* Запускаем первую ноду
	```sbt "run waves-devnet-1.conf"```
* Запускаем вторую ноду в другой консоли
	```sbt "run waves-devnet-2.conf"```

Первая валится с SIGSEGV
Если посмотреть в hs_err_pid*.log
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V+0
j  org.hyperic.sigar.Cpu.fetch(Lorg/hyperic/sigar/Sigar;)Lorg/hyperic/sigar/Cpu;+10
j  org.hyperic.sigar.Sigar.getCpu()Lorg/hyperic/sigar/Cpu;+1
j  org.hyperic.sigar.Sigar.getCpuPerc()Lorg/hyperic/sigar/CpuPerc;+25
j  kamon.system.sigar.CpuMetrics.cpuPerc$1()Lscala/Tuple5;+4
```

**Comment by vsuharnikov** [comment]
Отличный баг-репорт 👍 

Сталкивался с такой же проблемой, когда Kamon работал с одной libsigar. Что интересно, на macOS подобной проблемы не наблюдается, только на Linux. Варианты решения:
* Отключить отправку системных метрик: 
```conf
kamon {
  modules {
    kamon-statsd.auto-start = yes
    kamon-system-metrics.auto-start = no # <-- эта строка
  }
}
``` 

* Либо собрать ноду через `universal:dist` и одной из нод указать другой путь к libsigar.so через ENV или [еще](https://github.com/kamon-io/sigar-loader/tree/master/core/src/main/resources) как-то
