### ISSUE TITLE
Send Waves using REST API

### ISSUE THREAD

**Issue by i3bitcoin** [wavesplatform/Waves#570]
**The case can be closed.**

Hi, I'm new to Wavesplatform.

I am testing the REST API at the moment and everything worked smooth (balance, generate address, get block, get transaction info) till I tried to transfer WAVES to other address.

I used POST /assets/transfer method including API_KEY and params:
sender: "My Address"
recipient: "Recipient Address"
fee: 100000
amount: 1000000
attachment: ""

Unfortunately I got error: The requested resource could not be found but may be available again in the future.

Is there any settings where I need to enable private functions?

Edit.1: Don't know if it may be a problem, but I'm sending requests from the different server.
Edit.2: I've just tried to send local request and it didn't work as well.
Edit.3: Tried to send array, json, httprawpostdata with parameters, but it didn't work.

**Comment by JackPickering** [comment]
Hi, 

Can you tell me how you accessed the API? What do you call before specifying the URI? 

Sorry, I know this wasnt the answer to your question.

**Comment by i3bitcoin** [comment]
I'm using PHP + Curl.

1st step: you need to enable rest api in the waves.conf (/usr/share/waves/conf)
enable = yes
bind-address = "127.0.01"
port = 1234
api-key-hash = "HASH VALUE" - pre-generated string using "/utils/hash/secure" method in REST API.

Then just send curl request to the address, for example:
GET - http://127.0.0.1:1234/addresses - getting account addresses
GET - http://127.0.0.1:1234/blocks/height - getting last block height

**Comment by i3bitcoin** [comment]
You are welcome.

Don't know if it may be a problem, but I'm sending requests from the different server.

**Comment by i3bitcoin** [comment]
Okay, I've found a solution.
I forgot to add json header to request.

**Comment by loainagati** [comment]
@i3bitcoin How do you install Waves on Linux?

**Comment by petermz** [comment]
For the record: The header that's needed is
        Content-type: application/json
