### ISSUE TITLE
/utils/hash/secure - The requested resource could not be found but may be available again in the future.

### ISSUE THREAD

**Issue by JackPickering** [wavesplatform/Waves#572]
I have simply download and run the waves.jar command, the terminal starts to log data and the REST API works as it prints my address when prompted. 

When navigating to /utils/hash/secure I get the response: 
The requested resource could not be found but may be available again in the future.

Is this just a generic error message? Do I need to download the full chain from somewhere?

**Comment by JackPickering** [comment]
I realise that I was sending a GET not a POST however, where do I find the API-key that I am meant to get a hash for?

**Comment by phearnot** [comment]
The default value for API key is `ridethewaves!`. I've updated a [wiki page](https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API#private-functions) to mention this explicitly.

**Comment by petermz** [comment]
Another thing you may need to specify in order to avoid 404 is a content type header:
`Content-type: application/json`
