### ISSUE TITLE
Spending problem with partial tokens of an asset

### ISSUE THREAD

**Issue by jansenmarc** [wavesplatform/Waves#58]
During the test ico, i tried to also spend partial tokens (from a tokens defined with 8 digits). Nevertheless, the  /assets/transfer endpoint only accepts a long value (no decimals) for the amount of tokens to transfer. On the other hand, this value does not seem to be interpreted as (amountOfTokens \* 10^digits) since amounts higher than the current amount of tokens of an address yield to invalid transactions.

**Comment by Tolsi** [comment]
@gagarin55

**Comment by bcdev-** [comment]
I've looked into the issue. You just used the IssueTransaction wrong. :-)
You need to issue a token with (amountOfTokens * 10^digits). So if you've for example issued
```
"quantity": 42
"decimals": 4
```
you have in reality issued
```
0.0042 token
```
So instead you should have issued 420000 for the amount to be correct. :-)
[It's confusing, but it's correct and I agree with that design.]

**Comment by jansenmarc** [comment]
I also agree on the Design, but it wasn't working like this during the test ICO. Anyway, it may have been a problem in combination with the double spending issue. Therefore hard to reproduce.
