### ISSUE TITLE
Miners should vote on some network parameters.

### ISSUE THREAD

**Issue by bcdev-** [wavesplatform/Waves#60]
Two aspects of a cryptocurrency right now are ridiculous:
1. The fact that Bitcoin devs for 3 years cannot achieve consensus to raise the blocksize.
2. That Ethereum needs to make a HARD FORK to change transaction fees.

So I propose that miners should vote on some parameters of the network. Miners definitely should vote on:
- The transaction fee - If the fee is set today 1c and Waves rises 100_, it'll become $1, which would be ridiculous. We need a mechanism to adjust it fairly quickly without breaking consensus. [The same problem is if Waves falls down 100_, allowing a blockchain bloat through ridiculously cheap transactions]
- Amount of transactions in a block

Miners would make a mandatory vote on these parameters with each block. The value for current block could be a median of 2880 last votes/blocks.

The change is relatively easy to implement.

**Comment by gagarin55** [comment]
In this case, when we validate fee amount during block validation, we will have to recalculate acceptable MinFee for each block, right ?

**Comment by bcdev-** [comment]
Miner has to recalculate it. Non-miners just read it and if it's incorrect, reject the block.
MinFee should be in the signed part of the block header, so that we can send it to the wallet, so that it knows what the current fee is.

**Comment by phearnot** [comment]
Implemented in [Waves Features Activation Protocol](https://github.com/wavesplatform/Waves/wiki/Waves-Features-Activation-Protocol).
