### ISSUE TITLE
SBT Error?

### ISSUE THREAD

**Issue by oneyesoneno** [wavesplatform/Waves#621]
![untitled](https://user-images.githubusercontent.com/20178233/31863301-08cae3a0-b776-11e7-9420-f9c4101d4c67.png)

Hi guys.. hi Tolsi.... can you tell me what wrong with this screenshot? i follow your guide here https://github.com/wavesplatform/Waves/wiki/Creating-a-private-Waves-blockchain-network . Thanks

**Comment by vsuharnikov** [comment]
Hi!
1. Are you working in IDEA and SBT from the console at same time? If yes, please check "Use SBT shell..." in IDEA: Preferences > Build, Execution, Deployment > Build Tools > SBT
2. Run "clean" from SBT
3. Also try a full path to the genesis.example.conf
4. Try your command again

**Comment by oneyesoneno** [comment]
still failed.. i am not familiar with IDEA stuff... facing many kind of errors... It will be good if there is more comprehensive guide... I will keep trying..

**Comment by phearnot** [comment]
@oneyesoneno it appears you are launching sbt from `src/test/resources` subdirectory. Please try launching sbt from the top-level directory, which is `C:\Users\Administrator\Desktop\Waves` in your case.

**Comment by jwaugh** [comment]
@phearnot has the right idea here. I had the same problem and had to CD up to the parent directory.
