### ISSUE TITLE
install waves ubuntu 14.04

### ISSUE THREAD

**Issue by mass34** [wavesplatform/Waves#680]
sudo dpkg -i waves*.deb
(Чтение базы данных … на данный момент установлено 169872 файла и каталога.)
Подготовка к распаковке waves-mainnet-systemd-0.6.4.deb …
/var/lib/dpkg/info/waves.prerm: 117: /var/lib/dpkg/info/waves.prerm: systemctl: not found
/var/lib/dpkg/info/waves.prerm: 118: /var/lib/dpkg/info/waves.prerm: systemctl: not found
waves wasn't even running!
Распаковывается waves (0.6.4) на замену (0.6.4) …
Настраивается пакет waves (0.6.4) …
/var/lib/dpkg/info/waves.postinst: 104: /var/lib/dpkg/info/waves.postinst: systemctl: not found
waves could not be registered
«/usr/share/waves/settings.conf» -> «/etc/waves.conf»
mv: не удалось выполнить stat для «/etc/waves.json»: Нет такого файла или каталога
dpkg: ошибка при обработке пакета waves (--install):
 подпроцесс установлен сценарий post-installation возвратил код ошибки 1
При обработке следующих пакетов произошли ошибки:
 waves

**Comment by alexeykiselev** [comment]
Solved since version 0.8
