### ISSUE TITLE
Testnet API needs updating

### ISSUE THREAD

**Issue by beregovoy68** [wavesplatform/Waves#75]
As far as I know some API issues have been fixed, but I can't see them on testnet. In particular, the node http://52.30.47.67:6869/ gives me the following.

Transfer request:
```
{  
   "recipient":"3N9UuGeWuDt9NfWbC5oEACHyRoeEMApXAeq",
   "timestamp":1479462208828,
   "assetId":"GAXAj8T4pSjunDqpz6Q3bit4fJJN9PD4t8AK8JZVSa5u",
   "amount":5000,
   "fee":100000,
   "senderPublicKey":"FJuErRxhV9JaFUwcYLabFK5ENvDRfyJbRz8FeVfYpBLn", 
   "signature":"4jWTZcRxuFpG4XdCbAhkiWdBjXMHEayPcEhk3yQ3oLYASJ7Fn8ij9C1nAQv61Z7Yo9DoLgy1fysGaaPGbxCWHrfT",
   "attachment":""
}
```
Response:
`{"error":1,"message":"failed to parse json message"}`

It works as expected if I use null as the attachment value (see https://github.com/wavesplatform/Waves/issues/72)

Request to the list of last transactions API (/transactions/address/3MtMoVbAHSitzohEvd6dJGR3kmJZHSePUkS/limit/50) gives me this (omitted other tx's to be short):
```
{  
         "type":3,
         "id":"GAXAj8T4pSjunDqpz6Q3bit4fJJN9PD4t8AK8JZVSa5u",
         "sender":"3MtMoVbAHSitzohEvd6dJGR3kmJZHSePUkS",
         "senderPublicKey":"FJuErRxhV9JaFUwcYLabFK5ENvDRfyJbRz8FeVfYpBLn",
         "assetId":"GAXAj8T4pSjunDqpz6Q3bit4fJJN9PD4t8AK8JZVSa5u",
         "name":"4wHKwCUAGbpPVg3gk",
         "description":"ziu6bcfZ1gm5fRDb9R79HUnHMoE",
         "quantity":100000000,
         "decimals":2,
         "reissuable":true,
         "fee":100000000,
         "timestamp":1479119236120,
         "signature":"2Tc7kQDPE2LnhtkuN4CPgFaMPcdP6wUAJPaWDnZ16HcCurezt8oJPyGwo7wDGF7r7TSeEgsQXDCqDC5Qqb9z6JUu"
}
```
Notice the name and description fields encoding.

BTW. The transaction info request works fine (/transactions/info/GAXAj8T4pSjunDqpz6Q3bit4fJJN9PD4t8AK8JZVSa5u)

**Comment by alexeykiselev** [comment]
Fixed by https://github.com/wavesplatform/Scorex/pull/192
