### ISSUE TITLE
Request: ability to define who's paying for transaction

### ISSUE THREAD

**Issue by pauliusuza** [wavesplatform/Waves#756]
Hello,

I'm building an app on Waves, and I stumbled across a problem with my use case:
1) Assuming I have 1000 users in my app - I create an address for each user on my main wallet
2) I am transferring a custom token from the main address to the user's address on the same wallet
3) After some time, I want to move part of the token the user has received to another address - transaction fails because the user's wallet does not have any Waves.

I could transfer some waves together with each token, however not all accounts will be making transactions - in this case Waves would simply be locked in those accounts.

Would it be possible to define which address pays for transaction, if both addresses (sender and recipient) belong to the same wallet?

**Comment by pauliusuza** [comment]
Any comments / response on this?

**Comment by alexeykiselev** [comment]
It is possible to pay transaction fee with tokens. It could be your own tokens, in this case you have to be a miner to accept your own tokens as fee. It could be inefficient in case of low stake, then you mine blocks once a week or even once a day. Or you can buy on DEX other miner's tokens, ask which is widely acceptable on #fullnode slack channel.

**Comment by pauliusuza** [comment]
@alexeykiselev I'm aware of that, I'm just proposing adding an API feature where you could optionally define "source of fee" address (A or B), if both addresses A and B belong to the same private key.

If you mine, buy, or otherwise acquire tokens they still need to be in address B in order to send a transaction from that address.

**Comment by alexeykiselev** [comment]
Actually it's not a good idea, because in this case everybody can use others accounts to pay their fees. So the only way is to pay your fee for yourself.

**Comment by pauliusuza** [comment]
Use case resolved by #1040, landed in 0.12.0.
https://docs.wavesplatform.com/technical-details/sponsored-fee.html
