### ISSUE TITLE
SEED: which log file?

### ISSUE THREAD

**Issue by hostragon-hosting** [wavesplatform/Waves#758]
Hi.
Assuming that one comments out seed = "BASE58SEED", which of the log files can one find the generated seeds? 

/var/log/syslog or /var/log/waves/waves.log?

Please could you point me to the right location as using already generated wallet is throwing up:

`Exception in thread "main" java.lang.AssertionError: assertion failed: Wrong char in Base58 string`

Once you comment that out in ubuntu-xenial, the app can start.

Thanks!

**Comment by alexeykiselev** [comment]
The automatically generated seed is written in `waves.log` file. Search for string `Your randomly generated seed is` to locate it.
