### ISSUE TITLE
Orderbook REST API call

### ISSUE THREAD

**Issue by romanga** [wavesplatform/Waves#762]
Is there a way to get Asset/Pair Orderbook through the REST API and if not is there a roadmap to support that?

Thanks

**Comment by vsuharnikov** [comment]
Hi! There is an official [wiki](https://github.com/wavesplatform/Waves/wiki/Matcher#order-book).

Example:
```
curl -s http://matcher.wavesnodes.com/matcher/orderbook/WAVES/Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck | jq .
```

Returns (the output was cut):
```json
{
  "timestamp": 1516194965616,
  "pair": {
    "amountAsset": "WAVES",
    "priceAsset": "Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck"
  },
  "bids": [
    {
      "price": 890,
      "amount": 13800000000
    }
  ],
  "asks": [
    {
      "price": 945,
      "amount": 5000000000
    }
  ]
}
```

But keep in mind:
1. `depth` doesn't work at this time. We'll fix it in the near future.
2. `price` is actually: `priceInSmallestUnit * 10 ^ (8 + priceAsset.decimals - amountAsset.decimals)`. For example, for WBTC (8 decimals) `priceInSmallestUnit` is 1 satoshi = 10^(-8). For WUSD (2 decimals) it is 1 cent = 0.01 $
3. You can get an information about all assets by ```curl http://matcher.wavesnodes.com/matcher/orderbook```

@koloale Am I right? :)
