### ISSUE TITLE
Proposal : Change the default accessrights to /usr/shared/waves 

### ISSUE THREAD

**Issue by realhagie** [wavesplatform/Waves#77]
In the default installation of the deb package the directory /usr/shared/waves is created and the config file is placed there.

The default right allow to view the directory and the settings file from anyone:

drwxr-xr-x   5 root root  4096 Nov 17 22:36 ./
drwxr-xr-x 148 root root  4096 Nov 17 22:36 ../
drwxr-xr-x   2 root root  4096 Nov 17 22:36 bin/
drwxr-xr-x   2 root root  4096 Nov 17 22:39 conf/
drwxr-xr-x   2 root root 12288 Nov 17 22:36 lib/
lrwxrwxrwx   1 root root    14 Nov 17 16:56 logs -> /var/log/waves/
-rw-r--r--   1 root root  1320 Nov 18 10:57 settings.json

Also the owner could be moved to waves:waves

**Comment by bcdev-** [comment]
I agree. *nobody except root and waves should be able to read settings.json*!
