### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by ossybel** [wavesplatform/Waves#770]
Win 10. v 0.8.10 .jar When airdrops is going log file is grow up to 900 MB, Windows is stalling, node is shutting down.

**Comment by ossybel** [comment]
В общем, по порядку... Запустил 0.8.10, всё работало норм, пока не начались эирдропы, лог файл из-а этого распухает до 900-920 мегабайт за полдня и винда зависает наглухо, пришлось перезагружать кнопкой. Затем я запустил с параметром -Dlogback.file.level=INFO, лог файл не большой, около 400 килобайт, но нода зависает через 15-30 минут, идут хендшейки, но обработки блоков нет и swagger не отвечает. Вернулся на 0.8.8 и вот уже пару часов без проблем...

**Comment by alexeykiselev** [comment]
It's better to use DEBUG level only then needed.
