### ISSUE TITLE
Use DEX via javascript code

### ISSUE THREAD

**Issue by manidlou** [wavesplatform/Waves#778]
I couldn't find any API to use DEX via code. I want to use DEX via javascript code. I appreciate if someone help me on that! Thanks.

**Comment by mrmading** [comment]
I think you want this https://github.com/wavesplatform/Waves/wiki/Matcher

**Comment by Aidin** [comment]
thanks but what is the base url?

**Comment by manidlou** [comment]
@Aidin I've used these urls for main and test nets:

Mainnet: https://github.com/xenohunter/waves-api/blob/master/src/constants.ts#L58
Testnet: https://github.com/xenohunter/waves-api/blob/master/src/constants.ts#L65

**Comment by Aidin** [comment]
Thanks!
