### ISSUE TITLE
Add old address to wallet (full node)

### ISSUE THREAD

**Issue by yupasik** [wavesplatform/Waves#82]
Hello!
As i see, method /waves/address is deprecated in the full node.
There is an only one way to create(add) address in the wallet now: POST /addresses
Is it possible to add address from my Web wallet (https://waveswallet.io/) into Full node wallet using public key (like /waves/address)?
Thanks

**Comment by Tolsi** [comment]
No, for now. You can use your seed from the lite client in your node.
