### ISSUE TITLE
Mining in custom token

### ISSUE THREAD

**Issue by renickj** [wavesplatform/Waves#820]
Hi I am new to blockchain & waves, I am trying to build the private blockchain with custom token.
Managed to build the private blockchain and also created custom token. 
But couldn't understand how to integrate the custom token to the private blockchain. Could anyone please help me with the details of integrating custom tokens.
My idea is building the private blockchain and using custom token to mine and transact.

**Comment by alexeykiselev** [comment]
Hello,
the mining is possible using default currency only, which is always called Waves, even on custom blockchains. It's impossible to mine user created assets (tokens).
