### ISSUE TITLE
How can I make my own site ?

### ISSUE THREAD

**Issue by admicaa** [wavesplatform/Waves#821]
We wanna make a site with our own (currency) I'm the developer and I don't understand what should I do. 
should I send API requests to the wave platform site or to my own site and if it was for my own site that means that I must install waves platform node on the server?? How could I do that and can I integrate it with PHP or not any help ??
anyone had done this before tell me only the idea

**Comment by WebDevDen** [comment]
I'm making something like this now. Idea is that you running waves node as server or something like that(like Node.js server for example or even like Apache with it's own configurations) and then making requests to it from your site with PHP or whatever (list of requests is available in waves wiki) to do all what you need. But I could not connect my waves node with wallet (if more precisely then I connected but my waves balance was 1,6 WAVES and in node I had 0, it has his own balance system that I don't understand for now). Maybe you would do better. Good luck.

**Comment by alexeykiselev** [comment]
@admicaa You can do both, it's possible to perform some requests on our [public nodes](https://nodes.wavesnodes.com). Or you can install your own node on your dev computer or on a server following instructions on [Wiki](https://github.com/wavesplatform/Waves/wiki/How-to-install-Waves-node). The main difference is that you can't use the built-in wallet on a public node.

@WebDevDen In your case it seems like you haven't configured your node correctly. By default the node will create a new wallet address for you at first start. Please, check the wallet address in your node using API's method `/addresses`.  To make the node use your wallet address you have to provide the **encoded** seed in its configuration file. Read [about configuration file format in the Wiki](https://github.com/wavesplatform/Waves/wiki/Waves-Node-Configuration-File).
