### ISSUE TITLE
Required amount calculation question

### ISSUE THREAD

**Issue by me21** [wavesplatform/Waves#828]
I wanted to buy 11.59 EUR in EUR/USD pair. The order is: `{'price': 1.2269, 'amount': 100.0}`. So it seems that I need 14.22 USD. But I get message from server:

```
Order Rejected - Not enough tradable balance: Map(Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck -> 1422, WAVES -> 15271378), needs: OpenPortfolio(Map(WAVES -> 300000, Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck -> 1425))
```
Why do I need 14.25 USD? Where did extra 0.03 USD come from?
This is unlike my previous question, as there are no other orders with different prices involved.

**Comment by alexeykiselev** [comment]
I think it's rounding problem. Do you use Waves Wallet or trying to work with DEX using API? If latter, check the actual long values your software send to matcher.
