### ISSUE TITLE
Is it possible to charge fees in my tokens? 

### ISSUE THREAD

**Issue by AtixD** [wavesplatform/Waves#830]
What i do:

nodes.wavesnodes.com/assets/broadcast/transfer

{ method: 'POST',
  headers:
   { Accept: 'application/json',
     'Content-Type': 'application/json;charset=UTF-8' },
  body: '{"senderPublicKey":"**************","assetId":"Bvvf3adjyzZFD7JLLbf2LtSaWNjKXp7X4vABKiPXUvU8","feeAssetId":"Bvvf3adjyzZFD7JLLbf2LtSaWNjKXp7X4vABKiPXUvU8","timestamp":1518180276194,"amount":1000000,"fee":100000,"recipient":"address:3PMgh8ra7v9USWUJxUCxKQKr6PM3MgqNVR8","attachment":"fC7d31KyE8ggRahvkqAFbvAwKM","signature":"4qdzXEaGT4rkFhZXZQVGYw9oC4phfeNZSEkbfa4HMmnMm1A8ZYudef7vvF9FK7s1LX*****3wQ37okDAEKSmrzqc"}' }
What i get:

{
  "error": 199,
  "message": "Minimum fee is not defined for TransactionAssetFee(4, Some(Bvvf3adjyzZFD7JLLbf2LtSaWNjKXp7X4vABKiPXUvU8))"
}

Is it possible to charge fees in my tokens?

**Comment by alexeykiselev** [comment]
Yes, it's possible. But you have to post your transaction to the node which accepts your asset as fee. It could be your own node. Waves public nodes doesn't accept your asset as fee, they accept only Waves as fee.
