### ISSUE TITLE
Adding Asset to private block chain

### ISSUE THREAD

**Issue by renickj** [wavesplatform/Waves#832]
I have created a private block chain. How to add initial Asset?
For example, how to add Waves into the private block chain? or add custom tokens as assets.

**Comment by alexeykiselev** [comment]
Waves as a base currency will be added to a blockchain by default. Then you setup genesis transactions  for the custom blockchain you do it using Waves. To add new tokens you have to issue them using [API](https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API#post-assetsissue) or connected wallet software.

**Comment by renickj** [comment]
Thanks. Yes, I am able to see the balance using API, when I tried to use the example shared.
But When I tried to create a genesis block with a 15 word seed text, I am unable to get the balance.
Do we have any specific restriction of seed text, for genesis.
