### ISSUE TITLE
ERC20 token Swap in DEX?

### ISSUE THREAD

**Issue by taghvaei** [wavesplatform/Waves#835]
is there any way that let us to use DEX (via API,...) and create an environment for ERC20 token swap with Waves Token one-to-one ? or do the same inside the Waves DEX
Scenario: an ICO distributed ERC20 tokens to users, then built their platform with Waves generated token and now want's to ask ERC20 token holders to deposit their token in DEX and swap with exact same amount of Waves generated token/

**Comment by alexeykiselev** [comment]
The possible solution:
1. Issue tokens on Waves to represent your ERC20 tokens
2. Implement a gateway to convert waves tokens to ERC20 tokens and vice versa
3. Trade waves tokens on DEX

So, then user sends a ERC20 token on ETH blockchain to the gateway address, it receives the same amount of tokens on its waves address. Same in opposite direction.

**Comment by taghvaei** [comment]
@alexeykiselev thanks, but the tricky part is
 "user sends a ERC20 token on ETH blockchain to the gateway address, it receives the same amount of tokens on its waves address."
How this possible when they are in two different blockchain ?

**Comment by alexeykiselev** [comment]
it's how gateway works, it looks in both blockchains and have addresses in both

**Comment by taghvaei** [comment]
@alexeykiselev looks good, can you give me some reference about it

**Comment by alexeykiselev** [comment]
You have to implement the service that can use the [API](https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API) of Waves node and the API of ETH node. Wait for new transactions on both and create a mirror transaction.

**Comment by xema2110** [comment]
https://github.com/TOKENLAND/WavesGatewayFramework  Can this link help?

**Comment by pasomoaikai** [comment]
@alexeykiselev, in a situation were the token is a waves base token and needs to be swapped to an erc20 token how do you go about that?

**Comment by pasomoaikai** [comment]
Is there a link on how to conduct the swap?

**Comment by ragazzo-br** [comment]
it really will be a good deal, I have thousands to exchanve for waves tokens....
