### ISSUE TITLE
Order rejected due to insufficient tradable balance

### ISSUE THREAD

**Issue by me21** [wavesplatform/Waves#839]
The account 3PGrm6a2YsnNi1fjx3DYQyiHg22CEzpwVqs (https://wavesdesk.com/account/3PGrm6a2YsnNi1fjx3DYQyiHg22CEzpwVqs#trade) has 266.69019327 Simdaq Token in its balance.

When I try to sell 28.68158127 (or any other amount) of it using PyWaves, I get:
```
[ERROR] Order Rejected - Not enough tradable balance: Map(CBik4JEmsoPZKKATnShULYj2ebUao5aada9N1XGznEET -> 0, WAVES -> 
14722185544), needs: OpenPortfolio(Map(WAVES -> 0, CBik4JEmsoPZKKATnShULYj2ebUao5aada9N1XGznEET -> 2868158127))
```

How come?
The first such attempt was at Feb 12 20:37:59 UTC-7, the last at Feb 13 20:14:01 UTC-7.
On 14 Feb 2018 07:47:33 UTC-7 I've finally managed to sell it.

**Comment by alexeykiselev** [comment]
The balance for the given address and asset is 0.
```
https://nodes.wavesnodes.com/assets/balance/3PGrm6a2YsnNi1fjx3DYQyiHg22CEzpwVqs/CBik4JEmsoPZKKATnShULYj2ebUao5aada9N1XGznEET
```

returns:

```
{
  "address" : "3PGrm6a2YsnNi1fjx3DYQyiHg22CEzpwVqs",
  "assetId" : "CBik4JEmsoPZKKATnShULYj2ebUao5aada9N1XGznEET",
  "balance" : 0
}
```

**Comment by me21** [comment]
Yeah, it's zero now, because, as I've written,  I've finally managed to sell the asset. Don't you have full transaction history? But why sell orders were rejected before?

**Comment by alexeykiselev** [comment]
There two reasons why order could be rejected. First, not enough tradable balance (your case) and second the order expiration period is too short (order expired on arrival).
You tradable balance is the actual balance and all orders that are not matched as if they already matched (it could be negative). Possibly you have set too many orders.

**Comment by me21** [comment]
Is it possible to get tradable balance with API in addition to actual balance?

**Comment by alexeykiselev** [comment]
Yes, GET /matcher/orderbook/{amountAsset}/{priceAsset}/tradableBalance/{address}

**Comment by me21** [comment]
Please update https://github.com/wavesplatform/Waves/wiki/Matcher page to include this and possibly other additions not mentioned there.
