### ISSUE TITLE
Additional node in private chain

### ISSUE THREAD

**Issue by renickj** [wavesplatform/Waves#842]
Hi, How to create additional node in private chain,
What will be the blockchain. type = CUSTOM
When I provide custom its asking for custom functionality and then the genesis block.
When I stated the node without 'type' its considering the blockchain.id as 'T', which is not right.
Please share the settings for additional node in private chain.

**Comment by alexeykiselev** [comment]
Hello,
please, follow the [documentation](https://github.com/wavesplatform/Waves/wiki/Creating-a-private-Waves-blockchain-network) and update it with the missing functionality settings from https://github.com/wavesplatform/Waves/wiki/Waves-Node-Configuration-File.
Then you see 'T' as a network ID it means that the node started with default Testnet settings.

**Comment by renickj** [comment]
hi, this is not about testnet, sorry,my private chain genesis node is ready. I am planning to add additional nodes to my private chain. the issue is with configuration of additional node. Lets say if my "address-scheme-character = "C"  then my additional nodes should share the same is it? it cant be T or W. Is there any specific configuration that has to be made on the additional nodes.

**Comment by alexeykiselev** [comment]
Yes, you have to share exactly the same configuration file among all of your nodes.
