### ISSUE TITLE
GET /matcher/orders/{address} question

### ISSUE THREAD

**Issue by ilyacherevkov** [wavesplatform/Waves#843]
How do I execute `GET /matcher/orders/{address}` method?

I was able to receive all orders history in another method `GET /matcher/orderbook/{publicKey}` by specifying  headers
```
{
    "Accept": "application/json", 
    "Timestamp": XXX,
    "Signature": YYY,
} 
```
where signature was generated from PublicKey + Timestamp bytes.

But I'm confused which headers should I send to  `/matcher/orders/{address}` method and do I need to generate signature and which parameters should I use then for its generation?

**Comment by alexeykiselev** [comment]
This method is protected by api-key. So, you can't use it on our public matcher.
