### ISSUE TITLE
Using API to fetch human readable transaction data

### ISSUE THREAD

**Issue by AYapejian** [wavesplatform/Waves#854]
I'm trying to figure out how to download all transactions for my address since I, surprisingly, can't find this functionality anywhere natively in either the beta client (transactions tab broken for me, opened issue already) or the original client which only shows recent transactions.  The problem I'm running into now seems to be around getting asset information, heres what I'm doing currently.  

I guess my main question surrounds the last item below, where really all I want to do is lookup an asset by an id and get it's details ( including symbol and precision ), is there a way to do this? Didn't see it in the api and the steps below are less than ideal.

1. GET `transactions/address/${address}/limit/${limit}` with a large limit, say 5000 as I don't see anything about pagintation support
2. Get all symbols from `https://marketdata.wavesplatform.com/api/symbols`
3. Fetch all markets from `https://marketdata.wavesplatform.com/api/markets`
4. Loop through transactions
	- Try and see if `assetId` and/or `feeAsset` exits in fetched symbols, if so grab the symbol text. 
	- If `assetId` or `feeAsset` is undefined then assume that the asset is 'WAVES' ( think this is what the docs said, although if type = 7 then in orders the id is actually `WAVES`?  )
	- If the transaction is of `type === 7` ( no documentation found on that type, looks like dex orders)
		- Do a property key search for keys that start with text `order` (usually `order1` and `order2`, this should really be an array instead, but... )
		- Look up `assetPair.priceAsset` and `assetPair.amountAsset` in symbols table to find symbol
		- Also see if a market exists from step 3 with both matching `amountAsset` and `priceAsset`
			- If market was found get the `amountAssetDecimals` and `priceAssetDecimals` values
			- Use above values to calculate the human readable asset denomination ( reffered to as `wavelets` and `asset'lets` in the docs, something like "api amount / 10 ^ asset precision" I believe )
	- If transaction is not `type === 7` then find any market with matching priceAsset or amountAsset to use the decimals value for calculating human readable amounts like mentioned above

**Comment by vsuharnikov** [comment]
Hi!

```
I want to do is lookup an asset by an id and get it's details ( including symbol and precision ), is there a way to do this?
```
If you have its id, you can get an information through Node REST API. E.g. for asset with id of `BmcArNN9VnKAp3HbvpKaoE3utwEXqvP1UjunS9DVKdGS`:
```
$ curl https://nodes.wavesnodes.com/transactions/info/BmcArNN9VnKAp3HbvpKaoE3utwEXqvP1UjunS9DVKdGS
{
  "type" : 3,
  "id" : "BmcArNN9VnKAp3HbvpKaoE3utwEXqvP1UjunS9DVKdGS",
  "sender" : "3PMHtD2YwoqaEbGVKsrRZpMHpsxpFvU9eH9",
  "senderPublicKey" : "2vPMYssT5npF9cK9enMbJX14qBQSbRgWfh9Kxj9XMEYm",
  "fee" : 100000000,
  "timestamp" : 1503515511141,
  "signature" : "3KV3z4Gn7pbHMUuDQHszDad89pydUyRrRoUKjv7b5CnevSX4DWFrtQhxUau3NLmVK5Hdv1rGyHk3en1UMm4gYyiq",
  "assetId" : "BmcArNN9VnKAp3HbvpKaoE3utwEXqvP1UjunS9DVKdGS",
  "name" : "RewardMob",
  "description" : "RewardMob token for the RewardMob.com platform.",
  "quantity" : 25000000000000000,
  "decimals" : 8,
  "reissuable" : true,
  "height" : 636511
}
```
But you should know, it doesn't consider burn and reissue transaction (but we are working on it).

---
```
1. GET transactions/address/${address}/limit/${limit} with a large limit, say 5000 as I don't see anything about pagintation support
```
The pagination here is on the way, we are working on it :) The maximal limit is 10000 now.

---
```
3. Fetch all markets from https://marketdata.wavesplatform.com/api/markets
```
I'd recommend use to use Matcher REST API here. E.g.:
```
$ curl -s https://matcher.wavesnodes.com/matcher/orderbook | head -n 20
{
  "matcherPublicKey" : "7kPFrHDiGw1rCm7LPszuECwWYL3dMf6iMifLRDJQZMzy",
  "markets" : [ {
    "amountAsset" : "GZqrTJDvV8JqNWCvVQabSxwAEQeBBUSdRwxzobUPo5Xz",
    "amountAssetName" : "travelerstoken",
    "amountAssetInfo" : {
      "decimals" : 8
    },
    "priceAsset" : "4XThgnbpjkRtzn4dTMK76r8XpHLyKAtsqzNpYFweLxXV",
    "priceAssetName" : "Sensatori Token",
    "priceAssetInfo" : {
      "decimals" : 8
    },
    "created" : 1520341660907
  }, {
    "amountAsset" : "FZ3xVVBB5YAt65wZFMdWKH4RjQGEjrJT9jqkb37UdwWL",
    "amountAssetName" : "PonziCoin.org",
    "amountAssetInfo" : {
      "decimals" : 8
    },
```

---
```
If assetId or feeAsset is undefined then assume that the asset is 'WAVES'
```
Right!

---
```
… if type = 7 then in orders the id is actually WAVES?
```
Right, if type is 7, this is an exchange transaction. It is created by the DEX and the only fee is available here is WAVES.
But! Which assets a trader spends and receives are determined by `assetPair`.
For example, we have a pair `WAVES/WBTC` (amount=`WAVES`, price=`WBTC`). If this is a `SELL` order (see `orderType` in `order1` / `order2`), the trader spent `WAVES` and receives `WBTC`. If it is a `BUY` one, it spends `WBTC` and receives `WAVES`.

---
```
… (usually order1 and order2, this should really be an array instead, but... )
```
They are forever `order1` and `order2`. DEX matches an ask (`order1` or `order2`) with the bid (`order2` or `order1`).

---
```
Use above values to calculate the human readable asset denomination ( reffered to as wavelets and asset'lets in the docs, something like "api amount / 10 ^ asset precision" I believe )
```
Right!

---
```
If transaction is not type === 7 then find any market with matching priceAsset or amountAsset to use the decimals value for calculating human readable amounts like mentioned above
```
Actually, only an `ExchangeTransaction` has `priceAsset` and `amountAsset`. For example, a `TransferTransaction` contains `fee` with `feeAssetId` and `ammount` with `assetId`.

---
Also:
* there is a [WavesExplorer](https://wavesexplorer.com). Try it: https://wavesexplorer.com/blocks/906793 , it's really helpful ;)
* we have a task to create a full swagger specification to all methods and all
