### ISSUE TITLE
     "error": 112,     "message": "State check failed. Reason: invalid signature",

### ISSUE THREAD

**Issue by Shashwat78** [wavesplatform/Waves#856]
i am hitting request from postman like below
http://0.0.0.0:6861/assets/broadcast/issue

i am giving payload like below

{
  "name": "Test Asset 1",
  "description": "Some description",  
  "sender": "3JfE6tjeT7PnpuDQKxiVNLn4TJUFhuMaaT5",
  "senderPublicKey": "GbGEY3XVc2ohdv6hQBukVKSjQyqP8rjQ8Kigkj6bL57S",
  "quantity": 100000000000,
  "decimals": 8,
  "reissuable": true,
  "fee": 100000000,
  "timestamp": 1479287120875,
  "signature": "2uwcuLxqHUGNpm4cJeN2cPFavYPLsZmjRcMLwSsvdgX3aDnur5Eb5FLT5FVbNzdoNemvpksMLjfoVMVLHunJ65zK"
}

i got error , something like below :
    "error": 112,
    "message": "State check failed. Reason: invalid signature",
    "tx": {
           "type": 3,
        "id": "Cvzh5LwQmGgG9ZdKNS248mYuUqEomhuvPpGw8ijoBJwW",

NOTE : i am giving  signature from  GenesisBlockGenerator result
 "signature": "2uwcuLxqHUGNpm4cJeN2cPFavYPLsZmjRcMLwSsvdgX3aDnur5Eb5FLT5FVbNzdoNemvpksMLjfoVMVLHunJ65zK"

Running (fork) tools.GenesisBlockGenerator src/test/resources/genesis.example.conf
[info] Addresses:
[info] (0):
[info]  Seed text:           foo0
[info]  Seed:                3csAfH
[info]  Account seed:        58zgAnBg775J6NKd4qVtfeX3m5TBMeizHNY9STvm2N87
[info]  Private account key: FYLXp1ecxQ6WCPD4axTotHU9RVfPCBLfSeKx1XSCyvdT
[info]  Public account key:  GbGEY3XVc2ohdv6hQBukVKSTQyqP8rjQ8Kigkj6bL57S
[info]  Account address:     3JfE6tjeT7PnpuDQKxiVNLn4TJUFhuMaaT5
[info] Settings:
[info] genesis {
[info]   average-block-delay: 60000ms
[info]   initial-base-target: 153722867
[info]   timestamp: 1500635421931
[info]   block-timestamp: 1500635421931
[info]   signature: "2uwcuLxqHUGNpm4cJeN2cPFavYPLsZmjRcMLwSsvdgX3aDnur5Eb5FLT5FVbNzdoNemvpksMLjfoVMVLHunJ65zK"
[info]   initial-balance: 10000000000000000
[info]   transactions = [
[info]     {recipient: "3JfE6tjeT7PnpuDQKxiVNLn4TJUFhuMaaT5", amount: 10000000000000}
[info]   ]
[info] }

please help ??

**Comment by Shashwat78** [comment]
is anyone solves this problem ??

**Comment by phearnot** [comment]
You can't reuse signatures, each new transaction needs to be signed individually. You can use [private API](https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API#post-assetsissue) to sign transactions with your node's private key.
