### ISSUE TITLE
API problem: Asset transfer transaction disappears in the destination account

### ISSUE THREAD

**Issue by beregovoy68** [wavesplatform/Waves#87]
### Steps to reproduce:
1. Sign in to your "Waves" account with assets. (1)
2. Create another one account (2)
3. Send to the second account(2) a few assets

### Actual Result:
you see that transaction only when doesn't confirmed yet
After full confirmation this transaction disappears

You'll see new transaction in the account (1) tx list, but you won't see this tx in the account (2) tx list.

### Proof
account (1): 3MtMoVbAHSitzohEvd6dJGR3kmJZHSePUkS
account (2): 3N9UuGeWuDt9NfWbC5oEACHyRoeEMApXAeq

Transaction with id=D4awUpuZ5vSkigHhqagexupAC1JZ1r4nDdh6ixhnstMF is visible in the transactions list of the account (1): http://testnet.wavesexplorer.com/address/3MtMoVbAHSitzohEvd6dJGR3kmJZHSePUkS (top tx in the list)
The same transaction is not visible in the transactions list of the account (2):
http://testnet.wavesexplorer.com/address/3N9UuGeWuDt9NfWbC5oEACHyRoeEMApXAeq

This API method /transactions/address/3N9UuGeWuDt9NfWbC5oEACHyRoeEMApXAeq/limit/50 just doesn't return the incoming transaction for some reason.

**Comment by alexeykiselev** [comment]
fixed by https://github.com/wavesplatform/Scorex/pull/195
