### ISSUE TITLE
Withdraw asset API

### ISSUE THREAD

**Issue by me21** [wavesplatform/Waves#878]
There is UI in Lite client for withdrawing BTC/ETH/LTC/ZEC. But how can it be done via API? I could not find any information on it.
The browser uses /assets/broadcast/transfer in that case, sending the asset to gateway. But how do I form the request properly?

**Comment by petermz** [comment]
There's some info here:
https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API
https://github.com/wavesplatform/Waves/wiki/Data-Structures

You might want to use some library such as WavesJ or pyWaves to sign your transaction, it's tedious to do by hand

**Comment by me21** [comment]
I am using pyWaves. But I couldn't find any API, neither in Waves wiki nor in pyWaves implementation, which is used to withdraw BTC/ETH/LTC/ZEC to external addresses (for example, to withdraw BTC to Bitcoin wallet address, not Waves network address).
Could you please provide any example of doing it?
I assume that transfer transaction should be used for that, but I cannot find any field to specify Bitcoin wallet address there. Or Ethereum address, etc.

**Comment by alexeykiselev** [comment]
At the moment it is not possible to withdraw through official gateways without accessing their APIs. First you have to link your waves address to your bitcoin address on the gateway. You post both addresses and receive a link id. Later you can use this link id as an attachment to transfer transaction. There is Attachment field in Transfer transaction that you can use to send additional information to a receiver.

**Comment by me21** [comment]
@alexeykiselev Thanks! Can I find the description of official gateway API somewhere?

**Comment by vsuharnikov** [comment]
@me21 Sorry, it's private
