### ISSUE TITLE
API KEY wont work for post

### ISSUE THREAD

**Issue by kiahmed** [wavesplatform/Waves#883]
I am running a test node. rest api key has is api-key-hash = "H6nsiifwYKYEx6YzYD7woP1XCn72RVvx6tC1zjjLXqsu" mentioned like this in the config file, but when I try to use it in a POST request with API_KEY like it says in the api doc it always fails with the following error:
{
  "error" : 2,
  "message" : "Provided API key is not correct"
}

**Comment by alexeykiselev** [comment]
You have to send with a request the API_KEY itself, not its hash. The node will hash received API_KEY string and compare the hash with the hash from the configuration file. 
I have to warn you that some browsers will strip out not well formatted headers, but our node supports both `api_key`and `Api-Key` headers since version 0.9.

**Comment by kiahmed** [comment]
how do I get actual key from hash? Also, I am not sending through browser but postman..so it has to be lower case api_key?

**Comment by alexeykiselev** [comment]
Where is no way to get something from hash! But the default api_key is "ridethewaves!" and your hash is the hash of this string. Yes, the header itself should be in lowercase.

**Comment by kiahmed** [comment]
well, tried it but looks like now all /address related request hangs! not sure why..any idea? I tried other resources like localhost:6869/peers/connected this works

**Comment by vsuharnikov** [comment]
The right header is `X-API-Key`, but `api_key` is still supported. Could you make a `curl` request and paste the output here?

**Comment by kiahmed** [comment]
here is the request 
curl -X POST http://localhost:6869/addresses -H 'api_key: ridethewaves!'  
will never return anything , but the same GET request works to return the list of addresses. Also, tried with X-API-Key , but same result :(

**Comment by vsuharnikov** [comment]
Could you try:
1. Clean or backup `waves` directory, e.g. clean: `rm -rf ~/waves`
2. Download the latest release from releases page:
   ```
   wget https://github.com/wavesplatform/Waves/releases/download/v0.10.2/waves-all-0.10.2.jar
   ```
3. Check your JRE version: `java -version`
4. Run it:
    1. If you have Java9: `java -XX:+IgnoreUnrecognizedVMOptions --add-modules=java.xml.bind -jar waves-all-0.10.2.jar`
    2. If you have Java8: `java -jar waves-all-0.10.2.jar`
5. Make a curl request: `curl -X POST http://localhost:6869/addresses -H 'api_key: ridethewaves!'`

It should work. Next, please say, how your steps differs from these and we will determine the problem.

**Comment by vsuharnikov** [comment]
If you run it from SBT, try to use this patch: https://github.com/wavesplatform/Waves/pull/892/files

**Comment by kiahmed** [comment]
well, interesting it just worked without doing anything. I just restarted the daemon. My concern is how how I change the api key ? Or can I use basic auth user/password in config file?

**Comment by vsuharnikov** [comment]
You should use basic auth if want to protect all API methods. The API key is required to protect possibly dangerous actions.
To change it:
1. Use the Node REST API: `/utils/hash/secure`.
2. Enter your `raw_key` to it, you will get an `encoded_key`.
3. Paste the `encoded_key` into `waves.rest-api.api-key-hash` of config.
4. Restart the node and make requests to protected actions with `X-API-Key: raw_key`.

**Comment by vsuharnikov** [comment]
For testnet: http://testnet.wavesexplorer.com/faucet

**Comment by rio-coffe** [comment]
So, just , clean data dir ,   
rm -rdf /var/lib/waves/data
remove wallet file
rm -rdf /var/lib/waves/wallet

put to config in section Password  your password  

get hash

curl --request POST --url http://127.0.0.1:4444/utils/hash/secure --data 'yourpassword'

returned hashpassword

put in config in section api hash this hashpassword

start node

try

curl -X POST http://127.0.0.1:4444/addresses -H 'api_key: yourpassword'
