### ISSUE TITLE
Incomplete response from marketdata.wavesplatform.com/api/symbols

### ISSUE THREAD

**Issue by me21** [wavesplatform/Waves#893]
There are some assets not listed. For example, there is no symbol for Symdaq Token, asset id: CBik4JEmsoPZKKATnShULYj2ebUao5aada9N1XGznEET.

**Comment by vsuharnikov** [comment]
As I know, `marketdata` is a third-party tool that is hosted on our subdomain. You could use the node api to get an asset information:
```
$ curl https://nodes.wavesnodes.com/transactions/info/CBik4JEmsoPZKKATnShULYj2ebUao5aada9N1XGznEET
{
  "type" : 3,
  "id" : "CBik4JEmsoPZKKATnShULYj2ebUao5aada9N1XGznEET",
  "sender" : "3PPKZfALTDLEyAgTjQahjKNNcWpgGcAqmye",
  "senderPublicKey" : "2wtEGZ8nLSSMSwA3s9cgzF985LqBmArJZFvkmzQTRreg",
  "fee" : 100000000,
  "timestamp" : 1517519290438,
  "signature" : "5WyR8HYjyrxujEJzS8KRqCWcjshNnTcfDigfPCGWNshRtHTTidvYyjkLVgdZsFZDcKVJuhsCEAPFKefNEhxtpFd8",
  "assetId" : "CBik4JEmsoPZKKATnShULYj2ebUao5aada9N1XGznEET",
  "name" : "Simdaq Token",
  "description" : "Internal currency of Simdaq trading platform",
  "quantity" : 2500000000000000,
  "decimals" : 8,
  "reissuable" : false,
  "height" : 861447
}
```

**Comment by BlackTurtle123** [comment]
Yes Marketdata is third party and needs to be updated manually by the owner from this third party tool.
However Waves is/was using this for all the clients.

**Comment by me21** [comment]
Is Marketdata bug tracker available somewhere?

**Comment by alexeykiselev** [comment]
The original repository of Marketdata is https://github.com/alexeykiselev/WavesDataFeed. I've cloned the Marketdata and fixed few errors https://github.com/alexeykiselev/WavesDataFeed.

**Comment by Georgy45** [comment]
> The original repository of Marketdata is https://github.com/alexeykiselev/WavesDataFeed. I've cloned the Marketdata and fixed few errors https://github.com/alexeykiselev/WavesDataFeed.

Hi, did I missed something ? When I run it, even after complete sync with blockchain, I still have empty responses with /market, /trades, etc.... Only /symbols work. Thank you.

**Comment by alexeykiselev** [comment]
@Georgy45 The data for some routes are taken from the node. So it could be empty if you shutdown the node used to sync with.

**Comment by Georgy45** [comment]
> @Georgy45 The data for some routes are taken from the node. So it could be empty if you shutdown the node used to sync with.

Thank you! Maybe it's my issue: I try with ip of public nodes, I dont have one. So even if I sync, the routes are empty.
