### ISSUE TITLE
is there walletnotify option like bitcoin config

### ISSUE THREAD

**Issue by top1st** [wavesplatform/Waves#894]
I want to know how to config wallet notify if there is new transaction.

**Comment by BlackTurtle123** [comment]
http://ws.wavesplatform.com/

**Comment by top1st** [comment]
Hello Thank you for your reply. Could you provide testnet wallet notify url?

**Comment by BlackTurtle123** [comment]
I don't know that one. I am sorry :D

**Comment by monroid** [comment]
HI @top1st,
for now we don't have such functionality, and there are only some ideas how to implement that notifications. If you could create a feature request on our forum https://forum.wavesplatform.com, it would be great!
