### ISSUE TITLE
Asset naming conventions

### ISSUE THREAD

**Issue by aquarius777** [wavesplatform/Waves#91]
In order to avoid confusion creating assets under the same name like existing ones should be prohibited.

**Comment by Tolsi** [comment]
In our Whitepaper it was originally intended so.

**Comment by omwave777** [comment]
Also in order to avoid confusion there should be some protected names like USD, BTC, EUR, IBM, Wave, Waves etc...

**Comment by flip909** [comment]
Hi, Why can People Issue Assets with same names ( I know the identifier is different but this is not easy to see.) People will have to start referring to Assets by there Identifiers..

**Comment by flip909** [comment]
If I created a token called Incent then gave it to a someone who didn't already have an original Incent token, How would they know? They would assume that they had real one. Until perhaps they had another off someone, that had different identifier or of they went off to double check their identifiers with trusted sources online.

**Comment by aquarius777** [comment]
In order to prevent name squatting, i.e. not to let somebody take wBTC, BTC, ETH, wETH as an asset name before Waves Platform does.
