### ISSUE TITLE
Get Publickey and private key of an address?

### ISSUE THREAD

**Issue by geethsameer686** [wavesplatform/Waves#915]
I am using **GET /addresses API** to get the address. When I want to transfer waves from one address to another using **POST /assets/broadcast/transfer**, I have to request with
```
"assetId" [optional] - Asset ID to transfer or omit that param when transfer WAVES, Base58-encoded
"senderPublicKey" - Sender account's public key, Base58-encoded
"recipient" - Recipient account's address, Base58-encoded
"fee" - Transaction fee for Asset transfer, min = 100000 (WAVElets)
"feeAssetId" [optional] - Asset ID of transaction fee. WAVES by default, if empty or absent 
"amount" - amount of asset'lets (or wavelets) to transfer
"attachment" - Arbitrary additional data included in transaction, max length is 140 bytes, Base58-encoded
"timestamp" - Transaction timestamp
"signature" - Signature of all transaction data, Base58-encoded

```
Here how to get Public Key and Private key (to sign the transaction) of an address (  '3MwMwdzo6k1wwDE8JgiZmbM7nXEL6xmftPc')

**Comment by Tolsi** [comment]
You can create an account yourself using [this doc] or [python library](https://github.com/wavesplatform/Waves/wiki/Cryptographic-practical-details)(https://github.com/PyWaves/PyWaves), but it's impossible to extract private key to sign the transaction from the node wallet using API for now. Also you can use a code of node to create an app to do this, but it's easier to create a new account without the node.

**Comment by geethsameer686** [comment]
How can I get the asset id's of all the tokens on waves platform? I can't find any API call to get the list of all the tokens with the asset ids. Could you tell me the process of how to get all the tokens with asset ids?
Thanks.

**Comment by Tolsi** [comment]
Use http://dev.pywaves.org/assets/

**Comment by geethsameer686** [comment]
@Tolsi Thanks a lot.

**Comment by geethsameer686** [comment]
@Tolsi I used the python library which you recommended me to use. Along with that I am using my local node as a testnet. I can't send the transaction. I will post the code and error. Please tell me where am I doing wrong.

```
import pywaves as pw
pw.setNode(node = 'http://127.0.0.1:6869',chain = 'testnet')
address = '3Mq6YmrnfoSt5T36i3S2XPXpXh8kP87DUw4'
publicKey = '9u6mN4kN8U7iQVsyNaru7ko6VV3E3pQ6sqcmmDwM6k7a'
privateKey = 'GczfiQJoqkp4E4pXGj7wicx53nckPyG46EWChEd9brzM'
myAddress = pw.Address(privateKey=privateKey) 
t_id = myAddress.sendWaves(recipient=pw.Address('3MwMwdzo6k1wwDE8JgiZmbM7nXEL6xmftPc'),amount = 10000000)
```

Error:
`{'error': 112, 'message': 'State check failed. Reason: invalid signature', 'tx': {'type': 4, 'id': 'BPP2CSFUBey5UybNDZpeeKJ7aEptMc2mXVmdYnUrAf3F', 'sender': '3Mq6YmrnfoSt5T36i3S2XPXpXh8kP87DUw4', 'senderPublicKey': '9u6mN4kN8U7iQVsyNaru7ko6VV3E3pQ6sqcmmDwM6k7a', 'fee': 100000, 'timestamp': 1521476122683, 'signature': '4PYFgEYtKJWG1zXQtmw3KMgR54opCnNBkfNQKieP4A6ywGNHainhfpNqnqhMwsoNeSW42C5kNyNs6K76tsSg1o3E', 'recipient': '3MwMwdzo6k1wwDE8JgiZmbM7nXEL6xmftPc', 'assetId': None, 'amount': 10000000, 'feeAsset': None, 'attachment': '1'}}`

**Comment by vsuharnikov** [comment]
@geethsameer686 Tried your code (but the node is `https://testnodes.wavesnodes.com`) and seems all work.

**Comment by Alex11211** [comment]
Получение Bitcoin
09:32, с адреса 3PAs2qSeUAfgqSKS8LpZPKGYEjJKcud9Djr
+0.00200529 Bitcoin
+18.42 US Dollar


2018-05-03 15:49 GMT+03:00 Vyatcheslav Suharnikov <notifications@github.com>
:

**Comment by monroid** [comment]
Moved to Close since the last comment was more that two months ago.
