### ISSUE TITLE
Deb packages overwriting conf file

### ISSUE THREAD

**Issue by jansenmarc** [wavesplatform/Waves#92]
It seems like a lot of people ran into problems since the .deb packages overwrite existing config files. I would suggest to provide a /etc/waves.json.dist file as an example and not overwrite the original config file. 

Additionally, a note in the release notes for new versions about potential changes to the config file would be much appreciated. :)

**Comment by Tolsi** [comment]
We fix it already, but in first deb release package it was not realized and that because you have this problem during the first update of the package. We were warned about the need to make a backup before upgrading. ;)
