### ISSUE TITLE
The requested resource could not be found but may be available again in the future. (transfer not working)

### ISSUE THREAD

**Issue by soulpapa** [wavesplatform/Waves#991]
Hello, I testing waves rest-apis in test-net.
I have encountered the error in transfer api.
I try request using curl command as below.

curl -H "Content-type: application/json" -H "X-API-KEY: ridethewaves!" -D '{"sender":"blabla~~","recipient":"blabla~~","fee":100000,"amount":5500000000,"attachment":"25bsUKfFsFF4WR7PDzStyxixxUDv"}' -X POST localhost:6869/assets/transfer

**Comment by sarosbacz** [comment]
I had the same error but it transformed with time. 
Now I'm getting :
{'error': 1, 'message': 'failed to parse json message', 'validationErrors': {'obj': [{'args': [], 'msg': ['error.expected.jsobject']}]}, 'cause': None}

**Comment by soulpapa** [comment]
Oh, My mistake !

curl option is fault. 

-D --> -d

Thanks.
